### ISSUE TITLE
建立增加一个表单防重复提交拦截

### ISSUE THREAD

**Issue by hadesvip** [elunez/eladmin#100]

**Comment by hadesvip** [comment]
补充下，如果只是vue端做处理，后台没做处理会不会有什么问题？

**Comment by elunez** [comment]
提交的时候给按钮加一个loading状态就可以了

**Comment by hadesvip** [comment]
我的意思是只是在按钮上面加loading，后台不做任何拦截处理会不会有什么问题？

**Comment by elunez** [comment]
如果某一个字段在数据库中是唯一的，后端新增或者修改的时候会拦截处理，如果没有唯一的字段，那还处理干嘛

**Comment by hadesvip** [comment]
@elunez  我说个实际场景，在页面进行操作转账操作，数据库没有唯一的字段判断的，如果你不做拦截，等于重复转账了，比如商户给会员要打10块钱，他可以分开打，第一次2块，第二次3块，第三次5块；但是意外出现了第一次出现重复提交了，等于打了两次两块，这个跟商户的预期是不一样的，这种场景，虽然最后结果不会超过10块，但是商户每次给商户转钱都是有实际意义的。
