### ISSUE TITLE
前端resetForm()函数不起作用

### ISSUE THREAD

**Issue by secondarycoder** [elunez/eladmin#101]
resetForm()无法做到清空表单
运行环境：谷歌浏览器
开发环境：vue3.8.4 node8.11.3
ps：线上演示环境也是如此，怀疑是个bug

**Comment by elunez** [comment]
不是不起作用，是没写默认关闭的事件
![image](https://user-images.githubusercontent.com/42142420/61258071-5ee53480-a7a6-11e9-9612-244c01570832.png)
https://element.eleme.cn/2.4/#/zh-CN/component/dialog 加上
![image](https://user-images.githubusercontent.com/42142420/61258079-6c022380-a7a6-11e9-9c47-c25ac37f74ab.png)就好了

**Comment by elunez** [comment]
用的是自定义的页脚，也就是说只有点取消按钮的时候才会清除数据，按esc或者右上角的 X ，都是不能清除数据的，需要清除的话得自己加一个关闭事件
