### ISSUE TITLE
1.使用内置定时任务时，线程池设置有问题

### ISSUE THREAD

**Issue by dawangdedawang5** [elunez/eladmin#106]
1.错误快照
![image](https://user-images.githubusercontent.com/30396074/63139332-7f581700-c010-11e9-8f1b-6bcd0aa74991.png)
![image](https://user-images.githubusercontent.com/30396074/63139377-b3cbd300-c010-11e9-8e97-8262f09a50d0.png)
2.错误分析
因为没有将该线程池设置为static对象，导致每次都创建了新的线程池。

**Comment by elunez** [comment]
创建新线程应该也不影响使用吧

**Comment by dawangdedawang5** [comment]
如果你一直重开线程池的话。那么如果存在每小时或者每分的任务。线程资源可能会耗尽。

**Comment by elunez** [comment]
> 如果你一直重开线程池的话。那么如果存在每小时或者每分的任务。线程资源可能会耗尽。

如果使用原有的线程，可能会堵塞

**Comment by dawangdedawang5** [comment]
> > 如果你一直重开线程池的话。那么如果存在每小时或者每分的任务。线程资源可能会耗尽。
> 
> 如果使用原有的线程，可能会堵塞
是的 可能会出现堵塞(该线程池允许无限堵塞，可能有OOM风险)。
但是如果每次都新建线程池的话，风险可能会更大。
建议加上注释：根据阿里公约，建议自定义线程池实现方式，该处仅供参考。
