### ISSUE TITLE
下载最新的数据库后 提示如下错误   但是修改对应的driverClassName还是报错(报错内容如下)

### ISSUE THREAD

**Issue by xufeng1994** [elunez/eladmin#11]
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

**Comment by xufeng1994** [comment]
![image](https://user-images.githubusercontent.com/30763520/51182937-bba48700-190a-11e9-87bb-93ba74563d93.png)

**Comment by elunez** [comment]
https://blog.csdn.net/u013276277/article/details/80255468

**Comment by elunez** [comment]
看这个能不能解决你的问题
