### ISSUE TITLE
项目很棒，几个建议

### ISSUE THREAD

**Issue by jianghanxia** [elunez/eladmin#12]
1、持久层建议不要更换，很难得国内框架不用Mybatis的。
2、建议增加部门、岗位。对应角色权限可以按照部门来划分范围。岗位可以用于很多流程设计。
3、外链增加框架内显示。

项目很棒。作者加油

**Comment by elunez** [comment]
感谢关注
持久层不会更换
2、3都可以考虑添加进去

**Comment by guotie** [comment]
还是mybatis灵活，可控，尽快上
