### ISSUE TITLE
生成代码后前端调用404

### ISSUE THREAD

**Issue by EmKs** [elunez/eladmin#123]
代码生成器生成代码后重新编译，无法访问
![微信图片_20190908125426](https://user-images.githubusercontent.com/21976086/64483580-28241b80-d237-11e9-8c07-308de5360e14.jpg)

**Comment by EmKs** [comment]
@elunez 怎么回事呢?

**Comment by elunez** [comment]
如果是在新模块中生成代码，需要注意，必须手动新建一个模块然后再生成代码

**Comment by esinhee** [comment]
@elunez 请问如何创建？差在哪个地方呢？
