### ISSUE TITLE
JwtAuthorizationTokenFilter类中关于校验的问题

### ISSUE THREAD

**Issue by fanhenghui** [elunez/eladmin#124]
if (username != null && SecurityContextHolder.getContext().getAuthentication() == null) {

            // It is not compelling necessary to load the use details from the database. You could also store the information
            // in the token and read it from it. It's up to you ;)
            JwtUser userDetails = (JwtUser)this.userDetailsService.loadUserByUsername(username);

            // For simple validation it is completely sufficient to just check the token integrity. You don't have to call
            // the database compellingly. Again it's up to you ;)
            if (jwtTokenUtil.validateToken(authToken, userDetails)) {
                UsernamePasswordAuthenticationToken authentication = new UsernamePasswordAuthenticationToken(userDetails, null, userDetails.getAuthorities());
                authentication.setDetails(new WebAuthenticationDetailsSource().buildDetails(request));
                SecurityContextHolder.getContext().setAuthentication(authentication);
            }
        }
是不是每个请求都要查询数据库获取用户信息loadUserByUsername
这样是不是会造成性能问题，我看了这个博客的评论，思路好像类似
https://blog.csdn.net/gaoleijie/article/details/82659168

**Comment by elunez** [comment]
目前是通过redis解决的
