### ISSUE TITLE
代码生成的时候右上角显示红色×提示信息，明明成功了，不知道啥情况

### ISSUE THREAD

**Issue by oweson** [elunez/eladmin#125]
？还请大佬解答

**Comment by elunez** [comment]
肯定是有部分没有生成成功，红色× 表示在生成过程中遇到了错误， 在报错前生成的代码是不会自动删除的，这个需要手动清理

**Comment by oweson** [comment]
多谢


 
---原始邮件---
发件人: "elunez"<notifications@github.com&gt;
发送时间: 2019年9月11日(星期三) 下午5:33
收件人: "elunez/eladmin"<eladmin@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"皮皮程"<570347720@QQ.com&gt;;
主题: Re: [elunez/eladmin] 代码生成的时候右上角显示红色×提示信息，明明成功了，不知道啥情况 (#125)



肯定是有部分没有生成成功，红色× 表示在生成过程中遇到了错误， 在报错前生成的代码是不会自动删除的，这个需要手动清理
