### ISSUE TITLE
mysql驱动版本过高导致启动出现警告！自己尝试修改失败

### ISSUE THREAD

**Issue by yangming9** [elunez/eladmin#126]
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

出现上面的警告在系统启动的时候，自己不知道如何修改，麻烦给一个提示，谢谢！

**Comment by elunez** [comment]
修改log4jdbc.log4j2.properties为
```
log4jdbc.spylogdelegator.name=net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
log4jdbc.auto.load.popular.drivers=false
log4jdbc.drivers=com.mysql.cj.jdbc.Driver
```
