### ISSUE TITLE
菜单管理点击修改后，再点击新增会出现报错

### ISSUE THREAD

**Issue by zhang3ii** [elunez/eladmin#129]
![image](https://user-images.githubusercontent.com/44663930/65582951-eaeab800-dfb0-11e9-9aad-d92bb1b0c7b5.png)
![image](https://user-images.githubusercontent.com/44663930/65582981-f76f1080-dfb0-11e9-9ddf-d0c4a2173d60.png)
![image](https://user-images.githubusercontent.com/44663930/65582998-02c23c00-dfb1-11e9-8e7c-d1909ce1e823.png)

**Comment by elunez** [comment]
旧的版本没有加默认关闭事件，导致关闭对话框后没有清除数据，然后新增的时候带上了ID，所以就报错了
临时解决办法：关闭对话框使用取消按钮关闭，不会出现这种问题
真正的解决办法：给对话框加一个关闭事件，@close="cancel"

**Comment by zhang3ii** [comment]
好的，谢谢大大，在菜单生成这里我还是有疑问，然后文档描述的太简练。
就是我想增加菜单，如百度外链菜单，或者是内部路径测试，代码生成之后确实放在对应的位置，
但是没有生成，这里困扰了我，是我的食用方法存在问题嘛
![image](https://user-images.githubusercontent.com/44663930/65585226-b8db5500-dfb4-11e9-9c1f-a9b867106ab0.png)
