### ISSUE TITLE
启动直接运行报错

### ISSUE THREAD

**Issue by kerwinguo** [elunez/eladmin#130]
从git上clone下代码,直接在ide运行AppRun,报错:

[0;39m[30melAdmin-[0;39m [31m2019-09-26 14:07:53[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35morg.hibernate.Version[0;39m - [1;30mHHH000412: Hibernate Core {5.3.7.Final}
[0;39m[30melAdmin-[0;39m [31m2019-09-26 14:07:53[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35morg.hibernate.cfg.Environment[0;39m - [1;30mHHH000206: hibernate.properties not found
[0;39m[30melAdmin-[0;39m [31m2019-09-26 14:07:53[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.h.annotations.common.Version[0;39m - [1;30mHCANN000001: Hibernate Commons Annotations {5.0.4.Final}
[0;39m[30melAdmin-[0;39m [31m2019-09-26 14:07:54[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35morg.hibernate.dialect.Dialect[0;39m - [1;30mHHH000400: Using dialect: org.hibernate.dialect.MySQL5InnoDBDialect
[0;39m[30melAdmin-[0;39m [31m2019-09-26 14:07:55[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.o.j.LocalContainerEntityManagerFactoryBean[0;39m - [1;30mInitialized JPA EntityManagerFactory for persistence unit 'default'
[0;39m[30melAdmin-[0;39m [31m2019-09-26 14:07:56[0;39m [32m[main][0;39m [1;31mERROR[0;39m [1;35mo.s.b.w.e.tomcat.TomcatStarter[0;39m - [1;30mError starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'jwtAuthorizationTokenFilter' defined in file [/Users/kerwin/git/eladmin/eladmin-system/target/classes/me/zhengjie/modules/security/security/JwtAuthorizationTokenFilter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jwtUserDetailsService': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'userMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'me.zhengjie.modules.system.service.mapper.UserMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
[0;39m[30melAdmin-[0;39m [31m2019-09-26 14:07:56[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.a.catalina.core.StandardService[0;39m - [1;30mStopping service [Tomcat]
[0;39m[30melAdmin-[0;39m [31m2019-09-26 14:07:56[0;39m [32m[main][0;39m [31mWARN [0;39m [1;35mo.a.c.loader.WebappClassLoaderBase[0;39m - [1;30mThe web application [ROOT] appears to have started a thread named [Druid-ConnectionPool-Create-1442249061] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2443)
[0;39m[30melAdmin-[0;39m [31m2019-09-26 14:07:56[0;39m [32m[main][0;39m [31mWARN [0;39m [1;35mo.a.c.loader.WebappClassLoaderBase[0;39m - [1;30mThe web application [ROOT] appears to have started a thread named [Druid-ConnectionPool-Destroy-1442249061] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:2540)
[0;39m[30melAdmin-[0;39m [31m2019-09-26 14:07:56[0;39m [32m[main][0;39m [31mWARN [0;39m [1;35mo.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext[0;39m - [1;30mException encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
[0;39m[30melAdmin-[0;39m [31m2019-09-26 14:07:56[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.o.j.LocalContainerEntityManagerFactoryBean[0;39m - [1;30mClosing JPA EntityManagerFactory for persistence unit 'default'
[0;39m[30melAdmin-[0;39m [31m2019-09-26 14:07:56[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mc.alibaba.druid.pool.DruidDataSource[0;39m - [1;30m{dataSource-1} closed
[0;39m[30melAdmin-[0;39m [31m2019-09-26 14:07:56[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.b.a.l.ConditionEvaluationReportLoggingListener[0;39m - [1;30m

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[0;39m[30melAdmin-[0;39m [31m2019-09-26 14:07:56[0;39m [32m[main][0;39m [1;31mERROR[0;39m [1;35mo.s.b.d.LoggingFailureAnalysisReporter[0;39m - [1;30m

***************************
APPLICATION FAILED TO START
***************************

Description:

Field userMapper in me.zhengjie.modules.system.service.impl.UserServiceImpl required a bean of type 'me.zhengjie.modules.system.service.mapper.UserMapper' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Qualifier(value=jwtUserDetailsService)

Action:

Consider defining a bean of type 'me.zhengjie.modules.system.service.mapper.UserMapper' in your configuration.

[0;39m

**Comment by elunez** [comment]
看文档

**Comment by kerwinguo** [comment]
感谢,确实在文档常见问题里第二个就是,辛苦作者整理.项目很赞
