### ISSUE TITLE
跨服务器autoType is not support.

### ISSUE THREAD

**Issue by ZhiHao1** [elunez/eladmin#133]
服务器启动，前端在本地启动，访问的过程中新写的业务就会报autoType is not support，但是项目中自带的mysql增删改查没有问题，请教下。（orm框架我用的mybatis）
我已在redisConfig。Java中添加了
`
ParserConfig.getGlobalInstance().addAccept("cn.net.polyinfo.learning.persona.readerPersona.entity");
`

**Comment by elunez** [comment]
返回用的是DTO，包路径不对
