### ISSUE TITLE
太多的编译告警提示

### ISSUE THREAD

**Issue by zhlonggang** [elunez/eladmin#134]
![image](https://user-images.githubusercontent.com/46254984/65829677-606cc600-e2da-11e9-81a9-71a0cdaea78e.png)

编译告警提示有点多，影响视觉啊

**Comment by zhlonggang** [comment]
这个问题为啥直接关闭呢？

**Comment by elunez** [comment]
> 这个问题为啥直接关闭呢？

影响使用吗？不影响使用就没太大的必要去在意，下个版本会优化

**Comment by zhlonggang** [comment]
倒是不影响运行，只是不太严谨。

期待下个版本。
