### ISSUE TITLE
当前数据权限过滤只应用在查询中？

### ISSUE THREAD

**Issue by its404** [elunez/eladmin#144]
首先，请问数据权限隔离是通过 `criteria.setDeptIds` 实现的么？
代码中我只在查询中找到数据权限过滤，对于增，删，改没有找到，请问当前版本对这几个操作是否有数据权限隔离支持？谢谢！

**Comment by elunez** [comment]
目前只对查进行了过滤，修改、删除，暂未实现，实现方式类似，可以自定义实现
