### ISSUE TITLE
当浏览器分屏大小情况下，点击侧边栏选项，会弹出部分其他选项，其余选项消失

### ISSUE THREAD

**Issue by 460678244** [elunez/eladmin#148]
![微信截图_20191018170430](https://user-images.githubusercontent.com/31058765/67081312-7a0e7880-f1c9-11e9-87ba-daf2f6eebed2.png)
![微信截图_20191018170445](https://user-images.githubusercontent.com/31058765/67081315-7a0e7880-f1c9-11e9-8eb6-c995385e6e34.png)

**Comment by elunez** [comment]
测试发现并未出现这种bug
