### ISSUE TITLE
菜单 icon 问题

### ISSUE THREAD

**Issue by HelloMeme** [elunez/eladmin#150]
新建菜单，如果不设置 icon ，即使授权了，菜单依然不显示在左侧导航中。

**Comment by elunez** [comment]
> 新建菜单，如果不设置 icon ，即使授权了，菜单依然不显示在左侧导航中。

测试并无问题，
![image](https://user-images.githubusercontent.com/42142420/67634317-387e7b80-f8f5-11e9-8174-6602ed573891.png)
