### ISSUE TITLE
菜单管理页面的“操作”独立bug，不与前面的行相匹配

### ISSUE THREAD

**Issue by liuzhengcast** [elunez/eladmin#152]
操作一列的修改和删除 ，与名称、图标等列的行高不一致的，导致独立出前面的行。
而且操作一列的行数少于名称的行数。
目前仅在菜单折叠起来时行高和行数一致，当菜单展开时发生不一致现象

**Comment by elunez** [comment]
请提供图片

**Comment by liuzhengcast** [comment]
您好，很高兴得到您的回复
图片详见附件，图1是有bug不一致的图片，图2是在折叠起来时能够一致的图片。


| |
Liu Zheng 刘政
|
|
liuzhengbusiness@163.com
|
签名由网易邮箱大师定制


在2019年10月24日 21:14，elunez<notifications@github.com> 写道：

请提供图片

**Comment by elunez** [comment]
> 图片详见附件，图1是有bug不一致的图片，图2是在折叠起来时能够一致的图片。 <img width="1251" alt="Screen Shot 2019-10-25 at 9 25 13 AM" src="https://user-images.githubusercontent.com/39894192/67536537-402dfc80-f70a-11e9-9e5b-1b16eedaa808.png"> <img width="1251" alt="Screen Shot 2019-10-25 at 9 28 48 AM" src="https://user-images.githubusercontent.com/39894192/67536539-4328ed00-f70a-11e9-88ad-a989b0871631.png">

树形表格替换为element-ui自带的就可以了，https://element.eleme.cn/2.11/#/zh-CN/component/table
![image](https://user-images.githubusercontent.com/42142420/67633254-c1db8100-f8e8-11e9-91fc-c5a2cb574d7d.png)

**Comment by liuzhengcast** [comment]
代码会在下个发布版本发布中修复吗？

**Comment by elunez** [comment]
> 代码会在下个发布版本发布中修复吗？

已更新在2.3dev分支

**Comment by liuzhengcast** [comment]
系统管理还存在同样的bug未修复。
<img width="1251" alt="Screen Shot 2019-10-28 at 11 16 38 AM" src="https://user-images.githubusercontent.com/39894192/67649674-06acf980-f975-11e9-9194-af20459c317e.png">

**Comment by elunez** [comment]
> 系统管理还存在同样的bug未修复。
> <img alt="Screen Shot 2019-10-28 at 11 16 38 AM" width="1251" src="https://user-images.githubusercontent.com/39894192/67649674-06acf980-f975-11e9-9194-af20459c317e.png">

我测试无问题，你可以向element-ui提issues

**Comment by liuzhengcast** [comment]
在chrome浏览器中没问题，在safari中存在此问题
