### ISSUE TITLE
权限管理对角色权限的影响

### ISSUE THREAD

**Issue by KingFeng0816** [elunez/eladmin#154]
编辑权限名称不会对已分配给角色的权限产生影响吗？，比如字典删除权限名称为“DICT_DELETE”,已分配给普通管理员角色，然后修改字典删除权限名称为“DICT_DEL”,此时普通管理员仍然可以对字典进行删除操作。这个是BUG吗？

**Comment by jackytang** [comment]
修改了以后，要重新登录才能获取到最新的权限以后才会生效吧

**Comment by elunez** [comment]
测试后并无问题
