### ISSUE TITLE
dev分支登陆状态已过期

### ISSUE THREAD

**Issue by liuzhengcast** [elunez/eladmin#157]
登陆提示，点击确定后仍然提示，进入死循环

<img width="677" alt="Screen Shot 2019-10-28 at 12 01 03 PM" src="https://user-images.githubusercontent.com/39894192/67651183-d700f000-f97a-11e9-9f4b-ff39dd19685f.png">

**Comment by elunez** [comment]
前端代码也要用dev分支的
