### ISSUE TITLE
[suggest] 建议导出SQL语句时可以按里程碑增量导出

### ISSUE THREAD

**Issue by everhopingandwaiting** [elunez/eladmin#160]
由于有已经基于此项目二次开发的项目，每次如果eladmin表结构发生变动，如果采用提供的SQL语句再建表会丢失自定义维护数据，建议版本升级时可以 把发布前后之间的SQL变动语句提供

**Comment by elunez** [comment]
感觉2.3改动挺大的，权限管理去掉了，已按钮形式存入菜单管理中

**Comment by liuzhengcast** [comment]
建议将eladmin.sql文件拆分为两个独立的文件

- schea.sql 文件，建立表结构
-test-data.sql 文件， 数据文件
