### ISSUE TITLE
[feature] 代码生成器建议增加父子表crud通用操作代码

### ISSUE THREAD

**Issue by everhopingandwaiting** [elunez/eladmin#162]
参考 jeecg boot 代码生成器效果， 如果作者有意改造，我可以添砖加瓦部分代码

**Comment by elunez** [comment]
> 参考 jeecg boot 代码生成器效果， 如果作者有意改造，我可以添砖加瓦部分代码

2.4 版本将基础的crud给优化了，2.5 版本做这一块的优化
