### ISSUE TITLE
系统缓存页面、代码生成页面显示排版

### ISSUE THREAD

**Issue by liuzhengcast** [elunez/eladmin#164]
在系统缓存页面，当选择50条记录每页时出现序号上下排列显示bug，见图1左列数字
<img width="1358" alt="Screen Shot 2019-10-31 at 10 28 28 AM" src="https://user-images.githubusercontent.com/39894192/67913874-66034780-fbc9-11e9-8a1b-4b2794240e0a.png">
在代码生成页面，模块名称、至于包下等均为两行显示，排版显示界面不友好，见图2
<img width="843" alt="Screen Shot 2019-10-31 at 10 46 04 AM" src="https://user-images.githubusercontent.com/39894192/67914767-035f7b00-fbcc-11e9-813a-7c8652564d36.png">

**Comment by elunez** [comment]
缓存页面的序号没啥用，去掉吧，代码生成页面 调整下 label-width
