### ISSUE TITLE
Validated提示信息格式的问题

### ISSUE THREAD

**Issue by kerwinguo** [elunez/eladmin#165]
问题描述:
1.在对象User属性name里添加@NotBlank(message = "名字不正确")的注解
2.在控制层@Validated @RequestBody User
3.页面如果不传递参数,返回给页面的提示信息是name:名字不正确

预期:希望只是提示message里的信息"名字不正确",为何多了个前缀"属性名:"呢

想请问下,这个格式在哪里配置的吗,还是默认的,是否可以修改呢,非常感谢.

**Comment by elunez** [comment]
> 问题描述:
> 1.在对象User属性name里添加@notblank(message = "名字不正确")的注解
> 2.在控制层@Validated @requestbody User
> 3.页面如果不传递参数,返回给页面的提示信息是name:名字不正确
> 
> 预期:希望只是提示message里的信息"名字不正确",为何多了个前缀"属性名:"呢
> 
> 想请问下,这个格式在哪里配置的吗,还是默认的,是否可以修改呢,非常感谢.

可以在 GlobalExceptionHandler 中的 handleMethodArgumentNotValidException 方法里面修改

**Comment by kerwinguo** [comment]
感谢,楼主大大真nice~
