### ISSUE TITLE
[question] 接口权限类似ROLES_ALL这种配置感觉挺好使的，为啥2.3要改成每个接口单个权限

### ISSUE THREAD

**Issue by everhopingandwaiting** [elunez/eladmin#168]
我看`@el.check(String ...str)` 预留了多个权限列表的传参方式，可是项目里好像都重构成单配置了，不知作者有何考量

**Comment by elunez** [comment]
类似这样**@PreAuthorize("hasAnyRole('ADMIN','DICT_ALL','DICT_SELECT')")**，每个接口都得预留一个 ADMIN 的权限， 这样还不如用自定义的权限验证，然后自定义的权限验证方法中给 管理员一个默认的权限，如果是管理员就放行。看着像单配置，其实不是

具体使用 hasAnyRole 还是 @el.check 这个就随个人了
