### ISSUE TITLE
下的源码，就改了一下配置，报下面的异常。根据错误检查了一下，相应的文件都在。

### ISSUE THREAD

**Issue by fusxAbc** [elunez/eladmin#173]
下的源码，就改了一下配置，报下面的异常。根据错误检查了一下，相应的文件都在。

[0;39m[30melAdmin-[0;39m [31m2019-11-04 09:33:45[0;39m [32m[main][0;39m [31mWARN [0;39m [1;35mo.a.c.loader.WebappClassLoaderBase[0;39m - [1;30mThe web application [ROOT] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)
[0;39m[30melAdmin-[0;39m [31m2019-11-04 09:33:45[0;39m [32m[main][0;39m [31mWARN [0;39m [1;35mo.a.c.loader.WebappClassLoaderBase[0;39m - [1;30mThe web application [ROOT] appears to have started a thread named [Druid-ConnectionPool-Create-546619197] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2443)
[0;39m[30melAdmin-[0;39m [31m2019-11-04 09:33:45[0;39m [32m[main][0;39m [31mWARN [0;39m [1;35mo.a.c.loader.WebappClassLoaderBase[0;39m - [1;30mThe web application [ROOT] appears to have started a thread named [Druid-ConnectionPool-Destroy-546619197] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:2540)
[0;39m[30melAdmin-[0;39m [31m2019-11-04 09:33:45[0;39m [32m[main][0;39m [31mWARN [0;39m [1;35mo.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext[0;39m - [1;30mException encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
[0;39m[30melAdmin-[0;39m [31m2019-11-04 09:33:45[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.o.j.LocalContainerEntityManagerFactoryBean[0;39m - [1;30mClosing JPA EntityManagerFactory for persistence unit 'default'
[0;39m[30melAdmin-[0;39m [31m2019-11-04 09:33:45[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mc.alibaba.druid.pool.DruidDataSource[0;39m - [1;30m{dataSource-1} closed
[0;39m[30melAdmin-[0;39m [31m2019-11-04 09:33:45[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.b.a.l.ConditionEvaluationReportLoggingListener[0;39m - [1;30m

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[0;39m[30melAdmin-[0;39m [31m2019-11-04 09:33:46[0;39m [32m[main][0;39m [1;31mERROR[0;39m [1;35mo.s.b.d.LoggingFailureAnalysisReporter[0;39m - [1;30m

***************************
APPLICATION FAILED TO START
***************************

Description:

Field userMapper in me.zhengjie.modules.system.service.impl.UserServiceImpl required a bean of type 'me.zhengjie.modules.system.service.mapper.UserMapper' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Qualifier(value=jwtUserDetailsService)

Action:

Consider defining a bean of type 'me.zhengjie.modules.system.service.mapper.UserMapper' in your configuration.

[0;39m

**Comment by elunez** [comment]
看文档：[https://docs.auauz.net/#/cjwt?id=启动报mapper找不到](https://docs.auauz.net/#/cjwt?id=启动报mapper找不到)
