### ISSUE TITLE
RestTemplate 建议封装成一个工具类

### ISSUE THREAD

**Issue by zenghuabin** [elunez/eladmin#18]
RestTemplate 建议封装成我们使用httpUtil 那样子的方式，方便使用

**Comment by elunez** [comment]
可以考虑

**Comment by elunez** [comment]
可以使用https://hutool.cn/docs/#/http/Http%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%B7%A5%E5%85%B7%E7%B1%BB-HttpUtil
