### ISSUE TITLE
%、_、[、]等符号查询报错。

### ISSUE THREAD

**Issue by rxiu** [elunez/eladmin#185]
试了几个模块的查询都有类似问题。
%和_符号过滤不了数据。这应该是mysql的问题。
![QQ截图20191107140747](https://user-images.githubusercontent.com/18202841/68364279-7175e600-0168-11ea-9342-ee5096436ff4.png)
![QQ截图20191107140759](https://user-images.githubusercontent.com/18202841/68364303-7fc40200-0168-11ea-9bc8-dfc58187eda1.png)

中括号直接查询异常了
![QQ截图20191107140814](https://user-images.githubusercontent.com/18202841/68364323-936f6880-0168-11ea-99f3-506bc5f3f206.png)

**Comment by elunez** [comment]
url 中可能不允许出现这种符号，你 f12 看，很明显没有进去到系统

**Comment by rxiu** [comment]
中括号是spring boot问题。但是有解决方法。
[关于SpringBoot 请求参数包含 []　特殊符号　返回400状态](https://blog.csdn.net/liuzhu4728/article/details/88222056)

百分号和下划线打开 F12是有进到后台的吧。我查了下是sql语句的问题。如果是mysql的话，查询语句需要用escape关键字。
![image](https://user-images.githubusercontent.com/18202841/68373620-38e10700-017e-11ea-8049-494e10eb31f7.png)

**Comment by elunez** [comment]
> 中括号是代码程序的问题。但是有解决方法。可以参考springboot的解决方案。
> [关于SpringBoot 请求参数包含 []　特殊符号　返回400状态](https://blog.csdn.net/liuzhu4728/article/details/88222056)
> 
> 百分号和下划线打开 F12是有进到后台的吧。我查了下是sql语句的问题。如果是mysql的话，查询语句需要用escape关键字。
> ![image](https://user-images.githubusercontent.com/18202841/68373620-38e10700-017e-11ea-8049-494e10eb31f7.png)
_  %  作为mysql通配符，一般名称都不会有这个，如果存在的话，就自行解决吧
