### ISSUE TITLE
存储管理-点击预览图预览后没有关闭的地方，建议有点击屏幕其他关闭

### ISSUE THREAD

**Issue by youcyousyunn** [elunez/eladmin#188]
![image](https://user-images.githubusercontent.com/20416034/68466664-d48e7800-024f-11ea-84d2-60df8af4b634.png)
![image](https://user-images.githubusercontent.com/20416034/68466686-dd7f4980-024f-11ea-96a3-a21cbd0f509a.png)

**Comment by elunez** [comment]
取消固定header即可 
![image](https://user-images.githubusercontent.com/42142420/68477383-51c5e700-0268-11ea-9bbd-02fa376c65f6.png)

**Comment by elunez** [comment]
或者在 src\views\tools\storage\local\index.vue 的<style scoped>中加入css
```css
/deep/ .el-image-viewer__wrapper{
    top: 84px;
  }
```
