### ISSUE TITLE
Menu排序问题

### ISSUE THREAD

**Issue by CCCY0** [elunez/eladmin#193]
如果一个user有两个role: roleA和roleB,  roleA有角色管理菜单, roleB有用户管理菜单, 在构建菜单时是依次查询roles所对应的菜单列表的, 那么如何保证这两个菜单的sort排序呢

**Comment by elunez** [comment]
> 如果一个user有两个role: roleA和roleB, roleA有角色管理菜单, roleB有用户管理菜单, 在构建菜单时是依次查询roles所对应的菜单列表的, 那么如何保证这两个菜单的sort排序呢

感谢反馈，已手动合并
