### ISSUE TITLE
menu索引的名字为什么是FKqcf9gem97gqa5qjm4d3elcqt5`(`pid`)?

### ISSUE THREAD

**Issue by wufannet** [elunez/eladmin#195]
INDEX `FKqcf9gem97gqa5qjm4d3elcqt5`(`pid`) USING BTREE

**Comment by elunez** [comment]
> INDEX `FKqcf9gem97gqa5qjm4d3elcqt5`(`pid`) USING BTREE

Jpa 自动生成的
