### ISSUE TITLE
项目分层乱、思路能说一下么？

### ISSUE THREAD

**Issue by zyfsuzy** [elunez/eladmin#196]

**Comment by elunez** [comment]
> _No description provided._

按功能分模块，分层乱？乱在哪儿，请教下

**Comment by zyfsuzy** [comment]
> > _No description provided._
> 
> 按功能分模块，分层乱？乱在哪儿，请教下

Configuration  和 Component  注解有区别么？

**Comment by elunez** [comment]
> > > _No description provided._
> > 
> > 
> > 按功能分模块，分层乱？乱在哪儿，请教下
> 
> Configuration 和 Component 注解有区别么？

@Configuration 我一般用在配置类上，https://www.baidu.com/s?ie=UTF-8&wd=Configuration+%E5%92%8C+Component+%E6%B3%A8%E8%A7%A3%E6%9C%89%E5%8C%BA%E5%88%AB%E4%B9%88&bn=centbrowser&tn=02003390_hao_pg 
这个和分层乱有啥关系？

**Comment by zyfsuzy** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > 按功能分模块，分层乱？乱在哪儿，请教下
> > 
> > 
> > Configuration 和 Component 注解有区别么？
> 
> @configuration 我一般用在配置类上，https://www.baidu.com/s?ie=UTF-8&wd=Configuration+%E5%92%8C+Component+%E6%B3%A8%E8%A7%A3%E6%9C%89%E5%8C%BA%E5%88%AB%E4%B9%88&bn=centbrowser&tn=02003390_hao_pg
> 这个和分层乱有啥关系？

还是有区别的，更好的建议分开目录，思路结构清晰些，当然这只是建议哈，看个人习惯了！

**Comment by zyfsuzy** [comment]
> > > > > _No description provided._
> > > > 
> > > > 
> > > > 按功能分模块，分层乱？乱在哪儿，请教下
> > > 
> > > 
> > > Configuration 和 Component 注解有区别么？
> > 
> > 
> > @configuration 我一般用在配置类上，https://www.baidu.com/s?ie=UTF-8&wd=Configuration+%E5%92%8C+Component+%E6%B3%A8%E8%A7%A3%E6%9C%89%E5%8C%BA%E5%88%AB%E4%B9%88&bn=centbrowser&tn=02003390_hao_pg
> > 这个和分层乱有啥关系？
> 
> 还是有区别的，更好的建议分开目录，思路结构清晰些，当然这只是建议哈，看个人习惯了！



> > _No description provided._
> 
> 按功能分模块，分层乱？乱在哪儿，请教下

项目结构可以参考：https://github.com/macrozheng/mall   个人建议哈
