### ISSUE TITLE
列表页按照开始时间和结束时间查询BUG

### ISSUE THREAD

**Issue by janyyy** [elunez/eladmin#197]
![image](https://user-images.githubusercontent.com/27274865/68993878-acd68a00-08b7-11ea-8382-a59e92a633c8.png)
![image](https://user-images.githubusercontent.com/27274865/68993881-b3fd9800-08b7-11ea-9433-71f659d929b0.png)

**Comment by janyyy** [comment]
其他查询也测试一下，感觉不可以

**Comment by elunez** [comment]
> 其他查询也测试一下，感觉不可以

![image](https://user-images.githubusercontent.com/42142420/69003337-ab01da80-093a-11ea-9437-28df508fcf5b.png)
日期控件的问题，结束日期没有给 23:59:59

**Comment by elunez** [comment]
> 其他查询也测试一下，感觉不可以
这样就可以了
:default-time="['00:00:00','23:59:59']"

![image](https://user-images.githubusercontent.com/42142420/69003377-d0431880-093b-11ea-92bc-53f26fbf3516.png)

**Comment by janyyy** [comment]
谢谢，解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"elunez"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月17日(星期天) 中午1:12
收件人:&nbsp;"elunez/eladmin"<eladmin@noreply.github.com&gt;;
抄送:&nbsp;"酱油"<597907730@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [elunez/eladmin] 列表页按照开始时间和结束时间查询BUG (#197)



 
其他查询也测试一下，感觉不可以
 这样就可以了
 :default-time="['00:00:00','23:59:59']"
