### ISSUE TITLE
实体对象主键为long类型时转JSON，前台接受到会丢失精度。

### ISSUE THREAD

**Issue by d15801543974** [elunez/eladmin#199]
出现问题的场景：分布式项目中，我为了保证主键唯一使用hutool主键生成方法 来获取主键。Long类型 长度18.  这种情况下 vue接收到的主键会丢失精度。需要在主键加上注解 @JsonSerialize(using = ToStringSerializer.class)

**Comment by elunez** [comment]
代码生成器中实现了这个功能，如果主键类型为 Long，并且不是自增，就会使用IdUtil.createSnowflake(1, 1) 生成主键，并且在Dto中加入了 @JsonSerialize(using= ToStringSerializer.class)
