### ISSUE TITLE
角色管理菜单分配时勾选父级节点子节点没有联动效果的bug

### ISSUE THREAD

**Issue by kuqi007** [elunez/eladmin#201]
![微信图片_20191127103535](https://user-images.githubusercontent.com/14246858/69688771-f8800380-1101-11ea-9319-2325915bd758.png)

**Comment by kuqi007** [comment]
正常应该是勾选父节点子节点也会被勾选上，取消勾选时候同理。

**Comment by elunez** [comment]
> 正常应该是勾选父节点子节点也会被勾选上，取消勾选时候同理。

不是bug，是故意为之，试想下，如果勾选了用户管理，但是我只想要用户有查询权限，这样是不是没法实现。用户管理是菜单也是权限

**Comment by kuqi007** [comment]
哇 那批量添加权限就比较麻烦勒
