### ISSUE TITLE
最新文档源码能否提交到GitHub？

### ISSUE THREAD

**Issue by kuqi007** [elunez/eladmin#202]
GitHub上源码还是很久之前更新的，想参考一下最新的文档源码，十分感谢。

**Comment by elunez** [comment]
> GitHub上源码还是很久之前更新的，想参考一下最新的文档源码，十分感谢。

已经更新啦，https://github.com/elunez/eladmin-doc

**Comment by kuqi007** [comment]
非常感谢！
