### ISSUE TITLE
SecurityConfig 里自定义PreAuthorize（“anonymous”）注解是否重复？

### ISSUE THREAD

**Issue by leezshow945** [elunez/eladmin#203]
因为方法中带有@AnonymousAccess 注解就已经代表开放权限，在@PreAuthorize（“anonymous”）加此处是具体有何效果，并且全局搜索只有testLImit方法处使用 是否直接优化 anonymousUrls add逻辑

**Comment by leezshow945** [comment]
个人理解接口handler处配置这2个自定义注解为的就是 401 403的授权，只是2.3版本理解起来似乎有点奇怪 403中包含401... 是不是为了校验一定需要token时的应用场景

**Comment by leezshow945** [comment]
![image](https://user-images.githubusercontent.com/44184768/69720054-c21ba600-114c-11ea-990a-6214e666ca04.png)
还有这一段的判断逻辑 打过debug.AnonymousAccess与PreAuthorize 都是只存在一个的 不会存在
null != anonymousAccess && null != preAuthorize  双注解同时存在的逻辑 是否有点误导

**Comment by elunez** [comment]
> ![image](https://user-images.githubusercontent.com/44184768/69720054-c21ba600-114c-11ea-990a-6214e666ca04.png)
> 还有这一段的判断逻辑 打过debug.AnonymousAccess与PreAuthorize 都是只存在一个的 不会存在
> null != anonymousAccess && null != preAuthorize 双注解同时存在的逻辑 是否有点误导

// 自定义匿名接口
@AnonymousAccess
// 标识为匿名接口
@PreAuthorize("hasRole('anonymous')")
// 标识为匿名接口
@PreAuthorize("@el.check('anonymous')")

定义了三种方式，是让用户根据自己的使用情况选择

**Comment by elunez** [comment]
2.4 版本打算去除这两个，统一使用@AnonymousAccess
// 标识为匿名接口
@PreAuthorize("hasRole('anonymous')")
// 标识为匿名接口
@PreAuthorize("@el.check('anonymous')")
