### ISSUE TITLE
自动生成的前端代码无法下载附件

### ISSUE THREAD

**Issue by kreee** [elunez/eladmin#204]
为什么这个模板eladmin-system/src/main/resources/template/generator/front/index.ftl里面的88行要判断hasTimestamp。我看了后台代码，返回的数据要有时间戳属性才能下载附件吗？不太符合正常需求。

**Comment by elunez** [comment]
什么意思，hasTimestamp 这个是导包时用的
![image](https://user-images.githubusercontent.com/42142420/69803990-8a7a3000-1218-11ea-9a33-9923685024a2.png)
