### ISSUE TITLE
menu菜单表主键ID问题

### ISSUE THREAD

**Issue by janyyy** [elunez/eladmin#206]
在进行业务开发后，自己业务菜单新增了生成一些ID。但是楼主更新框架的时候又添加了一些新的菜单，新增的菜单和我们业务菜单ID重叠。  是否考虑菜单ID  用uuid去优化呢。这样既能跟随框架更新，又能不影响业务菜单。

**Comment by elunez** [comment]
由于主键是自增的，所以导入的时候可以把 ID 字段设置为 NULL，这样就不会和你数据库的菜单主键冲突了
![image](https://user-images.githubusercontent.com/42142420/69803504-4fc3c800-1217-11ea-97ea-2edfdefb5673.png)
