### ISSUE TITLE
如何独立业务模块与框架模块

### ISSUE THREAD

**Issue by leezshow945** [elunez/eladmin#207]
目前有2张方案 第一种集成jpa 多数据源，并将代码生成至框架体系内；优点是代码一键生成，兼容性高，资源整合，缺点是耦合度过高，整合多个业务模块造成体系架子越来越重。如图所示：
![image](https://user-images.githubusercontent.com/44184768/69849669-55251f00-12b8-11ea-8585-2e05f7b90ba9.png)

**Comment by leezshow945** [comment]
另外一种方案目前还在探索，所以想问下author，如果说我自己独立有暴露http接口的服务，然后保持和框架项目通用的Security鉴权，这样是否可以达到所有原生权限菜单等框架模块独立在一个工程，其他自定义业务菜单数据交互 走的我自己独立的服务接口呢，具体是在前端配置多个数据API接口吗？

**Comment by jiaxinxuan** [comment]
> 目前有2张方案 第一种集成jpa 多数据源，并将代码生成至框架体系内；优点是代码一键生成，兼容性高，资源整合，缺点是耦合度过高，整合多个业务模块造成体系架子越来越重。如图所示：
> ![image](https://user-images.githubusercontent.com/44184768/69849669-55251f00-12b8-11ea-8585-2e05f7b90ba9.png)

分库的实现，方便分享下吗

**Comment by leezshow945** [comment]
> > 目前有2张方案 第一种集成jpa 多数据源，并将代码生成至框架体系内；优点是代码一键生成，兼容性高，资源整合，缺点是耦合度过高，整合多个业务模块造成体系架子越来越重。如图所示：
> > ![image](https://user-images.githubusercontent.com/44184768/69849669-55251f00-12b8-11ea-8585-2e05f7b90ba9.png)
> 
> 分库的实现，方便分享下吗

这个分库很简单的就是 jpa最简单的分库，然后配置bean 各扫各的datesource 和 rep目录
