### ISSUE TITLE
『登录状态已过期，您可以继续留在该页面，或者重新登录』的死循环

### ISSUE THREAD

**Issue by msh01** [elunez/eladmin#208]
登录页出现『登录状态已过期，您可以继续留在该页面，或者重新登录』的提示后，点击重新登录，依旧停留在登录页，继续展示该提示。

试过清除浏览器缓存，重启后端服务，重启前端服务，重启浏览器，全部不顶用。快被这个bug整到崩溃了

chrome控制台显示如下信息：
```
xhr.js:172 GET http://localhost:8013/auth/code 401 (Unauthorized)
createError.js:16 Uncaught (in promise) Error: Request failed with status code 401
```

![image](https://user-images.githubusercontent.com/5895871/69900956-6142d680-13b5-11ea-8364-3737704dba71.png)

**Comment by Creky** [comment]
解决方案：SecurityConfig.java 中 configure方法某行修改为(临时解决办法)：
`.antMatchers("/login", "/captchaImage","/prod-api/captchaImage").anonymous()`，
CaptchaController.java 中 getCode 的方法修改为：@GetMapping("**/captchaImage")

**Comment by Creky** [comment]
有可能是验证码权限和路径问题综合导致的，解决方案：SecurityConfig.java 中 configure方法某行修改为：
`.antMatchers("/login", "/**/captchaImage").anonymous()`，
CaptchaController.java 中 getCode 的方法注解修改为：@GetMapping("**/captchaImage")
Nginx 的配置文件 proxy_pass http://localhost:8080/;  一行，分号前面要以 / 结尾，切记切记！
