### ISSUE TITLE
生成代码，编辑的时候，逻辑有问题

### ISSUE THREAD

**Issue by zoulejiu** [elunez/eladmin#221]
![image](https://user-images.githubusercontent.com/31949635/70972804-365bc080-20df-11ea-9c7d-543de9a81299.png)
如果之前生成过，代码的逻辑是直接拿出来，但是之前生成过，如果中途改动了字段，是无法识别到的

**Comment by elunez** [comment]
> ![image](https://user-images.githubusercontent.com/31949635/70972804-365bc080-20df-11ea-9c7d-543de9a81299.png)
> 如果之前生成过，代码的逻辑是直接拿出来，但是之前生成过，如果中途改动了字段，是无法识别到的

会有个同步按钮，现在还没加上的
