### ISSUE TITLE
将代码放到测试环境，报打开文件过多错误！

### ISSUE THREAD

**Issue by wurainren** [elunez/eladmin#225]
如下图所示：
[
![image](https://user-images.githubusercontent.com/6847208/71138110-54433580-2245-11ea-82ef-6057d1954e11.png)
](url)

按照提示信息：一直在打开ip2region.db文件

**Comment by elunez** [comment]
什么版本

**Comment by elunez** [comment]
> 如下图所示：
> [ ![image](https://user-images.githubusercontent.com/6847208/71138110-54433580-2245-11ea-82ef-6057d1954e11.png) ](url)
> 
> 按照提示信息：一直在打开ip2region.db文件

2.4 已修复

**Comment by loveyuncheng** [comment]
怎么修复的我也有这种问题，从代码层面吗？
