### ISSUE TITLE
2.3前端升级2.4,哪些地方需要地方变动，需要如何替换，可以出个简短的说明吗

### ISSUE THREAD

**Issue by sxhjlzl** [elunez/eladmin#227]
2.3前端升级2.4,哪些地方需要地方变动，需要如何替换，可以出个简短的说明吗

**Comment by sunw31** [comment]
不建议升级，建议直接用 2.4，提醒注意前后端代码版本要匹配。

**Comment by elunez** [comment]
升级cli3  可以直接将业务代码直接复制进去，然后逐步排错
