### ISSUE TITLE
2.5 版本意见征集

### ISSUE THREAD

**Issue by elunez** [elunez/eladmin#231]
征集截至日期 2020年1月15日

**Comment by elunez** [comment]
拖拉拽的表单设计

**Comment by Charles7c** [comment]
通知系统

**Comment by sunw31** [comment]
基础功能参考 

1/ 物联网设备管理 支持 mqtt 主流协议
https://github.com/jetlinks

2/ 和 ruoyi-vue 竞争
 https://gitee.com/y_project/RuoYi-Vue
___________________

业务参考 rageframe2 
https://github.com/jianyan74/rageframe2

**Comment by mrdong916** [comment]
集成ES搜索那个

**Comment by ttnkh21** [comment]
数据库操作是否考虑更换成 querydsl-jpa并去掉所有外键？

**Comment by elunez** [comment]
> 数据库操作是否考虑更换成 querydsl-jpa并去掉所有外键？

这个可以

**Comment by elunez** [comment]
> 通知系统

这个可以

**Comment by winnerczr** [comment]
希望增加用户兼职功能。

**Comment by d15801543974** [comment]
可以考虑使用 spring cloud ,把项目做成分布式的二次开发框架。应该会有更多企业级的用户使用

**Comment by guotie** [comment]
搞一个mybatis的分支

**Comment by EDGDK** [comment]
希望能加入菜单栏tree结构 父节点和子节点的联动，全选/全不选等 
拖拉拽的表单设计

**Comment by xiejing-yinshan** [comment]
表单新增 的下拉菜单支持 查询其他表的数据name与id

**Comment by Menpen** [comment]
建议加入黑名单IP功能

**Comment by 1113452179** [comment]
权限系统的业务BUG在2.5修复
角色分配权限的时候对应的应该是岗位,不应该是部门
部门和岗位的代码关系也要重新捋一遍
(这个是基础架构的上,权限的业务bug)
如果看到这个问题,希望可以重视一下(因为现有的权限业务流程是错误的)

**Comment by kinbod** [comment]
增加graphql应该比较实用

**Comment by 1113452179** [comment]
> 增加graphql应该比较实用

这个可以有:graphql我也在想

**Comment by anfree** [comment]
后台拆分成微服务的项目吧

**Comment by tantaiheng** [comment]
能否增加工作流功能？

**Comment by fongjinming666** [comment]
1、支撑逻辑删除并且同时解决唯一索引的基础功能
2、支撑hikari/druid的多数据源操作操作
3、分支设定jpa/mybatis版本选择
