### ISSUE TITLE
用户界面渲染报错

### ISSUE THREAD

**Issue by scorpio-mo-dao** [elunez/eladmin#232]
`<template slot-scope="scope">
    <div>{{ scope.row.dept.name }} / {{ scope.row.job.name }}</div>
</template>`
![TIM截图20191224085938](https://user-images.githubusercontent.com/55874895/71386880-c479fe80-262b-11ea-9813-1a388d5b71c3.png)
页面初步渲染时获取不到name值，是否要用v-if控制

**Comment by elunez** [comment]
> `<template slot-scope="scope"> <div>{{ scope.row.dept.name }} / {{ scope.row.job.name }}</div> </template>`
> ![TIM截图20191224085938](https://user-images.githubusercontent.com/55874895/71386880-c479fe80-262b-11ea-9813-1a388d5b71c3.png)
> 页面初步渲染时获取不到name值，是否要用v-if控制

看数据是否有返回部门和岗位，系统创建用户时是必须选部门和岗位的，这块你可以根据业务去修改
