### ISSUE TITLE
添加用户不能选择角色

### ISSUE THREAD

**Issue by guiwenhou** [elunez/eladmin#233]
将普通用户角色赋予创建用户的菜单，
将test用户设置成普通用户角色
以test用户登录
创建用户时，角色是灰的。实际创建用户的这个功能不能完成

**Comment by elunez** [comment]
> 将普通用户角色赋予创建用户的菜单，
> 将test用户设置成普通用户角色
> 以test用户登录
> 创建用户时，角色是灰的。实际创建用户的这个功能不能完成

你角色级别低了，不能选高级别的角色，你创建用户时只能选角色级别低于自己的
