### ISSUE TITLE
请教一下，多个字段模糊查询，字段在join的表怎么处理呢？

### ISSUE THREAD

**Issue by robin-gao** [elunez/eladmin#234]
请教一下，多个字段模糊查询，字段在join的表怎么处理呢？
A join B where b.title like ‘%%’ or b.name like '%
%'

**Comment by elunez** [comment]
> 请教一下，多个字段模糊查询，字段在join的表怎么处理呢？
> A join B where b.title like ‘%%’ or b.name like '%
> %'

![image](https://user-images.githubusercontent.com/42142420/71441668-60475f80-273d-11ea-88d7-eb7033c5db22.png)
https://docs.auauz.net/guide/hdsc.html#通用查询
