### ISSUE TITLE
外链的菜单能否在右边打开

### ISSUE THREAD

**Issue by shine4j** [elunez/eladmin#239]
作者您好，我想请教一下，如果是外链的菜单能否直接在右边打开，不能再打开一个新的标签页

**Comment by elunez** [comment]
> 作者您好，我想请教一下，如果是外链的菜单能否直接在右边打开，不能再打开一个新的标签页

请参考接口文档菜单，或者Sql监控菜单

**Comment by LvXinPeng** [comment]
> 作者您好，我想请教一下，如果是外链的菜单能否直接在右边打开，不能再打开一个新的标签页

兄弟实现这个功能了吗？

**Comment by elunez** [comment]
> > 作者您好，我想请教一下，如果是外链的菜单能否直接在右边打开，不能再打开一个新的标签页
> 
> 兄弟实现这个功能了吗？

![image](https://user-images.githubusercontent.com/42142420/73629911-80990100-468f-11ea-9be2-74234bb8ec42.png)
参考这个菜单的写法

**Comment by LvXinPeng** [comment]
> > > 作者您好，我想请教一下，如果是外链的菜单能否直接在右边打开，不能再打开一个新的标签页
> > 
> > 
> > 兄弟实现这个功能了吗？
> 
> ![image](https://user-images.githubusercontent.com/42142420/73629911-80990100-468f-11ea-9be2-74234bb8ec42.png)
> 参考这个菜单的写法

嗯哼，那其实这种做法还是通过route-link转内链实现的吧？
我如果说直接添加一个外链，然后点击就在右侧显示，这个的话，从那一块入手呢？请指教~十分感谢!!

**Comment by elunez** [comment]
components 中有个 Iframe 组件，使用的时候
```
<template>
  <elFrame src="http://www.baidu.com" />
</template>
<script>
import elFrame from '@/components/Iframe/index'
export default {
  components: { elFrame }
}
</script>
```
，然后添加到菜单，
可以参考 
![image](https://user-images.githubusercontent.com/42142420/73635519-a974c280-469e-11ea-87c8-68ce3f20f8b8.png)
![image](https://user-images.githubusercontent.com/42142420/73635558-bbeefc00-469e-11ea-806d-edb79b967fd4.png)

**Comment by LvXinPeng** [comment]
> components 中有个 Iframe 组件，使用的时候
> 
> ```
> <template>
>   <elFrame src="http://www.baidu.com" />
> </template>
> <script>
> import elFrame from '@/components/Iframe/index'
> export default {
>   components: { elFrame }
> }
> </script>
> ```
> 
> ，然后添加到菜单，
> 可以参考
> ![image](https://user-images.githubusercontent.com/42142420/73635519-a974c280-469e-11ea-87c8-68ce3f20f8b8.png)
> ![image](https://user-images.githubusercontent.com/42142420/73635558-bbeefc00-469e-11ea-806d-edb79b967fd4.png)

首先很感谢您能帮助我，非常感谢!
不过，我这边还有一点困惑，我按您的指导操作了，但是在增加菜单的时候，路由地址应该如何填呢？
![1](https://user-images.githubusercontent.com/31260063/73714795-ef885f80-474c-11ea-9daf-a03d2223e99d.png)
，然后我还参考了您给的sql监控的写法，
![4](https://user-images.githubusercontent.com/31260063/73714964-5d348b80-474d-11ea-8e94-1bc9bcad780b.png)
iframe里的src传的值是getter里的吧，所以我在getter里添加了如下，
![2](https://user-images.githubusercontent.com/31260063/73715009-8e14c080-474d-11ea-9cc9-d2f4943e879a.png)
然后在api.js里添了如下，但是还是基于baseurl的，
![3](https://user-images.githubusercontent.com/31260063/73715137-ec41a380-474d-11ea-962a-1b9d685ba100.png)
所以最终还是没法显示外链的内容，不过iframe是有了；

所以我这边是哪一步出错了呢？希望能帮忙看一下，谢谢~

**Comment by elunez** [comment]
路由地址，就是URL的后缀，你填finance就好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "LvXinPeng"<notifications@github.com&gt;; 
发送时间: 2020年2月4日(星期二) 中午12:59
收件人: "elunez/eladmin"<eladmin@noreply.github.com&gt;; 
抄送: "201507802"<201507802@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [elunez/eladmin] 外链的菜单能否在右边打开 (#239)



 
components 中有个 Iframe 组件，使用的时候
 <template&gt;   <elFrame src="http://www.baidu.com" /&gt; </template&gt; <script&gt; import elFrame from '@/components/Iframe/index' export default {   components: { elFrame } } </script&gt;  
，然后添加到菜单，
 可以参考
 
 
  
首先很感谢您能帮助我，非常感谢!
 不过，我这边还有一点困惑，我按您的指导操作了，但是在增加菜单的时候，路由地址应该如何填呢？
 
 ，然后我还参考了您给的sql监控的写法，
 
 iframe里的src传的值是getter里的吧，所以我在getter里添加了如下，
 
 然后在api.js里添了如下，但是还是基于baseurl的，
 
 所以最终还是没法显示外链的内容，不过iframe是有了；
 
所以我这边是哪一步出错了呢？希望能帮忙看一下，谢谢~

**Comment by LvXinPeng** [comment]
> 路由地址，就是URL的后缀，你填finance就好
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "LvXinPeng"<notifications@github.com&gt;; 发送时间: 2020年2月4日(星期二) 中午12:59 收件人: "elunez/eladmin"<eladmin@noreply.github.com&gt;; 抄送: "201507802"<201507802@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 主题: Re: [elunez/eladmin] 外链的菜单能否在右边打开 (#239) components 中有个 Iframe 组件，使用的时候 <template&gt; <elFrame src="http://www.baidu.com" /&gt; </template&gt; <script&gt; import elFrame from '@/components/Iframe/index' export default { components: { elFrame } } </script&gt; ，然后添加到菜单， 可以参考 首先很感谢您能帮助我，非常感谢! 不过，我这边还有一点困惑，我按您的指导操作了，但是在增加菜单的时候，路由地址应该如何填呢？ ，然后我还参考了您给的sql监控的写法， iframe里的src传的值是getter里的吧，所以我在getter里添加了如下， 然后在api.js里添了如下，但是还是基于baseurl的， 所以最终还是没法显示外链的内容，不过iframe是有了； 所以我这边是哪一步出错了呢？希望能帮忙看一下，谢谢~ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

我填了finance试过，不行，是空白页。
