### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by shine4j** [elunez/eladmin#240]
作者，您好按照部署文档部署在nginx时一直报  9864#14340: *2 rewrite or internal redirection cycle while redirect to named location "@router"

**Comment by elunez** [comment]
> 作者，您好按照部署文档部署在nginx时一直报 9864#14340: *2 rewrite or internal redirection cycle while redirect to named location "@router"

测试并无这类问题

**Comment by Jabyn1031** [comment]
你好我也遇到这样的问题，[14/Jan/2021:10:47:03 +0000] "GET /favicon.ico HTTP/1.1" 500 177 "http://192.168.1.23/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0" "-"
2021/01/14 10:49:02 [error] 20#20: *4 rewrite or internal redirection cycle while redirect to named location "@router",

使用docker发布，挂的上面的配置文件，可能是由于nginx版本问题？
