### ISSUE TITLE
菜单栏tree结构使用check-strictly出现问题

### ISSUE THREAD

**Issue by EDGDK** [elunez/eladmin#241]
我的目标：
菜单栏选中父节点可自动选择子节点。
现状：
` <el-tree
            ref="menu"
            :data="menus"
            :default-checked-keys="menuIds"
            :props="defaultProps"
            check-strictly
            accordion
            show-checkbox
            node-key="id"
          />
`
若将 check-strictly设为false，即使子节点未全选，改完菜单栏后，仍未全选；
若将 :default-checked-keys="menuIds"去掉， check-strictly设为false。且用setCheckedKeys赋值，父节点无法选中。
所以请问作者有实现父节点选中，子节点全选，且显示无bug的解决方案吗？

**Comment by elunez** [comment]
> 我的目标：
> 菜单栏选中父节点可自动选择子节点。
> 现状：
> `<el-tree ref="menu" :data="menus" :default-checked-keys="menuIds" :props="defaultProps" check-strictly accordion show-checkbox node-key="id" />`
> 若将 check-strictly设为false，即使子节点未全选，改完菜单栏后，仍未全选；
> 若将 :default-checked-keys="menuIds"去掉， check-strictly设为false。且用setCheckedKeys赋值，父节点无法选中。
> 所以请问作者有实现父节点选中，子节点全选，且显示无bug的解决方案吗？

tree结构目前无法做到这种操作
