### ISSUE TITLE
<keep-alive :include="cachedViews">里的include没起组件缓存作用,都是全部刷新

### ISSUE THREAD

**Issue by CT940828071** [elunez/eladmin#243]
keep-alive失效了，应该是每个vue里的name的命名问题，参考：https://blog.csdn.net/Y_shihao/article/details/101542294

**Comment by MikuBlog** [comment]
我采用了如下方式解决动态路由懒加载命名问题
```js
component: () => {
	const component = import(`@/views${item.component}`)
	component.then(result => {
		const aliasName = item.path.replace(/\//g, "")
		result.default.name = aliasName
	})
	return component
}
```

**Comment by elunez** [comment]
> keep-alive失效了，应该是每个vue里的name的命名问题，参考：https://blog.csdn.net/Y_shihao/article/details/101542294

测试并未失效

**Comment by jeepc** [comment]
每次进页面都会重新调用created方法，重新加载数据

**Comment by jeepc** [comment]
> > keep-alive失效了，应该是每个vue里的name的命名问题，参考：https://blog.csdn.net/Y_shihao/article/details/101542294
> 
> 测试并未失效

官方体验地址也都是切换tab就会重新加载数据
