### ISSUE TITLE
关于maven多模块只设置一个启动类就能访问到其他模块的controller的问题

### ISSUE THREAD

**Issue by GreenHatHG** [elunez/eladmin#246]
<img src="https://i.loli.net/2020/01/07/Kwn5O7Gq41iQXhm.jpg">
在别的模块有controller，但是也没有配置什么，在system那个模块运行后也能访问到logging的controller，最近有个这种分模块的需求，很多个模块都有自己的controller，想运行一个模块就能访问到其他的模块的controller。看开发者的也有这种架构，所以特此问下是怎么实现的，谢谢。

**Comment by elunez** [comment]
https://docs.auauz.net/guide/cjwt.html#新建模块后访问接口-404
