### ISSUE TITLE
手动增加字段值获取不到

### ISSUE THREAD

**Issue by imikay** [elunez/eladmin#247]
手动在domain里增加了字段，也在WinesDTO增加了，调用的返回的值为null，单独访问可以访问到，但是在DTO里转了下值就变空了，请问是什么问题？另外这个组件默认有缓存吗？

**Comment by elunez** [comment]
> 手动在domain里增加了字段，也在WinesDTO增加了，调用的返回的值为null，单独访问可以访问到，但是在DTO里转了下值就变空了，请问是什么问题？另外这个组件默认有缓存吗？

重新生成 mapStruct 实现类，可以看文档中的常见问题

**Comment by imikay** [comment]
好的，了解了。
