### ISSUE TITLE
菜单加载不出来

### ISSUE THREAD

**Issue by SeongBrave** [elunez/eladmin#249]
![image](https://user-images.githubusercontent.com/10784393/72131088-3d13e580-33b6-11ea-91ee-578e32735c29.png)
好像角色加载不出来，
![image](https://user-images.githubusercontent.com/10784393/72131047-21a8da80-33b6-11ea-863c-62f306db587b.png)
麻烦给看下什么原因呢？

**Comment by elunez** [comment]
这怎么看

**Comment by SeongBrave** [comment]
@elunez 不好意思啊，晚上回去给你重截图

**Comment by SeongBrave** [comment]
多谢即使回复吧，之前的版本，应该是2.4之前把，还没有问题，今天更新成最新版本，然后把前端也更新了，现在是运行成功了，但是用admin 用户登录，菜单加载不出来了，我看了下是接口`/api/menus/build`返回的为空，然后debug 发现图下原因，有时间的话麻烦给看下是什么原因呢，多谢了
![image](https://user-images.githubusercontent.com/10784393/72151690-d4dbf880-33e3-11ea-8761-021ced731c73.png)

**Comment by Founder123** [comment]
> 多谢及时回复吧，之前的版本，应该是2.4之前把，还没有问题，今天更新成最新版本，然后把前端也更新了，现在是运行成功了，但是用admin用户登录，菜单加载不出来了，我看了下是接口`/api/menus/build`返回的为空，然后调试发现图下原因，有时间的话麻烦给看下是什么原因呢，多谢了
> ![图片](https://user-images.githubusercontent.com/10784393/72151690-d4dbf880-33e3-11ea-8761-021ced731c73.png)

解决了吗 遇到同样的问题

**Comment by SeongBrave** [comment]
没有呢，等作者给看看

**Comment by SeongBrave** [comment]
@elunez 是导入今天刚更新的sql吗？
