### ISSUE TITLE
返回结果时间全局格式化

### ISSUE THREAD

**Issue by CodeFarmerLi** [elunez/eladmin#25]
我在application.yml中配置了返回结果全局时间格式化但是没有生效。
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

**Comment by elunez** [comment]
不属于本系统问题

**Comment by Chinaxiang** [comment]
我用这个项目配置也没有生效，返回的还是时间戳JSON数据，我自己构建的springboot配置了这个format就ok。

**Comment by Chinaxiang** [comment]
确实是本系统的问题，本系统继承了 `implements WebMvcConfigurer` 导致配置时间格式不生效。新增实现可解决。

参考：
https://blog.csdn.net/Mrs_chens/article/details/103352990
https://blog.csdn.net/u012581020/article/details/105955060

**Comment by yizhitangtongxue** [comment]
我也遇到了这个问题，按楼上老哥留的文档解决了

1. 去掉application中关于jackson的配置
2. 打开eladmin\eladmin-system\src\main\java\me\zhengjie\config\ConfigurerAdapter.java
3. 新增如下代码
```java
    public void extendMessageConverters(List<HttpMessageConverter<?>> converters) {
        MappingJackson2HttpMessageConverter converter = new MappingJackson2HttpMessageConverter();
        ObjectMapper objectMapper = converter.getObjectMapper();
        // 将驼峰转下划线
        // objectMapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
        // objectMapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
        //  时间格式化
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        objectMapper.setTimeZone(TimeZone.getTimeZone("GMT+8"));
        objectMapper.setDateFormat(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"));
        // 设置格式化内容
        converter.setObjectMapper(objectMapper);
        converters.add(0, converter);
    }
```
4. 我这样配置就可以了！
