### ISSUE TITLE
请教，您开发过程中是如何测试的？

### ISSUE THREAD

**Issue by ronallee** [elunez/eladmin#251]
比如后台新增了接口，然后对于老的已有的功能接口，您是如何测试的呢？用啥自动化测试工具每个接口（包括老的）都跑一遍？谢谢

**Comment by elunez** [comment]
> 比如后台新增了接口，然后对于老的已有的功能接口，您是如何测试的呢？用啥自动化测试工具每个接口（包括老的）都跑一遍？谢谢

没用自动测试工具，都是放测试环境让用户体验，然后发现问题
