### ISSUE TITLE
条件查询报错

### ISSUE THREAD

**Issue by bourry** [elunez/eladmin#26]
条件查询报错

Unable to locate Attribute with the the given name [test_name] on this ManagedType [me.zhengjie.modules.test.domain.TestInfo]; nested exception is java.lang.IllegalArgumentException: Unable to locate Attribute with the the given name [test_name] on this ManagedType [me.zhengjie.modules.test.domain.TestInfo]

**Comment by elunez** [comment]
提交 Issues 请提供

1. 提供发生错误的步骤，最好有 GIf 动图
2. 异常日志（尽量详细，异常日志可以使用MD语法）
