### ISSUE TITLE
使用@RequiredArgsConstructor注解减少构造函数注入代码

### ISSUE THREAD

**Issue by zyd** [elunez/eladmin#260]
```java
    private final PasswordEncoder passwordEncoder;
    private final UserService userService;
    private final DataScope dataScope;
    private final DeptService deptService;
    private final RoleService roleService;
    private final VerificationCodeService verificationCodeService;

    public UserController(PasswordEncoder passwordEncoder, UserService userService, DataScope dataScope, DeptService deptService, RoleService roleService, VerificationCodeService verificationCodeService) {
        this.passwordEncoder = passwordEncoder;
        this.userService = userService;
        this.dataScope = dataScope;
        this.deptService = deptService;
        this.roleService = roleService;
        this.verificationCodeService = verificationCodeService;
    }
```

**Comment by elunez** [comment]
> ```java
>     private final PasswordEncoder passwordEncoder;
>     private final UserService userService;
>     private final DataScope dataScope;
>     private final DeptService deptService;
>     private final RoleService roleService;
>     private final VerificationCodeService verificationCodeService;
> 
>     public UserController(PasswordEncoder passwordEncoder, UserService userService, DataScope dataScope, DeptService deptService, RoleService roleService, VerificationCodeService verificationCodeService) {
>         this.passwordEncoder = passwordEncoder;
>         this.userService = userService;
>         this.dataScope = dataScope;
>         this.deptService = deptService;
>         this.roleService = roleService;
>         this.verificationCodeService = verificationCodeService;
>     }
> ```
