### ISSUE TITLE
2.5 版本意见补充

### ISSUE THREAD

**Issue by sunw31** [elunez/eladmin#262]
参考 hs-web 4.0版本
https://github.com/hs-web/hsweb-framework/tree/4.0.x

1. 双因素认证 2FA
2. 文件秒传，利用 firefox的1g文件互传特性。
3. 前端 Electron 版本维护

**Comment by elunez** [comment]
> 参考 hs-web 4.0版本
> https://github.com/hs-web/hsweb-framework/tree/4.0.x
> 
> 1. 双因素认证 2FA
> 2. 文件秒传，利用 firefox的1g文件互传特性。
> 3. 前端 Electron 版本维护

暂不考虑
