### ISSUE TITLE
关于在本地不能用admin登录的问题

### ISSUE THREAD

**Issue by youngerboye** [elunez/eladmin#263]
把代码拉去到本地，运行最新的数据库脚本。用admin账号登录时一直报密码错误。但是test账号不报错，请问是什么原因。

**Comment by randolph2014** [comment]
我也是碰到了这个问题
Encoded password does not look like BCrypt

**Comment by randolph2014** [comment]
> 把代码拉去到本地，运行最新的数据库脚本。用admin账号登录时一直报密码错误。但是test账号不报错，请问是什么原因。

# 用户加密方式变动，改为 BCryptPasswordEncoder方式： SHA-256 +随机盐+密钥对密码进行加密，替换后的明文密码为 123456
update user set `password` = "$2a$10$HhxyGZy.ulf3RvAwaHUGb.k.2i9PBpv4YbLMJWp8pES7pPhTyRCF." WHERE `password` = "e10adc3949ba59abbe56e057f20f883e"

这样就可以解决了，加密方式变动导致的

**Comment by heshengqi1991** [comment]
登录时登不上，然后报错：
com.alibaba.fastjson.JSONObject cannot be cast to me.zhengjie.modules.system.service
com.alibaba.fastjson.JSONObject cannot be cast to me.zhengjie.modules.system.service

这是啥情况
