### ISSUE TITLE
 java.lang.IllegalArgumentException: A granted authority textual representation is required

### ISSUE THREAD

**Issue by randolph2014** [elunez/eladmin#264]
是数据问题导致的吗？

**Comment by elunez** [comment]
> 是数据问题导致的吗？

没遇到过

**Comment by slin1972** [comment]
我遇到了

**Comment by slin1972** [comment]
![image](https://user-images.githubusercontent.com/7867412/73740705-a43d7380-4783-11ea-93f9-073b2fcf928d.png)
![image](https://user-images.githubusercontent.com/7867412/73740772-cafbaa00-4783-11ea-91a5-6daee65917d0.png)
@elunez

**Comment by slin1972** [comment]
是没有权限导致的，如果登录之后没有权限， 就会后面的所有接口全部500

而且遇到一个很离奇的问题

我test改成admin2 就可以了

**Comment by slin1972** [comment]
就仅仅改了username

**Comment by cy9707** [comment]
你好，问题结局了吗
