### ISSUE TITLE
机构8000家之后这系统直接凉了

### ISSUE THREAD

**Issue by LonelyTear** [elunez/eladmin#266]
机构,人员那里全部不是异步加载的, 没法玩.

**Comment by gaojianhua** [comment]
机构指的是那些数据？

**Comment by gaojianhua** [comment]
部门？

**Comment by LonelyTear** [comment]
> 机构指的是那些数据？


下面这张dept表的数据。
```sql
DROP TABLE IF EXISTS `dept`;
CREATE TABLE `dept`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '名称',
  `pid` bigint(20) NOT NULL COMMENT '上级部门',
  `enabled` bit(1) NOT NULL COMMENT '状态',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建日期',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 12 CHARACTER SET = utf8 COLLATE = utf8_general_ci COMMENT = '部门' ROW_FORMAT = Compact;
```

数据请参见附件，内含8000部门
[8000 dept 表 脱敏数据.xlsx](https://github.com/elunez/eladmin/files/4202329/8000.dept.xlsx)

**Comment by LonelyTear** [comment]
我配置是 win10  I5-8300H 16G内存  , 浏览器 从后台拿到数据后的表现是 :
- chrome浏览器有多少内存吃多少内存, 使用率缓慢升至5G, 吃完可用内存为止, 渲染大约4分钟
- firefox浏览器有多少内存吃多少内存, 使用率缓慢升至5G, 吃完可用内存为止, 渲染大约4分钟
- 遨游浏览器直接崩
- IE未偿试

**Comment by tantaiheng** [comment]
请问一下这个问题解决了吗，你那边大概是多少的用户数据和部门数据呢？我这边预计部门也会超过8千 用户数大于10万这样

**Comment by elunez** [comment]
> 请问一下这个问题解决了吗，你那边大概是多少的用户数据和部门数据呢？我这边预计部门也会超过8千 用户数大于10万这样

https://element.eleme.cn/#/zh-CN/component/tree#scoped-slot 

定制优化下

**Comment by elunez** [comment]
> 请问一下这个问题解决了吗，你那边大概是多少的用户数据和部门数据呢？我这边预计部门也会超过8千 用户数大于10万这样

![image](https://user-images.githubusercontent.com/42142420/76915826-8eca7600-68f9-11ea-9c5c-6809bad10e49.png)
