### ISSUE TITLE
机构8000家之后这系统直接扑街了

### ISSUE THREAD

**Issue by LonelyTear** [elunez/eladmin#267]
机构,人员那里全部不是异步加载的, 前端直接js一次性加载 , 没法玩 ,估计4000家应该也差不多凉了.

**Comment by kinbod** [comment]
> 机构,人员那里全部不是异步加载的, 前端直接js一次性加载 , 没法玩 ,估计4000家应该也差不多凉了.

缓存显奇效

**Comment by elunez** [comment]
> 机构,人员那里全部不是异步加载的, 前端直接js一次性加载 , 没法玩 ,估计4000家应该也差不多凉了.

暂时不做懒加载，这些简单功能都是可以自己定制的
