### ISSUE TITLE
用idea中的maven install 时报错 A required class was missing 

### ISSUE THREAD

**Issue by hl211** [elunez/eladmin#269]
Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources (default-resources) on project eladmin-common: Execution default-resources of goal org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources failed: A required class was missing while executing org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources: org/apache/maven/shared/utils/io/FileUtils$FilterWrapper

**Comment by elunez** [comment]
这种问题自己解决
