### ISSUE TITLE
SQL监控组件异常

### ISSUE THREAD

**Issue by ggmo** [elunez/eladmin#271]
你好，搭建过程中SQL监控可以正常显示，隔了几天后SQL监控提示输入账户密码一直认证不通过（密码复制粘贴来的），能帮忙看下吗？

**Comment by elunez** [comment]
![image](https://user-images.githubusercontent.com/42142420/76141504-04377a80-60a0-11ea-9899-8d9a204552a5.png)
sql 监控的账号密码在 prod 中配置
