### ISSUE TITLE
本地登录不上，不是密码的原因

### ISSUE THREAD

**Issue by heshengqi1991** [elunez/eladmin#272]
报错
m.z.e.handler.GlobalExceptionHandler - org.springframework.security.authentication.InternalAuthenticationServiceException: com.alibaba.fastjson.JSONObject cannot be cast to me.zhengjie.modules.system.service.dto.UserDto

**Comment by elunez** [comment]
> 报错
> m.z.e.handler.GlobalExceptionHandler - org.springframework.security.authentication.InternalAuthenticationServiceException: com.alibaba.fastjson.JSONObject cannot be cast to me.zhengjie.modules.system.service.dto.UserDto

清下缓存试试

**Comment by heshengqi1991** [comment]
清了缓存，也还是一样。我发现前端还报跨域的错误：
Proxy error: Could not proxy request auth/code from localhost:8013 to http://localhost:8000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
这个登录的post 报400
Request URL: http://localhost:8013/auth/login
Request Method: POST
Status Code: 400 Bad Request
Remote Address: 127.0.0.1:8013
Referrer Policy: no-referrer-when-downgrade

**Comment by heshengqi1991** [comment]
> > 报错
> > m.z.e.handler.GlobalExceptionHandler - org.springframework.security.authentication.InternalAuthenticationServiceException: com.alibaba.fastjson.JSONObject cannot be cast to me.zhengjie.modules.system.service.dto.UserDto
> 
> 清下缓存试试

清了缓存，也还是一样。我发现前端还报跨域的错误：
Proxy error: Could not proxy request auth/code from localhost:8013 to http://localhost:8000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
这个登录的post 报400
Request URL: http://localhost:8013/auth/login
Request Method: POST
Status Code: 400 Bad Request
Remote Address: 127.0.0.1:8013
Referrer Policy: no-referrer-when-downgrade

**Comment by heshengqi1991** [comment]
> > 报错
> > m.z.e.handler.GlobalExceptionHandler - org.springframework.security.authentication.InternalAuthenticationServiceException: com.alibaba.fastjson.JSONObject cannot be cast to me.zhengjie.modules.system.service.dto.UserDto
> 
> 清下缓存试试

![image](https://user-images.githubusercontent.com/42079691/74835970-6894d300-5359-11ea-8295-68145e7cb3ba.png)
![image](https://user-images.githubusercontent.com/42079691/74836021-7ea29380-5359-11ea-9cdf-a9170d951895.png)
![image](https://user-images.githubusercontent.com/42079691/74836052-924dfa00-5359-11ea-8a89-163376aadfe9.png)

**Comment by nongwenze** [comment]
清理redis
