### ISSUE TITLE
Add Index on dept.pid to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [elunez/eladmin#285]
## Problem
Missing index on table **dept** column **pid** might make the underlying query issued via [DeptServiceImpl#findByPid](https://github.com/elunez/eladmin/blob/286a48368f6a1899d953b57c75b4f2b38d8f93a2/eladmin-system/src/main/java/me/zhengjie/modules/system/service/impl/DeptServiceImpl.java#L59) & [DeptServiceImpl#getDeleteDepts](https://github.com/elunez/eladmin/blob/286a48368f6a1899d953b57c75b4f2b38d8f93a2/eladmin-system/src/main/java/me/zhengjie/modules/system/service/impl/DeptServiceImpl.java#L151) slow.Since table dept is mostly read and sometimes inserted or updated, the performance impact for write operations is acceptable under common cases.
## Possible Solution
Add Index on dept.pid

**Comment by elunez** [comment]
后续修改
