### ISSUE TITLE
关于测试的问题

### ISSUE THREAD

**Issue by zxdispd** [elunez/eladmin#29]
楼主这个单测有点难搞啊，比如说我在其他模块log，tools里面写单测，关系是不是有点乱。我搞了半天没搞出来，在其他模块总会有Could not resolve placeholder 'spring.redis.host' in value "${spring.redis.host}"。

**Comment by elunez** [comment]
因为其他模块依赖了eladmin-common 模块，eladmin-common 模块中有配置redis，所有会出现这个错误

**Comment by elunez** [comment]
可以把system 模块中的配置文件，copy到需要测试的模块，再进行测试
