### ISSUE TITLE
Add Index on dict.name to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [elunez/eladmin#291]
## Problem
Missing index on table **dict** column **name** might make the underlying query via [DictQueryCriteria#blurry](https://github.com/elunez/eladmin/blob/286a48368f6a1899d953b57c75b4f2b38d8f93a2/eladmin-system/src/main/java/me/zhengjie/modules/system/service/dto/DictQueryCriteria.java#L11) slow.Since table dict is mostly read and sometimes inserted or updated, the performance impact for write operations is acceptable under common cases.
## Possible Solution
Add Index on dict.name

**Comment by elunez** [comment]
后续修改
