### ISSUE TITLE
Add Index on role.name to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [elunez/eladmin#293]
## Problem
Missing index on table **role** column **name** might make  the underlying query issued  via `RoleServiceImpl#create` and `RolseServiceImpl#update` slow. Since this query try to find role by its name.

https://github.com/elunez/eladmin/blob/286a48368f6a1899d953b57c75b4f2b38d8f93a2/eladmin-system/src/main/java/me/zhengjie/modules/system/service/impl/RoleServiceImpl.java#L83

https://github.com/elunez/eladmin/blob/286a48368f6a1899d953b57c75b4f2b38d8f93a2/eladmin-system/src/main/java/me/zhengjie/modules/system/service/impl/RoleServiceImpl.java#L96

## Possible Solution
Add Index on role.name

**Comment by elunez** [comment]
后续修改
