### ISSUE TITLE
Add Index on menu.name to Accelerate Query

### ISSUE THREAD

**Issue by wtune** [elunez/eladmin#299]
Missing index on table **menu** column **name** might make the underlying query issued via [MenuServiceImpl#create](https://github.com/elunez/eladmin/blob/286a48368f6a1899d953b57c75b4f2b38d8f93a2/eladmin-system/src/main/java/me/zhengjie/modules/system/service/impl/MenuServiceImpl.java#L77) & [MenuServiceImpl#update](https://github.com/elunez/eladmin/blob/286a48368f6a1899d953b57c75b4f2b38d8f93a2/eladmin-system/src/main/java/me/zhengjie/modules/system/service/impl/MenuServiceImpl.java#L109) slow.Since table menu is mostly read and sometimes inserted or updated, the performance impact for write operations is acceptable under common cases.

**Comment by elunez** [comment]
后续修改
