### ISSUE TITLE
启动报错，

### ISSUE THREAD

**Issue by 819589789** [elunez/eladmin#31]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
elAdmin- 2019-03-20 12:03:25 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field menuMapper in me.zhengjie.modules.system.service.impl.MenuServiceImpl required a bean of type 'me.zhengjie.modules.system.service.mapper.MenuMapper' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'me.zhengjie.modules.system.service.mapper.MenuMapper' in your configuration.

**Comment by elunez** [comment]
docs.auauz.net 看文档

**Comment by elunez** [comment]
![image](https://user-images.githubusercontent.com/42142420/54661210-4163cf00-4b14-11e9-9ff0-eb8b04ab6545.png)
