### ISSUE TITLE
 优化job中的索引

### ISSUE THREAD

**Issue by wtune** [elunez/eladmin#311]
## 问题 
表job中缺少一些需要的索引，通过测试，我们发现加上这些索引可以极大地提高相关查询的性能(高达90%)，需要添加的索引分别如下所示：
### 1.job.sort
[JobController#getJobs](https://github.com/elunez/eladmin/blob/286a48368f6a1899d953b57c75b4f2b38d8f93a2/eladmin-system/src/main/java/me/zhengjie/modules/system/rest/JobController.java#L50)接口查询job时会按sort排序，如下从数据库日志中提取的sql语句：
```
select 
  job0_.id as id1_6_, 
  job0_.create_time as create_t2_6_, 
  job0_.dept_id as dept_id6_6_, 
  job0_.enabled as enabled3_6_, 
  job0_.name as name4_6_, 
  job0_.sort as sort5_6_ 
from 
  job job0_ 
  left outer join dept dept1_ on job0_.dept_id = dept1_.id 
where 
  1 = 1 
order by 
  job0_.sort asc 
limit 
  10
```
在sort字段加索引无疑可以极大地提升相关查询语句的效率。
## 解决方法
在下列字段添加索引
job.sort

**Comment by elunez** [comment]
后续修改
