### ISSUE TITLE
优化role中的索引

### ISSUE THREAD

**Issue by wtune** [elunez/eladmin#313]
## 问题
表role中缺少一些需要的索引，通过测试，我们发现加上这些索引可以极大地提高相关查询的性能(高达90%)，需要添加的索引分别如下所示：
### 1.role.level
[roleController#getAll](https://github.com/elunez/eladmin/blob/286a48368f6a1899d953b57c75b4f2b38d8f93a2/eladmin-system/src/main/java/me/zhengjie/modules/system/rest/RoleController.java#L69)接口查询role时会按level排序，在level字段加索引无疑可以极大地提升相关查询语句的效率。
## 解决方法
在下列字段添加索引
role.level

**Comment by elunez** [comment]
谢谢，后续会修改
