### ISSUE TITLE
修改quartz_log表引擎提高全表行数统计的性能

### ISSUE THREAD

**Issue by wtune** [elunez/eladmin#315]
## 问题
实现[QuartzJobServiceImpl#queryAllLog](https://github.com/elunez/eladmin/blob/286a48368f6a1899d953b57c75b4f2b38d8f93a2/eladmin-system/src/main/java/me/zhengjie/modules/quartz/service/impl/QuartzJobServiceImpl.java#L56)中分页查询quartz_log时数据库会统计全表的行数，产生如下sql：
```
select count(quartzlog0_.id) as col_0_0_ from quartz_log quartzlog0_ where 1=1
```
在InnoDB中不会缓存表的元数据，因此执行这样的语句会造成比较大的时间开销，而MyISAM则缓存有表的元数据，统计行数可以在很短的时间内完成。**如果没有其它必须使用InnoDB的原因**，建议修改表的存储引擎从而优化这类语句。  
参考：https://dev.mysql.com/doc/refman/8.0/en/group-by-functions.html#function_count

## 解决方法
修改quartz_log表的存储引擎为MyISAM

**Comment by elunez** [comment]
谢谢，后续会修改
