### ISSUE TITLE
QueryHelp::getPredicate生成的查询会产生多余的Join

### ISSUE THREAD

**Issue by wtune** [elunez/eladmin#317]
# 描述
`getPredicate`根据某个`XXXQueryCriteria`对象字段上的`@Query`生成查询，其中JOIN是从`joinName`来的。但是，即使那个条件并没有指定，仍然会产生一个没必要的JOIN。

举个例子，查询用户（`UserController::getUser` => `UserService::queryAll`）时，如果只指定了enabled的条件，deptIds没限制时（`UserCriteriaQuery::deptIds`是空的），产生了这样的查询
```sql
select 
  user0_.id as id1_20_, 
  user0_.create_time as create_t2_20_, 
  user0_.dept_id as dept_id9_20_, 
  user0_.email as email3_20_, 
  user0_.enabled as enabled4_20_, 
  user0_.job_id as job_id10_20_, 
  user0_.last_password_reset_time as last_pas5_20_, 
  user0_.password as password6_20_, 
  user0_.phone as phone7_20_, 
  user0_.avatar_id as avatar_11_20_, 
  user0_.username as username8_20_ 
from 
  user user0_ 
  left outer join dept dept1_ on user0_.dept_id = dept1_.id 
where 
  user0_.enabled = 1 
order by 
  user0_.id desc 
limit 
  10
```
可以看到其中的join其实并没有用。如果能去掉的话可以提升一些性能。

# 可能的改法
在QueryHelp.java 54行的if里加一个判断条件，变成`ObjectUtil.isNotEmpty(joinName) && ObjectUtil.isNotEmpty(val)`

**Comment by d15801543974** [comment]
我发现你提交的这些问题，可以直接在2.5版本分支中直接修改并提交。作者看到后审核完直接就合并到主分支了。只是建议哈

**Comment by elunez** [comment]
收到
