### ISSUE TITLE
项目启动不起来啊兄弟

### ISSUE THREAD

**Issue by aleng19890520** [elunez/eladmin#319]
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of constructor in me.zhengjie.modules.system.service.impl.UserServiceImpl required a bean of type 'me.zhengjie.modules.system.service.mapper.UserMapper' that could not be found.

Action:

Consider defining a bean of type 'me.zhengjie.modules.system.service.mapper.UserMapper' in your configuration.

**Comment by elunez** [comment]
> APPLICATION FAILED TO START
> 
> Description:
> 
> Parameter 1 of constructor in me.zhengjie.modules.system.service.impl.UserServiceImpl required a bean of type 'me.zhengjie.modules.system.service.mapper.UserMapper' that could not be found.
> 
> Action:
> 
> Consider defining a bean of type 'me.zhengjie.modules.system.service.mapper.UserMapper' in your configuration.

https://docs.auauz.net/guide/cjwt.html#%E5%90%AF%E5%8A%A8%E6%8A%A5mapper%E6%89%BE%E4%B8%8D%E5%88%B0
