### ISSUE TITLE
求教：websocket实时控制台是如何实现的

### ISSUE THREAD

**Issue by jiangcaijun** [elunez/eladmin#32]
对应接口为：
> wss://api.auauz.net/websocket/551/grmfk1uw/websocket?token=kl

求教，该模块的代码路径是哪里？
我找到了一篇类似的博文：https://blog.csdn.net/u014174854/article/details/82143595
不知道实现思路是否基本一致

**Comment by elunez** [comment]
![image](https://user-images.githubusercontent.com/42142420/54734970-370e0780-4bde-11e9-9c06-f70d2bd06daf.png)
可以参考 https://cloud.tencent.com/developer/article/1096792
