### ISSUE TITLE
group by 怎么动态添加？

### ISSUE THREAD

**Issue by C-Jason-Yang** [elunez/eladmin#320]
@interface Query 没有支持 group by 和 order by

**Comment by elunez** [comment]
> @interface Query 没有支持 group by 和 order by

周末给支持下

**Comment by elunez** [comment]
> @interface Query 没有支持 group by 和 order by
Query 中加入 group by 和 order by 的业务场景是啥，排序可以通过 Sort 类，至于 group by 用处在哪儿
