### ISSUE TITLE
请问下2.5有更新计划吗

### ISSUE THREAD

**Issue by SweetFr** [elunez/eladmin#327]

**Comment by AndroidKid19** [comment]
作者最近好久都没动静了

**Comment by AndroidKid19** [comment]
关注中
请问2.5会集成mybatis吗

**Comment by SweetFr** [comment]
> 关注中
> 请问2.5会集成mybatis吗

mybatis这个作者说了 时间不够 应该是没戏。不知道未来的更新计划

**Comment by d15801543974** [comment]
本身这个项目就是要和mybatis区分开的，我觉得没必要做mybatis版本的。意义不大。mybatis能做到的 jpa也可以做到，并且可以更优雅的方式实现。

**Comment by elunez** [comment]
https://www.ydyno.com/archives/1225.html
