### ISSUE TITLE
gitee发现一个用这个项目改个名字变成他的项目的！

### ISSUE THREAD

**Issue by heshengqi1991** [elunez/eladmin#330]
https://gitee.com/y_project/RuoYi-Vue

**Comment by rubekid** [comment]
你去看看code最早的时间，看谁改谁的

**Comment by SkillfulMariner** [comment]
不用说了，后台都是用的花裤衩的 vue-element-admin。基本上现在 vue 的后台模板都是抄的，直接看后台功能就好

**Comment by elunez** [comment]
> 你去看看code最早的时间，看谁改谁的
嗯哼 https://i.loli.net/2020/04/02/GRL4xh97UYeDACF.png

![image](https://user-images.githubusercontent.com/42142420/80854295-8475f880-8c69-11ea-8372-58a1d4258145.png)

若依的前后端分离项目发布的时间比我这个晚，里面有些代码是直接拿的我项目里面的。
比如动态路由，菜单图标选择，登陆页面等。

由于用的同一个ui模版，加上若依名气较大，就容易导致被误会
