### ISSUE TITLE
Entity.ftl模板文件中关于时间注解问题

### ISSUE THREAD

**Issue by sunsupeng** [elunez/eladmin#334]
如果前端配置页面不选择时间注解的情况下，也会默认加上@UpdateTimestamp  
在51行代码处，发现if判断没有过滤完全
 <#if column.dateAnnotation??>
    <#if column.dateAnnotation = 'CreationTimestamp'>
    @CreationTimestamp
    <#else>
    @UpdateTimestamp
    </#if>
    </#if>

**Comment by elunez** [comment]
> 如果前端配置页面不选择时间注解的情况下，也会默认加上@UpdateTimestamp
> 在51行代码处，发现if判断没有过滤完全
> <#if column.dateAnnotation??>
> <#if column.dateAnnotation = 'CreationTimestamp'>
> @CreationTimestamp
> <#else>
> @UpdateTimestamp
> </#if>
> </#if>

(column.dateAnnotation)??
