### ISSUE TITLE
连接池泄露

### ISSUE THREAD

**Issue by EmKs** [elunez/eladmin#339]
当高并发的时候，连接池达到max-active设置的数量，程序就会卡死，无法访问，连接也无法回收，只能通过重启程序才能解决，作者方便排查一下吗？或者项目哪里有连接数据库的操作，我这边查看一下
![image](https://user-images.githubusercontent.com/21976086/80197780-b546a400-8651-11ea-83a2-5f2a5c9ce59b.png)

**Comment by zoulejiu** [comment]
麻烦提供下你这边并发多大，现在设置了什么，因为默认得休闲等级时间是18000，你可以把这个设置小点，让它们快点回收
![image](https://user-images.githubusercontent.com/31949635/80685671-2545a600-8afa-11ea-888f-795072c9f736.png)

**Comment by EmKs** [comment]
并发最高2000，时长设置了虽然会减少一些，但是作用不明显，这边写了一个api接口，基本上连接都是来源于这个接口的，这个接口是一个get请求，请求完成后就没有后续动作，以至于有些时候并发比较高的时候会来不及回收，想问下有没有快速回收的配置？ @zoulejiu

**Comment by EmKs** [comment]
# 初始化配置
      initial-size: 3
      # 最小连接数
      min-idle: 3
      # 最大连接数
      max-active: 2000
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 30000
      # 最大空闲时间
      min-evictable-idle-time-millis: 1800000

**Comment by EmKs** [comment]
目前的情况就是app访问api接口结束后，数据库的连接并没有被释放，会处于sleep状态，然后当连接达到max-active以后，后台就会无法访问

**Comment by gaojianhua** [comment]
升级一下Druid 的版本试试呢。
