### ISSUE TITLE
基于EL-ADMIN扩展的项目(mybatis、could 等)

### ISSUE THREAD

**Issue by elunez** [elunez/eladmin#346]
基于EL-ADMIN扩展的项目并且是开源的可以在这里记录【如mybatis 版本、could 版本等等】

后续将这些项目添加到文档页面

**Comment by elunez** [comment]
基于EL-ADMIN的EF-ADMIN支持多租户、国际化等功能

项目地址：https://docs.efactory.vip/guide/

**Comment by guchengwuyue** [comment]
yshop电商系统，https://gitee.com/guchengwuyue/yshopmall (mybatisPlus版本）

**Comment by sunw31** [comment]
> yshop电商系统，https://gitee.com/guchengwuyue/yshopmall (mybatisPlus版本）

pom.xml没发现有myatisplus啊，最关键代码生成器也没改吧

**Comment by guchengwuyue** [comment]
> > yshop电商系统，https://gitee.com/guchengwuyue/yshopmall (mybatisPlus版本）
> 
> pom.xml没发现有myatisplus啊，最关键代码生成器也没改吧, 从新更新了，上次同步有点问题，mproo就是mybaits模块 其他模块依赖于它

**Comment by adyfang** [comment]
> 基于EL-ADMIN扩展的项目并且是开源的可以在这里记录【如mybatis 版本、could 版本等等】
> 
> 后续将这些项目添加到文档页面

mybatis plus版本: https://gitee.com/adyfang/eladmin

**Comment by elunez** [comment]
mybatis plus 版本：https://github.com/JinlongLiao/eladmin

才用适配器 方式 兼容 MybatisPlus
基于原有的 JPA 查询、注解 兼容数据持久层兼容适配Mybatisplus
