### ISSUE TITLE
运维管理两个错误，一个是不同服务器部署，获取服务器信息错误。二、部署到linux中后，上传的war包名称前会自动多一个tmp导致部署失败，

### ISSUE THREAD

**Issue by gcs1230** [elunez/eladmin#347]
问题一
ScpClientUtil

	static synchronized public ScpClientUtil getInstance(String ip, int port, String username, String passward) {
//		if (instance == null) {
			return new ScpClientUtil(ip, port, username, passward);
//		}
//		return instance;
	}

![image](https://user-images.githubusercontent.com/50815165/81296118-03bd5f00-90a4-11ea-8a39-3fbb7be0ea7a.png)

**Comment by gcs1230** [comment]
![image](https://user-images.githubusercontent.com/50815165/81359099-c3dd9280-910a-11ea-9c23-446a3da32125.png)
这地方少了个File.separator，问下如果这个问题确认的话，是不是所有路径拼接的都要加一下呢？

**Comment by wangxm345566462** [comment]
同样的问题。感觉 tmp 本身不需要加
而不是少加了分割符

**Comment by gcs1230** [comment]
不加应该是能用，但没有指定临时文件存放目录不方便管理

**Comment by wangxm345566462** [comment]
> 不加应该是能用，但没有指定临时文件存放目录不方便管理

![image](https://user-images.githubusercontent.com/17328090/81383298-68c79200-9142-11ea-9dac-129ab37b8f83.png)
看默认的shell 里就没有tmp 目录。 感觉设计上就没打算加 tmp 。

**Comment by zhy6599** [comment]
问题解决了，请拉取最新的代码。有问题请反馈

**Comment by wangxm345566462** [comment]
https://github.com/elunez/eladmin/commit/fe77f081c580912c28bc146a3a941d2bd37c414d
