### ISSUE TITLE
关于StringUtils.getCityInfo出现invoke错误的问题

### ISSUE THREAD

**Issue by yangming9** [elunez/eladmin#349]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

出现的位置是在StringUtils.getCityInfo 的dataBlock = (DataBlock) method.invoke(searcher, ip);  这个地方，上次大神提交的commit是a9e12b 修复了不能关闭的问题后，开始出现这个错误，麻烦看一下这个是什么问题，自己尝试解决失败

**Comment by elunez** [comment]
> java.lang.reflect.InvocationTargetException
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> 
> 出现的位置是在StringUtils.getCityInfo 的dataBlock = (DataBlock) method.invoke(searcher, ip); 这个地方，上次大神提交的commit是a9e12b 修复了不能关闭的问题后，开始出现这个错误，麻烦看一下这个是什么问题，自己尝试解决失败

ip归属地查询已经修改了方式

https://github.com/elunez/eladmin/commit/3095f3730e76e52b371e235202cf322e792802bd
