### ISSUE TITLE
为什么没有字典管理呢？是有特殊考虑吗？

### ISSUE THREAD

**Issue by mylater** [elunez/eladmin#35]

**Comment by elunez** [comment]
啥码表

**Comment by elunez** [comment]
sql文件在system模块下
![image](https://user-images.githubusercontent.com/42142420/55786671-4d292c80-5ae7-11e9-8370-8dc6275ea3a0.png)

**Comment by mylater** [comment]
不好意思，是字典管理。

**Comment by elunez** [comment]
已经加入版本更新计划了，1.7版本就会有了，估计周末发布

**Comment by mylater** [comment]
好的，感谢 elunez
