### ISSUE TITLE
项目依赖升级计划

### ISSUE THREAD

**Issue by shaokuuipo** [elunez/eladmin#350]
请问，项目里面的依赖不打算升级一下吗？我看很多依赖版本都太老了。

**Comment by elunez** [comment]
> 请问，项目里面的依赖不打算升级一下吗？我看很多依赖版本都太老了。

具体哪些

**Comment by shaokuuipo** [comment]
> > 请问，项目里面的依赖不打算升级一下吗？我看很多依赖版本都太老了。
> 
> 具体哪些

比如jedis ，最新版是3.2.0
druid：1.1.22
commons-pool2：2.8.0
mapstruct：1.3.1.Final
io.swagger：2.1.2
poi：4.1.2
等等。。
