### ISSUE TITLE
菜单数据懒加载以后角色授权后导致未加载的菜单权限无法保存登录后出错的问题

### ISSUE THREAD

**Issue by cai-peiyuan** [elunez/eladmin#352]
菜单数据懒加载以后角色授权后导致未加载的菜单权限无法保存登录后出错的问题

**Comment by elunez** [comment]
> 菜单数据懒加载以后角色授权后导致未加载的菜单权限无法保存登录后出错的问题
![image](https://user-images.githubusercontent.com/42142420/81665743-a8101e80-9473-11ea-9810-696b7156a174.png)

前后端都需要更新
