### ISSUE TITLE
2.5版本 代码生成分页报错

### ISSUE THREAD

**Issue by janyyy** [elunez/eladmin#353]
问题截图：
![image](https://user-images.githubusercontent.com/27274865/81723552-96e80180-94b5-11ea-866a-52cf089200e7.png)
![image](https://user-images.githubusercontent.com/27274865/81723574-9fd8d300-94b5-11ea-819c-d1801c453a98.png)
问题定位：
![image](https://user-images.githubusercontent.com/27274865/81723661-c72fa000-94b5-11ea-91fd-4e2e2e3a8168.png)
异常代码：
int[] startEnd = PageUtil.transToStartEnd(page, size);
说明：
将page +1 改为page后 页面分页显示正常、数据也正常，但是前端传到后台的分页值有问题 比如说第一页传到后台page是0，点第一页，page传到后台是2。以此类推

**Comment by elunez** [comment]
能提供下操作视频吗，我这边复现不出来

**Comment by janyyy** [comment]
操作视频已经发送到：201507802<201507802@qq.com>

**Comment by 1406704102** [comment]
page+1 查不到 第一页的数据 因为hutool的代码修改过了:
--------------------------------------------------------------------------------------------------------------
hutool-all-5.3.4.jar( eladmin2.5 ) 

    private static int firstPageNo = 0;

    public static int getStart(int pageNo, int pageSize) {
        if (pageNo < firstPageNo) {
            pageNo = firstPageNo;
        }

        if (pageSize < 1) {
            pageSize = 0;
        }

        return (pageNo - firstPageNo) * pageSize;
    }
--------------------------------------------------------------------------------------------------------------
hutool-all-5.0.6.jar( eladmin2.4) 

    public static int getStart(int pageNo, int pageSize) {
        if (pageNo < 1) {
            pageNo = 1;
        }

        if (pageSize < 1) {
            pageSize = 0;
        }

        return (pageNo - 1) * pageSize;
    }

**Comment by janyyy** [comment]
nice
