### ISSUE TITLE
交流学习

### ISSUE THREAD

**Issue by timely-rain** [elunez/eladmin#356]
Mr.Zheng您好，我是[MornBoot](https://github.com/morn-team/morn-boot-projects) 的作者Timely，目前正在学习使用EL-ADMIN。现阶段查阅了部分指南，运行了Demo环境，并阅读了一些EL-ADMIN的源码。

我觉得EL-ADMIN是一个非常适合项目初期使用的框架，并且我也计划在公司内推广使用，但目前为止，我也发现了EL-ADMIN一些相对不太友好的组件，想对它进行一定程度修改。例如EL-ADMIN的操作日志、响应消息，EF-ADMIN的异常国际化等，这些API是开发可用的，但在实际业务开发中还是不够完善灵活，或者说没有达到好用的程度。

MornBoot恰好是专注于提供这些API的框架，例如上面提到的[操作日志-OperationLog](https://github.com/morn-team/morn-boot-projects/wiki/OperationLog-%E6%93%8D%E4%BD%9C%E6%97%A5%E5%BF%97) 、[响应消息-RestMessage](https://github.com/morn-team/morn-boot-projects/wiki/RestMessage-REST%E6%B6%88%E6%81%AF) 、[异常国际化-ApplicationMessage](https://github.com/morn-team/morn-boot-projects/wiki/ApplicationMessage-%E5%BA%94%E7%94%A8%E6%B6%88%E6%81%AF) ，当然还有一些其它特性。按原计划，我准备用EL-ADMIN集成MornBoot之后，再在公司内部推广使用，不过一方面EL-ADMIN和我的开源项目开发方向高度一致，而且我也希望EL-ADMIN更加完善，从而帮助到更多人。因此希望将MornBoot一些好的特性集成进EL-ADMIN。

如果对我的提议有兴趣的话，能否通过邮箱联系我，非常感谢！

Email：lolic_sd@hotmail.com

**Comment by elunez** [comment]
> Mr.Zheng您好，我是[MornBoot](https://github.com/morn-team/morn-boot-projects) 的作者Timely，目前正在学习使用EL-ADMIN。现阶段查阅了部分指南，运行了Demo环境，并阅读了一些EL-ADMIN的源码。
> 
> 我觉得EL-ADMIN是一个非常适合项目初期使用的框架，并且我也计划在公司内推广使用，但目前为止，我也发现了EL-ADMIN一些相对不太友好的组件，想对它进行一定程度修改。例如EL-ADMIN的操作日志、响应消息，EF-ADMIN的异常国际化等，这些API是开发可用的，但在实际业务开发中还是不够完善灵活，或者说没有达到好用的程度。
> 
> MornBoot恰好是专注于提供这些API的框架，例如上面提到的[操作日志-OperationLog](https://github.com/morn-team/morn-boot-projects/wiki/OperationLog-%E6%93%8D%E4%BD%9C%E6%97%A5%E5%BF%97) 、[响应消息-RestMessage](https://github.com/morn-team/morn-boot-projects/wiki/RestMessage-REST%E6%B6%88%E6%81%AF) 、[异常国际化-ApplicationMessage](https://github.com/morn-team/morn-boot-projects/wiki/ApplicationMessage-%E5%BA%94%E7%94%A8%E6%B6%88%E6%81%AF) ，当然还有一些其它特性。按原计划，我准备用EL-ADMIN集成MornBoot之后，再在公司内部推广使用，不过一方面EL-ADMIN和我的开源项目开发方向高度一致，而且我也希望EL-ADMIN更加完善，从而帮助到更多人。因此希望将MornBoot一些好的特性集成进EL-ADMIN。
> 
> 如果对我的提议有兴趣的话，能否通过邮箱联系我，非常感谢！
> 
> Email：[lolic_sd@hotmail.com](mailto:lolic_sd@hotmail.com)

等空闲下来去了解下MornBoot
