### ISSUE TITLE
登陆成功后，请求接口问题

### ISSUE THREAD

**Issue by gengwhs** [elunez/eladmin#36]
楼主，您好。我在登陆成功之后，去请求任何一个接口，都会被拦截，返回 401错误，
"status": 401,
"error": "Unauthorized",
"message": "Full authentication is required to access this resource",
"path": "/api/roles"，请问是我请求的有问题吗？每次请求，我都在 token的位置，填写登陆后返回的token，若楼主看到，麻烦回复下，我加您qq群，提示禁止加入了，有劳了。 595985964

**Comment by wbq-bios** [comment]
如果是用postman之类的要把head头也要完全复制全，我的是这样，不知道能不能对你有帮助。
![image](https://user-images.githubusercontent.com/12454499/55923296-73f67880-5c37-11e9-8105-659552b7a979.png)

**Comment by elunez** [comment]
检查请求头部
![image](https://user-images.githubusercontent.com/42142420/55926185-f173b600-5c42-11e9-8b8c-fe4a0cb9283d.png)
