### ISSUE TITLE
新增菜单，点击菜单分配，再重新登录，发现系统内置的菜单点开白屏

### ISSUE THREAD

**Issue by zoulejiu** [elunez/eladmin#360]
![image](https://user-images.githubusercontent.com/31949635/82289184-cf686d80-99d6-11ea-8e80-c277704a36f7.png)

**Comment by zoulejiu** [comment]
点击保存的时候，请求的json 菜单ID 有丢失的情况
![image](https://user-images.githubusercontent.com/31949635/82291195-253f1480-99db-11ea-82a9-fee84a1df971.png)

**Comment by elunez** [comment]
测试并无问题

录屏链接：https://files.ydyno.com/QQ20200520-191130-HD.mp4
