### ISSUE TITLE
赖加载引起来的问题

### ISSUE THREAD

**Issue by zoulejiu** [elunez/eladmin#362]
![image](https://user-images.githubusercontent.com/31949635/82305333-13b43780-99f0-11ea-8a57-228d329289df.png)
![image](https://user-images.githubusercontent.com/31949635/82305360-1b73dc00-99f0-11ea-8f21-c13fa25188c3.png)
查询用户信息，User 对象里面 使用了ManyToMany FetchType 默认为LAZY
导致用户角色信息和岗位信息还未查询出，就session 关闭引起异常

**Comment by elunez** [comment]
> ![image](https://user-images.githubusercontent.com/31949635/82305333-13b43780-99f0-11ea-8a57-228d329289df.png)
> ![image](https://user-images.githubusercontent.com/31949635/82305360-1b73dc00-99f0-11ea-8f21-c13fa25188c3.png)
> 查询用户信息，User 对象里面 使用了ManyToMany FetchType 默认为LAZY
> 导致用户角色信息和岗位信息还未查询出，就session 关闭引起异常

什么版本，什么情景下发生的

**Comment by zoulejiu** [comment]
2.5bean 版本，在定时任务调度里面，调用userService 的时候，会出现这个问题

**Comment by elunez** [comment]
> 2.5bean 版本，在定时任务调度里面，调用userService 的时候，会出现这个问题

调用哪个方法

**Comment by zoulejiu** [comment]
//查询用户信息，看是否有配置邮箱地址
            UserDto userDto=userService.findById(userId);
我目前本地修复是在User 上面标注，不lazy
![image](https://user-images.githubusercontent.com/31949635/82515601-2ee78a00-9b4b-11ea-9514-2510c7e5a562.png)
你那边看看有没有更好的办法

**Comment by elunez** [comment]
@Transactional  

加在findById方法上即可
