### ISSUE TITLE
字典管理模块新增bug

### ISSUE THREAD

**Issue by HuanBaby1314** [elunez/eladmin#366]
**前端bug**
复现流程： 字典管理-选择一个已有的条目，点击铅笔图标，编辑-点击取消-点击新增
我的想法：debug看到form对象的数据和正常新增数据不一致，提交会报错。暂时不是很了解代码，希望大佬修复一下。

**Comment by elunez** [comment]
> **前端bug**
> 复现流程： 字典管理-选择一个已有的条目，点击铅笔图标，编辑-点击取消-点击新增
> 我的想法：debug看到form对象的数据和正常新增数据不一致，提交会报错。暂时不是很了解代码，希望大佬修复一下。

```
const defaultForm = { id: null, name: null, description: null, dictDetails: [] }
```
![image](https://user-images.githubusercontent.com/42142420/82723450-9c3d1b80-9d01-11ea-9283-74abc2bae75a.png)
