### ISSUE TITLE
如何修改日志打印級別

### ISSUE THREAD

**Issue by KuoCHsiang** [elunez/eladmin#367]
logging:
  level:
    root: info
    com.xxx: warn

在配置文件中，如上配置，但是com.xxx的info级别的日志还是一样输出

**Comment by elunez** [comment]
![image](https://user-images.githubusercontent.com/42142420/82743810-df030000-9da2-11ea-96f2-022bc517f770.png)

**Comment by KuoCHsiang** [comment]
你好，请问如何解决

**Comment by elunez** [comment]
> 你好，请问如何解决

对应文件对应位置修改
