### ISSUE TITLE
角色管理失效

### ISSUE THREAD

**Issue by yinlingshishangS** [elunez/eladmin#368]
每次给其他角色分配权限后，admin的很多权限就会丢失，不知道是什么原因造成的

**Comment by yinlingshishangS** [comment]
超级管理员的菜单分配经常会少一些，莫名其妙的丢失，不知道什么原因造成的？

**Comment by elunez** [comment]
> 超级管理员的菜单分配经常会少一些，莫名其妙的丢失，不知道什么原因造成的

这个Bug修复了的，是因为角色分配菜单时，没有将子节点的菜单ID传入，所以出现了菜单丢失。。。

可以看看最近的提交记录

**Comment by yinlingshishangS** [comment]
好的，很感谢大佬，还有，实在加不进去咱们的群，是ios的原因么

**Comment by elunez** [comment]
> 好的，很感谢大佬，还有，实在加不进去咱们的群，是ios的原因么

ios 会出现这样的问题，可以用电脑试试

**Comment by yinlingshishangS** [comment]
电脑是mac的，等会出去找一台安卓手机吧，好坑。或者您拉我一下？2736876044

**Comment by li1533** [comment]
什么群？&nbsp; 群号是多少了？



---原始邮件---
发件人: "引领时尚S"<notifications@github.com&gt;
发送时间: 2020年5月24日(星期日) 上午9:43
收件人: "elunez/eladmin"<eladmin@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [elunez/eladmin] 角色管理失效 (#368)




 
好的，很感谢大佬，还有，实在加不进去咱们的群，是ios的原因么

**Comment by elunez** [comment]
> 什么群？&nbsp; 群号是多少了？
> […](#)
> ---原始邮件--- 发件人: "引领时尚S"<notifications@github.com&gt; 发送时间: 2020年5月24日(星期日) 上午9:43 收件人: "elunez/eladmin"<eladmin@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [elunez/eladmin] 角色管理失效 (#368) 好的，很感谢大佬，还有，实在加不进去咱们的群，是ios的原因么 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

891137268
