### ISSUE TITLE
前端添加按钮

### ISSUE THREAD

**Issue by yinlingshishangS** [elunez/eladmin#369]
大佬，如果在前端操作上
![image](https://user-images.githubusercontent.com/35954690/82736197-506a9080-9d5a-11ea-9c88-52b842728397.png)
如果想再添加一个按钮，该如何添加
我查询出来的时间是时间戳，如何在时间按钮上正常显示

万分感谢大佬

**Comment by elunez** [comment]
时间戳可以用
 import {
  parseTime
} from '@/utils/index'
进行转换， 加按钮可以在 UD.operation.vue 中添加，也可以直接在表格中添加

**Comment by yinlingshishangS** [comment]
好的，很谢谢大佬
