### ISSUE TITLE
在其他平台登录过一个admin后，在我们平台登录的时候出现此问题

### ISSUE THREAD

**Issue by yinlingshishangS** [elunez/eladmin#370]
Caused by: javax.crypto.BadPaddingException: Decryption error
 cn.hutool.crypto.CryptoException: BadPaddingException: Decryption error

**Comment by elunez** [comment]
> Caused by: javax.crypto.BadPaddingException: Decryption error
> cn.hutool.crypto.CryptoException: BadPaddingException: Decryption error

其他平台？ 现在解密加密没用 hutool 工具了，这个在创建 Rsa 对象的时候特别慢

**Comment by yinlingshishangS** [comment]
下载mall的代码，在本地跑完，admin登录后，再切换我们的本地跑，就会出现这种情况

**Comment by elunez** [comment]
> mall

mall？

**Comment by yinlingshishangS** [comment]
没事，大佬，我先尝试解决吧。就是github上的另一套代码。太感谢您了

**Comment by elunez** [comment]
> 没事，大佬，我先尝试解决吧。就是github上的另一套代码。太感谢您了

可以把解密部分替换掉，以前的解密的确慢

**Comment by yinlingshishangS** [comment]
好的呢，很感谢大佬
