### ISSUE TITLE
怎么会有这么多ip2region.db文件，哪里打开这个文件了，最后没有关闭导致打开文件过多的错误，怎么解决？

### ISSUE THREAD

**Issue by loveyuncheng** [elunez/eladmin#373]
部署后怎么会有这么多ip2region.db文件，哪里打开这个文件了，最后没有关闭导致打开文件过多的错误，怎么解决？
![image](https://user-images.githubusercontent.com/38218695/83008861-6e7d0d00-a048-11ea-9965-3e7806c02844.png)

**Comment by elunez** [comment]
> 部署后怎么会有这么多ip2region.db文件，哪里打开这个文件了，最后没有关闭导致打开文件过多的错误，怎么解决？
> ![image](https://user-images.githubusercontent.com/38218695/83008861-6e7d0d00-a048-11ea-9965-3e7806c02844.png)

issues 中搜索 ip2region， 应该有答案
https://github.com/elunez/eladmin/issues?q=ip2region

**Comment by elunez** [comment]
> 部署后怎么会有这么多ip2region.db文件，哪里打开这个文件了，最后没有关闭导致打开文件过多的错误，怎么解决？
> ![image](https://user-images.githubusercontent.com/38218695/83008861-6e7d0d00-a048-11ea-9965-3e7806c02844.png)

这个版本已经去掉 ip2region 获取 IP了，可以修改下代码

**Comment by loveyuncheng** [comment]
服务器是内网环境无法连接外网，所以StringUtils.getCityInfo()还不能走外网接口获取详细地址，怎么及时把流关掉呢？
