### ISSUE TITLE
jpa多表查询

### ISSUE THREAD

**Issue by yinlingshishangS** [elunez/eladmin#374]
您好，关于jpa多表查询，
我的表之间没有做外键，使用注解one to one发现：sql查询时候，已经查询了那张表，但是无法映射到我们的dto里面，您清楚原因么？或者说，如果在jpa中如果要使用one to one等注解的话，需要的操作是？

**Comment by elunez** [comment]
Dto 与 Entity 的字段需要对应上

如果对应上了还是没有数据，可以查看 https://el-admin.vip/guide/cjwt.html#%E5%85%B3%E4%BA%8E%E6%96%B0%E5%A2%9E%E5%AD%97%E6%AE%B5%E5%90%8E%E5%87%BA%E7%8E%B0%E7%9A%84%E9%97%AE%E9%A2%98
