### ISSUE TITLE
新版本，菜单管理，修改报错

### ISSUE THREAD

**Issue by jameswuwu** [elunez/eladmin#375]
![image](https://user-images.githubusercontent.com/52489194/83123521-9a12fc80-a107-11ea-905b-a2ace17dc127.png)

报错信息

JSON parse error: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_NUMBER_INT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_NUMBER_INT token at [Source: (PushbackInputStream); line: 1, column: 1]

**Comment by elunez** [comment]
> ![image](https://user-images.githubusercontent.com/52489194/83123521-9a12fc80-a107-11ea-905b-a2ace17dc127.png)
> 
> 报错信息
> 
> JSON parse error: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_NUMBER_INT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of VALUE_NUMBER_INT token at [Source: (PushbackInputStream); line: 1, column: 1]

看提交记录，已经修复了

https://github.com/elunez/eladmin-web/commit/6103bbc6a7456ce461db1135fbe5bfe673caed90
