### ISSUE TITLE
带Token访问anonymous的地址报错403

### ISSUE THREAD

**Issue by kerwinguo** [elunez/eladmin#376]
问题描述:
1.环境:使用的是2.0的版本(较早期版本)
2.场景需要,部分url登录跟未登录的用户都可以访问
3.在SecurityConfig配置了antMatchers("/goods/goodsInit").anonymous(),表示可以不用token也可以访问

状况:如果不带token访问是可以的,带着正确的token访问,会返回403
期望:带着或者不带token都能正确的访问

想请问下,是哪里有全局处理这种配置了anonymous就必须不能带token访问吗?

**Comment by elunez** [comment]
> 问题描述:
> 1.环境:使用的是2.0的版本(较早期版本)
> 2.场景需要,部分url登录跟未登录的用户都可以访问
> 3.在SecurityConfig配置了antMatchers("/goods/goodsInit").anonymous(),表示可以不用token也可以访问
> 
> 状况:如果不带token访问是可以的,带着正确的token访问,会返回403
> 期望:带着或者不带token都能正确的访问
> 
> 想请问下,是哪里有全局处理这种配置了anonymous就必须不能带token访问吗?

![image](https://user-images.githubusercontent.com/42142420/83141554-79a46b80-a122-11ea-91b9-cbd525f02969.png)
