### ISSUE TITLE
前端权限问题

### ISSUE THREAD

**Issue by yinlingshishangS** [elunez/eladmin#377]
![image](https://user-images.githubusercontent.com/35954690/83141194-d2bfcf80-a121-11ea-94b7-bd3733c91c09.png)

大佬，前端权限是如何控制的，我在一个页面多导入了一个前端页面，竟然导入不进来

**Comment by elunez** [comment]
> ![image](https://user-images.githubusercontent.com/35954690/83141194-d2bfcf80-a121-11ea-94b7-bd3733c91c09.png)
> 
> 大佬，前端权限是如何控制的，我在一个页面多导入了一个前端页面，竟然导入不进来

没懂意思

**Comment by elunez** [comment]
权限控制：https://docs.auauz.net/guide/qdsc.html#%E6%9D%83%E9%99%90%E6%8E%A7%E5%88%B6
