### ISSUE TITLE
执行 /proc/pid/fd/命令，查看打开的文件信息

### ISSUE THREAD

**Issue by loveyuncheng** [elunez/eladmin#378]
执行 /proc/pid/fd/命令，查看打开的文件信息，程序里面哪里有使用吗？怎么会有这么多文件。求优化方法
![image](https://user-images.githubusercontent.com/38218695/83346163-a5a33500-a34c-11ea-969d-2ed9b4cf1425.png)

**Comment by elunez** [comment]
不明觉厉
