### ISSUE TITLE
前端打包部署到二级目录，一直 404

### ISSUE THREAD

**Issue by gee1k** [elunez/eladmin#381]
部署到域名一级目录没问题，部署到二级目录不行。

vue.config.js 里 publicPath 已经配置。

![image](https://user-images.githubusercontent.com/12059800/83502172-d07bbd80-a4f3-11ea-84b4-9ae4553044fc.png)

**Comment by elunez** [comment]
> 部署到域名一级目录没问题，部署到二级目录不行。
> 
> vue.config.js 里 publicPath 已经配置。
> 
> ![image](https://user-images.githubusercontent.com/12059800/83502172-d07bbd80-a4f3-11ea-84b4-9ae4553044fc.png)

  publicPath: process.env.NODE_ENV === 'development' ? '/' : './',

![image](https://user-images.githubusercontent.com/42142420/83743559-757dce00-a68d-11ea-9782-63a2f72f5cbf.png)


nginx
```
server {
	   listen       80;
	   server_name  zj2020.pw;

	   location /dist {
	      root   /home/wwwroot/eladmin/test;
	      index  index.html;
	   }
}
```
文件目录
![image](https://user-images.githubusercontent.com/42142420/83743489-60a13a80-a68d-11ea-8f89-b8e494f32ce5.png)

注意目录名称要与配置名称一致

![image](https://user-images.githubusercontent.com/42142420/83743607-87f80780-a68d-11ea-9a22-3366fc0a1709.png)
