### ISSUE TITLE
前端查询器params传参怎么使用

### ISSUE THREAD

**Issue by jinmuzhihuakai** [elunez/eladmin#384]
在其他组件引用crudjs后，查询参数params怎么传，使页面表格数据请求成功

**Comment by lpl606606** [comment]
同问，比如我的请求是http://localhost:8080/user?id=111,进入新页面的时候就要在后台传入这个id，在crud这个组件想通过this.$route.query获取id传入CRUD()这个方法中，但该不识别this，请问作者有没有推荐的解决方法

**Comment by elunez** [comment]
> 在其他组件引用crudjs后，查询参数params怎么传，使页面表格数据请求成功

![image](https://user-images.githubusercontent.com/42142420/83735087-78bf8c80-a682-11ea-8b3b-abb36d4e3daa.png)

![image](https://user-images.githubusercontent.com/42142420/83735133-85dc7b80-a682-11ea-80bb-cfc1809d6f19.png)

**Comment by yuyifade** [comment]
请问你解决这个问题了吗？

**Comment by jinmuzhihuakai** [comment]
解决了

**Comment by yuyifade** [comment]
> 解决了
这段代码能添加筛选条件吗，比如我从其他页面跳转过来传了一个id，如何把id这个筛选条件加进去  
cruds() {
    return CRUD({ title: '采集器', url: 'api/pmNodeInfo', idField: 'id', sort: 'id,desc', crudMethod: { ...crudPmNodeInfo }})
  }

**Comment by yuyifade** [comment]
> 解决了

我存cookie解决的，就是不知道有没有其他方法

**Comment by jinmuzhihuakai** [comment]
在组件使用作者封的钩子函数，例如，[ CRUD. HOOK. beforeRefresh](){ this. crud. params.xxxx=xxxx},
