### ISSUE TITLE
请问前端没有路由表，懒加载怎么实现，同时没看明白打包的时候没有 tree shaking?

### ISSUE THREAD

**Issue by llt22** [elunez/eladmin#386]
1 没有引入的组件会被 tree shaking 掉，但是我发现这个项目没有，这样路由从后端获取，打包不会出错，但是没看明白怎么配置，我用 vue cli4创建的项目默认会 tree shaking

2 前端没有路由表，懒加载怎么实现，我测试了现在框架多个页面是打包在一个 js 文件里面的

**Comment by elunez** [comment]
> 1 没有引入的组件会被 tree shaking 掉，但是我发现这个项目没有，这样路由从后端获取，打包不会出错，但是没看明白怎么配置，我用 vue cli4创建的项目默认会 tree shaking
> 
> 2 前端没有路由表，懒加载怎么实现，我测试了现在框架多个页面是打包在一个 js 文件里面的

前端给不了太多建议，懒加载实现逻辑在
![image](https://user-images.githubusercontent.com/42142420/83736012-a78a3280-a683-11ea-90b2-f75a9abf317c.png)
