### ISSUE TITLE
无法新增二级部门的问题

### ISSUE THREAD

**Issue by jameswuwu** [elunez/eladmin#388]
点击新增的时候，出现的都是一个页面，选中了一级部门还是一样的

![image](https://user-images.githubusercontent.com/52489194/83940686-a4747b00-a818-11ea-9d96-c7e5a87be253.png)

**Comment by elunez** [comment]
> 点击新增的时候，出现的都是一个页面，选中了一级部门还是一样的
> 
> ![image](https://user-images.githubusercontent.com/52489194/83940686-a4747b00-a818-11ea-9d96-c7e5a87be253.png)

对比下部门管理这块代码，演示环境是没有问题的
