### ISSUE TITLE
给角色赋 增删改查权限的问题  

### ISSUE THREAD

**Issue by jameswuwu** [elunez/eladmin#389]
第一次给角色增加权限正常
![image](https://user-images.githubusercontent.com/52489194/83941225-58c3d080-a81c-11ea-8819-33befba8c3c6.png)

再一次修改角色的权限的时候，此时取的数据还是redis中的，数据库没有跟新
![image](https://user-images.githubusercontent.com/52489194/83941252-932d6d80-a81c-11ea-92f9-1ad47d6e6934.png)

**Comment by elunez** [comment]
https://github.com/elunez/eladmin/commit/ca43526915c8ec8458f077ac4d0eb2a6d1c3795e
