### ISSUE TITLE
JwtAuthorizationTokenFilter校验token时有一点问题

### ISSUE THREAD

**Issue by 91wangmeng** [elunez/eladmin#39]
通过token 获取username 
username = jwtTokenUtil.getUsernameFromToken(authToken); 
通过username获取用户信息
 UserDetails userDetails = this.userDetailsService.loadUserByUsername(username);
校验token是否有效
jwtTokenUtil.validateToken(authToken, userDetails)
判断条件里
 JwtUser user = (JwtUser) userDetails;
 final String username = getUsernameFromToken(token);
 username.equals(user.getUsername())
本来用户信息就是根据token获取的用户名来获取的
然后你又比较这个获取的用户信息内的用户名与token获取的用户名是否相等.....
好像没什么意义

**Comment by elunez** [comment]
的确判断username.equals(user.getUsername())是多余的，已删除
