### ISSUE TITLE
角色、菜单管理问题

### ISSUE THREAD

**Issue by yinlingshishangS** [elunez/eladmin#390]
大佬，在使用我们最新的代码，角色管理还是有某些问题，在给某个角色添加菜单的时候，依然会将很多菜单删除。
![image](https://user-images.githubusercontent.com/35954690/83964601-ba4d7300-a8e0-11ea-97e4-8b991afa86df.png)

**Comment by yinlingshishangS** [comment]
这个是在添加目录的时候出现的问题
![image](https://user-images.githubusercontent.com/35954690/83964671-187a5600-a8e1-11ea-8a57-569c94e7b08d.png)

**Comment by yinlingshishangS** [comment]
在移动菜单的时候也会导致角色权限缺失

**Comment by yinlingshishangS** [comment]
在点击保存的时候。（没有获得相应的数据）
![image](https://user-images.githubusercontent.com/35954690/83965174-4dd47300-a8e4-11ea-88aa-11eba4f5d446.png)

**Comment by elunez** [comment]
修改了菜单，角色的缓存没刷新导致的，待会修复下

**Comment by elunez** [comment]
修改后试试 https://github.com/elunez/eladmin/commit/0f7cefaf4b6c2b516d2bf6e8e3783c1677cf18f6

**Comment by yinlingshishangS** [comment]
好的，谢谢大佬。

**Comment by cai-peiyuan** [comment]
最新版依然有这个问题
