### ISSUE TITLE
启动报错Parameter 1 of constructor in me.zhengjie.modules.mnt.service.impl.AppServiceImpl required a bean of type 'me.zhengjie.modules.mnt.service.mapstruct.AppMapper' that could not be found.

### ISSUE THREAD

**Issue by liuyang77886** [elunez/eladmin#392]
Spring Boot ::       (v2.1.0.RELEASE)
[30melAdmin-[0;39m [31m2020-06-08 07:59:15[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mme.zhengjie.AppRun[0;39m - [1;30mStarting AppRun on DESKTOP-DOMO0RN with PID 34108 (G:\workspaces_cms\eladmin\eladmin\eladmin-system\target\classes started by Administrator in G:\workspaces_cms\eladmin\eladmin\eladmin-system)
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:15[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mme.zhengjie.AppRun[0;39m - [1;30mThe following profiles are active: dev
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:16[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.d.r.c.RepositoryConfigurationDelegate[0;39m - [1;30mMultiple Spring Data modules found, entering strict repository configuration mode!
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:16[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.d.r.c.RepositoryConfigurationDelegate[0;39m - [1;30mBootstrapping Spring Data repositories in DEFAULT mode.
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:17[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.d.r.c.RepositoryConfigurationDelegate[0;39m - [1;30mFinished Spring Data repository scanning in 452ms. Found 23 repository interfaces.
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:17[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker[0;39m - [1;30mBean 'asyncTaskProperties' of type [me.zhengjie.config.thread.AsyncTaskProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:17[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker[0;39m - [1;30mBean 'asyncTaskExecutePool' of type [me.zhengjie.config.thread.AsyncTaskExecutePool$$EnhancerBySpringCGLIB$$3c73f7d3] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:17[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker[0;39m - [1;30mBean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$4a388884] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:18[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker[0;39m - [1;30mBean 'redisConfig' of type [me.zhengjie.config.RedisConfig$$EnhancerBySpringCGLIB$$6360ce9c] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:18[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker[0;39m - [1;30mBean 'org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration' of type [org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration$$EnhancerBySpringCGLIB$$e2e650be] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:18[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker[0;39m - [1;30mBean 'objectPostProcessor' of type [org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:18[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker[0;39m - [1;30mBean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@5f9f3e58' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:18[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker[0;39m - [1;30mBean 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration' of type [org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration$$EnhancerBySpringCGLIB$$7baf370] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:18[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker[0;39m - [1;30mBean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:20[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.b.w.e.tomcat.TomcatWebServer[0;39m - [1;30mTomcat initialized with port(s): 8000 (http)
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:20[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.a.coyote.http11.Http11NioProtocol[0;39m - [1;30mInitializing ProtocolHandler ["http-nio-8000"]
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:20[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.a.catalina.core.StandardService[0;39m - [1;30mStarting service [Tomcat]
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:20[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.a.catalina.core.StandardEngine[0;39m - [1;30mStarting Servlet Engine: Apache Tomcat/9.0.12
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:20[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.a.c.core.AprLifecycleListener[0;39m - [1;30mThe APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [E:\code\jdk1.8.0_181\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;E:/code/jdk1.8.0_251/jre8/bin/server;E:/code/jdk1.8.0_251/jre8/bin;E:/code/jdk1.8.0_251/jre8/lib/amd64;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\IDM Computer Solutions\UltraEdit;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;d:\Program Files\Git\cmd;E:\pfile\OpenSSL-Win64\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;J:\javasoft\sonar\sonar-scanner-2.5\bin;C:\Program Files (x86)\scala\bin;C:\Program Files (x86)\Common Files\Thunder Network\KanKan\Codecs;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;E:\pfile\cocos2d-x-cocos2d-x-3.17.2\templates;E:\pfile\cocos2d-x-cocos2d-x-3.17.2\tools\cocos2d-console\bin;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;E:\code\jdk1.8.0_181\bin\;E:\code\Android\android-sdk2441\platform-tools;E:\code\Android\android-sdk2441\tools;D:\Program Files\Fiddler;E:\code\gradle-4.10.2\bin;E:\pfile\Python37;C:\Users\Administrator\AppData\Roaming\npm;E:\codes\MicrosoftVSCode\bin;E:\pfile\opcv\opencv2.4.13.6\build\x64\vc14\bin;E:\pfile\cmake-3.12.4-win64-x64\bin;D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;E:\pfile\cuda\bin;E:\pfile\cuda\lib\x64;E:\pfile\Anaconda3\Scripts;C:\Program Files (x86)\EPSON\ScanSDK_V10\Bin;E:\pfile\nodejs;d:\Program Files\Docker Toolbox;D:\Qt\Qt5.12.4\5.12.4\mingw73_64\bin;D:\Qt\Qt5.12.4\Tools\mingw730_64\bin;C:\Program Files (x86)\scala\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;;E:\code\eclipse\eclipse-jee-2020-03-R-incubation-win32-x86_64;;.]
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:20[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.a.c.c.C.[Tomcat].[localhost].[/][0;39m - [1;30mInitializing Spring embedded WebApplicationContext
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:20[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.web.context.ContextLoader[0;39m - [1;30mRoot WebApplicationContext: initialization completed in 5167 ms
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:20[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.b.w.s.FilterRegistrationBean[0;39m - [1;30mMapping filter: 'characterEncodingFilter' to: [/*]
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:20[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.b.w.s.DelegatingFilterProxyRegistrationBean[0;39m - [1;30mMapping filter: 'springSecurityFilterChain' to: [/*]
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:20[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.b.w.s.FilterRegistrationBean[0;39m - [1;30mMapping filter: 'webStatFilter' to urls: [/*]
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:20[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.b.w.s.FilterRegistrationBean[0;39m - [1;30mMapping filter: 'corsFilter' to: [/*]
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:20[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.b.w.s.ServletRegistrationBean[0;39m - [1;30mServlet dispatcherServlet mapped to [/]
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:20[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.b.w.s.ServletRegistrationBean[0;39m - [1;30mServlet statViewServlet mapped to [/druid/*]
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:20[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mc.a.d.s.b.a.DruidDataSourceAutoConfigure[0;39m - [1;30mInit DruidDataSource
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:21[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mc.alibaba.druid.pool.DruidDataSource[0;39m - [1;30m{dataSource-1} inited
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:21[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.h.jpa.internal.util.LogHelper[0;39m - [1;30mHHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:21[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35morg.hibernate.Version[0;39m - [1;30mHHH000412: Hibernate Core {5.3.7.Final}
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:21[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35morg.hibernate.cfg.Environment[0;39m - [1;30mHHH000206: hibernate.properties not found
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:21[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.h.annotations.common.Version[0;39m - [1;30mHCANN000001: Hibernate Commons Annotations {5.0.4.Final}
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:22[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35morg.hibernate.dialect.Dialect[0;39m - [1;30mHHH000400: Using dialect: org.hibernate.dialect.MySQL5InnoDBDialect
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:24[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.o.j.LocalContainerEntityManagerFactoryBean[0;39m - [1;30mInitialized JPA EntityManagerFactory for persistence unit 'default'
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:24[0;39m [32m[main][0;39m [31mWARN [0;39m [1;35mo.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext[0;39m - [1;30mException encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'appController' defined in file [G:\workspaces_cms\eladmin\eladmin\eladmin-system\target\classes\me\zhengjie\modules\mnt\rest\AppController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'appServiceImpl' defined in file [G:\workspaces_cms\eladmin\eladmin\eladmin-system\target\classes\me\zhengjie\modules\mnt\service\impl\AppServiceImpl.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'me.zhengjie.modules.mnt.service.mapstruct.AppMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:24[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.o.j.LocalContainerEntityManagerFactoryBean[0;39m - [1;30mClosing JPA EntityManagerFactory for persistence unit 'default'
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:24[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mc.alibaba.druid.pool.DruidDataSource[0;39m - [1;30m{dataSource-1} closing ...
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:24[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mc.alibaba.druid.pool.DruidDataSource[0;39m - [1;30m{dataSource-1} closed
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:24[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.a.catalina.core.StandardService[0;39m - [1;30mStopping service [Tomcat]
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:24[0;39m [32m[main][0;39m [34mINFO [0;39m [1;35mo.s.b.a.l.ConditionEvaluationReportLoggingListener[0;39m - [1;30m

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[0;39m[30melAdmin-[0;39m [31m2020-06-08 07:59:24[0;39m [32m[main][0;39m [1;31mERROR[0;39m [1;35mo.s.b.d.LoggingFailureAnalysisReporter[0;39m - [1;30m

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 1 of constructor in me.zhengjie.modules.mnt.service.impl.AppServiceImpl required a bean of type 'me.zhengjie.modules.mnt.service.mapstruct.AppMapper' that could not be found.

Action:

Consider defining a bean of type 'me.zhengjie.modules.mnt.service.mapstruct.AppMapper' in your configuration.

[0;39m

**Comment by elunez** [comment]
mvn compile

看看有没有 AppMapper 的实现类 target -> generated-sources -> mnt.service.mapstruct

![image](https://user-images.githubusercontent.com/42142420/83985522-26c18400-a96c-11ea-9f05-5cd9bf8cf6a0.png)

**Comment by liuyang77886** [comment]
target下只有classes和test-classes两个文件夹
