### ISSUE TITLE
通过mvn compile，eladmin-system生成了mapstruct，但是eladmin\eladmin-logging\target\generated-sources\annotations下是空的。启动报错

### ISSUE THREAD

**Issue by liuyang77886** [elunez/eladmin#395]
eclipse2020(4.15),win10,jdk1.8,maven3.3.9
通过mvn compile，eladmin-system生成了mapstruct，但是eladmin\eladmin-logging\target\generated-sources\annotations下是空的。启动报错

Parameter 1 of constructor in me.zhengjie.service.impl.LogServiceImpl required a bean of type 'me.zhengjie.service.mapstruct.LogErrorMapper' that could not be found.

Action:

Consider defining a bean of type 'me.zhengjie.service.mapstruct.LogErrorMapper' in your configuration.

_Originally posted by @liuyang77886 in https://github.com/elunez/eladmin/issues/392#issuecomment-640672770_

**Comment by elunez** [comment]
Eclipse 没研究过，可以百度看看

**Comment by elunez** [comment]
https://el-admin.vip/guide/ksks.html

后端运行[Eclipse]

**Comment by Django47** [comment]
> https://el-admin.vip/guide/ksks.html
> 
> 后端运行[Eclipse]

请问我的IDEA也出现了相同的问题该怎么办？一开始啥都没改，用maven的compile没问题，但是用IDEA的build会出现很多
![image](https://user-images.githubusercontent.com/34894492/103059217-6df92480-45df-11eb-8e9e-de502e053ffa.png)这样的cannot find symbol的问题，我自己在pom里加上
`<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <forceJavacCompilerUse>true</forceJavacCompilerUse>

                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.16</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>`以后就会出现题主的问题，请问该怎么办呢？
