### ISSUE TITLE
前端代码vue生成不完整。

### ISSUE THREAD

**Issue by liuyang77886** [elunez/eladmin#399]
缺少api，能否给个示例

**Comment by elunez** [comment]
![image](https://user-images.githubusercontent.com/42142420/84250746-07c71b80-ab3f-11ea-8475-a4d231ee659b.png)
![image](https://user-images.githubusercontent.com/42142420/84250765-0eee2980-ab3f-11ea-9513-d58a20aa7029.png)

前端路径：`/Users/jie/Documents/work/me/front/eladmin-web/src/views/test` 需要放到 views 目录

代码生成后，新增菜单

![image](https://user-images.githubusercontent.com/42142420/84251015-57a5e280-ab3f-11ea-9b3e-fb9c0339f2e3.png)

角色管理中分配菜单

![image](https://user-images.githubusercontent.com/42142420/84251115-7b692880-ab3f-11ea-936d-484151297067.png)

重启后端项目，刷新前端页面，进入菜单

![Uploading image.png…]()
