### ISSUE TITLE
关于数据权限的使用

### ISSUE THREAD

**Issue by yinlingshishangS** [elunez/eladmin#400]
大佬，关于数据权限的使用，我看了我们的介绍，以及源码，还是没太看懂。

**Comment by JinlongLiao** [comment]
推荐你看一下SpringSecurity ,这里大部分还是基于它的 只是在健全哪里 扩展 了下
```me.zhengjie.config.ElPermissionConfig#check```

**Comment by elunez** [comment]
> 大佬，关于数据权限的使用，我看了我们的介绍，以及源码，还是没太看懂。

数据权限是根据部门维度去控制数据的显示或者隐藏的，既然是基于部门，那肯定是使用表中的部门ID去查询数据，可以看下底层实现 QueryHelp.class 中的 42 行

**Comment by yinlingshishangS** [comment]
大佬，比如说：如果我想要创建一个表，这个表在完成增删改查后，想用我们的数据权限去管理，是不是意味着我要有一张表和dept_id有关联

**Comment by yinlingshishangS** [comment]
> > 大佬，关于数据权限的使用，我看了我们的介绍，以及源码，还是没太看懂。
> 
> 数据权限是根据部门维度去控制数据的显示或者隐藏的，既然是基于部门，那肯定是使用表中的部门ID去查询数据，可以看下底层实现 QueryHelp.class 中的 42 行

大佬，比如说：如果我想要创建一个表，这个表在完成增删改查后，想用我们的数据权限去管理，是不是意味着我要有一张表和dept_id有关联

**Comment by yinlingshishangS** [comment]
> 推荐你看一下SpringSecurity ,这里大部分还是基于它的 只是在健全哪里 扩展 了下
> `me.zhengjie.config.ElPermissionConfig#check`

谢谢大佬，我研究下
