### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by jameswuwu** [elunez/eladmin#401]
版本2.5
环境：本地

1. 改了用户名，原来的用户名还能登陆，未清除缓存

2. 新增完菜单的权限按钮，在角色管理模块，给角色菜单分配的时候没有出现 刚刚新增的权限按钮

**Comment by elunez** [comment]
> 版本2.5
> 环境：本地
> 
> 1. 改了用户名，原来的用户名还能登陆，未清除缓存
> 2. 新增完菜单的权限按钮，在角色管理模块，给角色菜单分配的时候没有出现 刚刚新增的权限按钮

关于 1，在 UserServiceImpl 的 update 中做如下修改
![image](https://user-images.githubusercontent.com/42142420/84249837-dac63900-ab3d-11ea-936c-eac688d476ae.png)
```
// 如果用户名称修改
        if(!resources.getUsername().equals(user.getUsername())){
            redisUtils.del("user::username:" + user.getUsername());
        }
```
关于2，测试没有这个问题，可以在演示环境测试

**Comment by elunez** [comment]
https://github.com/elunez/eladmin/commit/4ddf97ce9c45d98e1a833e4d0e19d11c6fb4541c
