### ISSUE TITLE
用户角色菜单

### ISSUE THREAD

**Issue by yinlingshishangS** [elunez/eladmin#402]
在使用我们角色与管理员的，还存在以下问题：
1、有时候给管理员分配权限（或给其他角色分配权限），还是会有部分角色、菜单失效的问题。【我保存两次就很少出现此问题】
2、对于按钮级别的权限，分配权限后，需要删除redis缓存，重新登录，才可以在角色分配菜单权限中找到增删改查按钮权限

**Comment by elunez** [comment]
已修复 https://github.com/elunez/eladmin/commit/96276dfc589f7289a7e5ef8a2e0d707f6ec2abec
