### ISSUE TITLE
图床管理删除单张照片错误

### ISSUE THREAD

**Issue by EmKs** [elunez/eladmin#404]
图床管理上传单张照片，再上传完成后再对话框内点击删除图标，报异常，controller里接收的是Long数组，传入单个会报错
org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.lang.Long[]` out of VALUE_NUMBER_INT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long[]` out of VALUE_NUMBER_INT token

**Comment by elunez** [comment]
> 图床管理上传单张照片，再上传完成后再对话框内点击删除图标，报异常，controller里接收的是Long数组，传入单个会报错
> org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.lang.Long[]` out of VALUE_NUMBER_INT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.Long[]` out of VALUE_NUMBER_INT token

已修复 https://github.com/elunez/eladmin-web/commit/92434003bf3e447d360446a62f26a40fb421c55c
