### ISSUE TITLE
火狐浏览器，打开后台管理页面样式的问题

### ISSUE THREAD

**Issue by jameswuwu** [elunez/eladmin#407]
1.版本: v2.5
2.环境：线上
3.复现步骤：按f12调试的，在还原，用户管理、菜单管理模块列表，有遮挡
![image](https://user-images.githubusercontent.com/52489194/84462978-f5fe8900-aca2-11ea-857b-c55c045f1616.png)

![image](https://user-images.githubusercontent.com/52489194/84463138-673e3c00-aca3-11ea-9d96-782bb7f6d851.png)

**Comment by jameswuwu** [comment]
火狐浏览器

**Comment by elunez** [comment]
> 1.版本: v2.5
> 2.环境：线上
> 3.复现步骤：按f12调试的，在还原，用户管理、菜单管理模块列表，有遮挡
> ![image](https://user-images.githubusercontent.com/52489194/84462978-f5fe8900-aca2-11ea-857b-c55c045f1616.png)
> 
> ![image](https://user-images.githubusercontent.com/52489194/84463138-673e3c00-aca3-11ea-9d96-782bb7f6d851.png)

这个无能为力
