### ISSUE TITLE
角色管理->选中角色;  菜单分配->点击保存;刷新页面所有二级菜单权限消失

### ISSUE THREAD

**Issue by cai-peiyuan** [elunez/eladmin#412]
版本：2.5
环境：本地
重现步骤：打开角色管理，选中一个角色，菜单分配按钮处点击保存按钮，重新刷新页面，显示404。返回首页刷新页面后，二级菜单权限消失。

![image](https://user-images.githubusercontent.com/37100059/84799576-07db8580-b02f-11ea-91a7-d4639ef4ebab.png)
![image](https://user-images.githubusercontent.com/37100059/84799600-1164ed80-b02f-11ea-92d5-c3c873656bad.png)
![image](https://user-images.githubusercontent.com/37100059/84799636-217ccd00-b02f-11ea-95eb-3dd236bc4470.png)

原因：
http://localhost:8013/api/menus/superior
接口没有返回数据之前点了保存按钮，导致二级菜单权限消失。
建议在接口返回数据之前，保存按钮为不可点击状态。

**Comment by elunez** [comment]
感谢反馈，已修复 https://github.com/elunez/eladmin-web/commit/cd01e3a21b08980300895e092e30dd7b21ffd35d

**Comment by gee1k** [comment]
好像还是存在，前端菜单树那里的逻辑感觉有问题。有时候正在操作时会莫名的自动折叠回去了。然后会发现内部的子级没有选中（正确的数据是选中的）
