### ISSUE TITLE
角色菜单分配后，保存后，漏了一些增删改的权限

### ISSUE THREAD

**Issue by jameswuwu** [elunez/eladmin#413]
版本: v2.5
环境：线上
复现步骤：
前提：普通用户，菜单分配--系统管理--用户管理下面所有的权限都勾选了
![image](https://user-images.githubusercontent.com/52489194/84970693-c55c9a80-b14d-11ea-9f7a-f554fb2431b2.png)

此时，只打开菜单分配--系统管理--用户管理，去掉一个用户新增的权限
![image](https://user-images.githubusercontent.com/52489194/84970874-208e8d00-b14e-11ea-8f99-f28b8b50abe1.png)

在刷新界面的时候，菜单分配--系统管理--其他模块的增删改权限都消失了
![image](https://user-images.githubusercontent.com/52489194/84971003-5df31a80-b14e-11ea-84d1-a479b5bbb335.png)

原因可能是，跟新菜单权限的时候，参数少了一部分
![image](https://user-images.githubusercontent.com/52489194/84971089-9561c700-b14e-11ea-9869-7e989950df44.png)

**Comment by jameswuwu** [comment]
前提：普通用户，菜单分配--系统管理   下面所有的菜单权限都勾选了

**Comment by elunez** [comment]
无法复现，视频如下

https://img.el-admin.xin/QQ20200621-180503-HD.mp4

如果可以的话，希望提供下操作的视频
