### ISSUE TITLE
用户管理-编辑用户-选择多个角色之后保存，前端控制台会报错，保存弹框关闭前，角色框里的值会变一下。岗位也有同样的问题。

### ISSUE THREAD

**Issue by 184478007** [elunez/eladmin#414]
用户管理-编辑用户-选择多个角色之后保存，前端控制台会报错，保存弹框关闭前，角色框里的值会变一下。岗位也有同样的问题。
版本：v2.5
环境：在线
复现步骤：步骤：
选两个角色
![image](https://user-images.githubusercontent.com/45475868/85002900-0f627200-b188-11ea-8a0c-54fa9344525d.png)
报错
![image](https://user-images.githubusercontent.com/45475868/85003209-80a22500-b188-11ea-9197-077990d4b696.png)
角色值自动变化
![image](https://user-images.githubusercontent.com/45475868/85003392-bb0bc200-b188-11ea-8b35-3cb913911a7a.png)

**Comment by elunez** [comment]
> 用户管理-编辑用户-选择多个角色之后保存，前端控制台会报错，保存弹框关闭前，角色框里的值会变一下。岗位也有同样的问题。
> 版本：v2.5
> 环境：在线
> 复现步骤：步骤：
> 选两个角色
> ![image](https://user-images.githubusercontent.com/45475868/85002900-0f627200-b188-11ea-8a0c-54fa9344525d.png)
> 报错
> ![image](https://user-images.githubusercontent.com/45475868/85003209-80a22500-b188-11ea-9197-077990d4b696.png)
> 角色值自动变化
> ![image](https://user-images.githubusercontent.com/45475868/85003392-bb0bc200-b188-11ea-8b35-3cb913911a7a.png)

我这边测试无法复现，可以录视频复现，先关闭issues，有复现视频随时打开
