### ISSUE TITLE
用户编辑保存时会闪一下，两个角色都变成普通用户，岗位也会变成两个一样的

### ISSUE THREAD

**Issue by 184478007** [elunez/eladmin#418]
用户编辑保存时会闪一下，两个角色都变成普通用户，岗位也会变成两个一样的
[用户编辑保存时会闪一下，两个角色都变成普通用户，岗位也会变成两个一样的.zip](https://github.com/elunez/eladmin/files/4810650/default.zip)

**Comment by 184478007** [comment]
线上的项目前端控制台没有报错，但是保存时还是会闪

**Comment by elunez** [comment]
中午处理
