### ISSUE TITLE
打包项目时出现错误

### ISSUE THREAD

**Issue by ZyuHookie** [elunez/eladmin#425]
版本: v2.45
环境：本地
复现步骤：
![image](https://user-images.githubusercontent.com/43179640/85757007-ce4afe80-b741-11ea-9f01-6203bbe2efef.png)
日志提供：
报错截图
![image](https://user-images.githubusercontent.com/43179640/85757366-fd617000-b741-11ea-9726-c2a4946fd07d.png)
中间没截图的详细[ERROR] Failed to execute goal on project eladmin-system: Could not resolve dependencies for project me.zhengjie:eladmin-system:jar:2.4: The following artifacts could not be resolved: me.zhengjie:eladmin-generator:jar:2.4, me.zhengjie:eladmin-tools:jar:2.4: Could not find artifact me.zhengjie:eladmin-generator:jar:2.4 in public (http://maven.aliyun.com/nexus/content/groups/public/) -> [Help 1]
请问作者知道原因吗？如果有看到的话期待回复，谢谢

**Comment by JinlongLiao** [comment]
先在根目录 执行install，后再system package

**Comment by veargithub** [comment]
我也遇到一样的问题

怀疑是idea自带的maven不好使，去官网下载最新的3.6.3,然后用它在项目根目录执行mvn install就好了
