### ISSUE TITLE
每次重新启动时，首次验证码生成非常久

### ISSUE THREAD

**Issue by wtf-boy** [elunez/eladmin#427]
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.7.1908 (Core)
Release:        7.7.1908
Codename:       Core

版本：v2.4

**Comment by elunez** [comment]
重新启动项目，分别使用 ip:端口 和 域名去请求 /auth/code ，如果只有 域名形式访问慢，那么就是nginx配置问题
