### ISSUE TITLE
验证码闪烁

### ISSUE THREAD

**Issue by veargithub** [elunez/eladmin#429]
版本: v2.5
环境：线上
复现步骤：必现
日志提供：
可选：生成出来的图片
data:image/gif;base64,R0lGODlhbwAkAPcAAAAAAAEBAQICAgMDAwQEBAUFBQYGBgcHBwgICAkJCQoKCgsLCwwMDA0NDQ4ODg8PDxAQEBERERISEhMTExQUFBUVFRYWFhcXFxgYGBkZGRoaGhsbGxwcHB0dHR4eHh8fHyAgICEhISIiIiMjIyQkJCUlJSYmJicnJygoKCkpKSoqKisrKywsLC0tLS4uLi8vLzAwMDExMTIyMjMzMzQ0NDU1NTY2Njc3Nzg4ODk5OTo6Ojs7Ozw8PD09PT4+Pj8/P0BAQEFBQUJCQkNDQ0REREVFRUZGRkdHR0hISElJSUpKSktLS0xMTE1NTU5OTk9PT1BQUFFRUVJSUlNTU1RUVFVVVVZWVldXV1hYWFlZWVpaWltbW1xcXF1dXV5eXl9fX2BgYGFhYWJiYmNjY2RkZGVlZWZmZmdnZ2hoaGlpaWpqamtra2xsbG1tbW5ubm9vb3BwcHFxcXJycnNzc3R0dHV1dXZ2dnd3d3h4eHl5eXp6ent7e3x8fH19fX5+fn9/f4CAgIGBgYKCgoODg4SEhIWFhYaGhoeHh4iIiImJiYqKiouLi5ONjZuPj6OSkqqTk7CVlbaXl7uYmMCZmcWamsmbm82cnNCcnNOdndWdndientmentqentuentyentyfn9yfn9yfn9ufn9qfn9mgoNigoNagoNWhodOhodCios6jo8ukpMmlpcampsOoqMCqqr2srLmurrawsLOzs7S0tLW1tba2tre3t7i4uLm5ubq6usHBwc7OztjY2OTk5O7u7vX19vn6+vz8/P39/f7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v///yH/C05FVFNDQVBFMi4wAwEAAAAh+QQACgAAACwAAAAAbwAkAAAI/gD/CRxIsKDBgwgTKlzIsKHDhxAjSpxIsaLFixgzatzIsWAwX7569fIFrKNJjL968VrZ61c4hil/AQsGLKWvYSdzQhSmkiQwYL5W/lIYrFewguFAvtTJNGE4Xr1wFvzFqyRCX0MNJs2qEVcoX00XBl1qkOrRg0YRAuXoK5QnT7zOhi3IiytasGgTFjX5q9bbWlbnCtwV+CCwXgh7kS14OGcwXm/hym26a+Hjq4UJgmza9u3XsLsWG2xEurRp04zThh3Wy62nr1JNVlV4unZpgkXtzn0cOdRstogRBiOtl/RRYSkzCxZY1G2n17xuYgxGODHxhKRFgpy8/CBV55596mPV3TBo5nAqryNU3x3iR16uPXWaH7m+ffuhKkFSpYtlf2HsjdZIexkN8wtIQa2k4IIr6YLLg6FsMkkkkUhCCSbPkRbKLiQJSOCHCQHVi4ZvPQedL8MNCOKKB6mX0i7xkVYXizQKFOBAw/hCmnyvcRhbjcvdSBBxKcXnG3lA5iTkQAE2x2MovSiX5EZL2qiid/BFhgteU1J5ZYtfJuTLLr1J1+VFVf6TpkHAQOaZamdKlOaawrXm2W9xOjRnmBGx5pYueT60p0bcBYodn0MiaqhOgy4qWKOOhgVppExNSqmSttV2aVOZampSQAAh+QQACgAAACwAAAAAbwAkAIcAAAABAQECAgIDAwMEBAQFBQUGBgYHBwcICAgJCQkKCgoLCwsMDAwNDQ0ODg4PDw8QEBARERESEhITExMUFBQVFRUWFhYXFxcYGBgZGRkaGhobGxscHBwdHR0eHh4fHx8gICAhISEiIiIjIyMkJCQlJSUmJiYnJycoKCgpKSkqKiorKyssLCwtLS0uLi4vLy8wMDAxMTEyMjIzMzM0NDQ1NTU2NjY3Nzc4ODg5OTk6Ojo7Ozs8PDw9PT0+Pj4/Pz9AQEBBQUFCQkJDQ0NERERFRUVGRkZHR0dISEhJSUlKSkpLS0tMTExNTU1OTk5PT09QUFBRUVFSUlJTU1NUVFRVVVVWVlZXV1dYWFhZWVlaWlpbW1tcXFxdXV1eXl5fX19gYGBhYWFiYmJjY2NkZGRlZWVmZmZnZ2doaGhpaWlqampra2tsbGxtbW1ubm5vb29wcHBxcXFycnJzc3N0dHR1dXV2dnZ3d3d4eHh5eXl6enp7e3t8fHx9fX1+fn5/f3+AgICBgYGCgoKDg4OEhISFhYWGhoaHh4eIiIiJiYmKioqLi4uTjY2bj4+jkpKqk5OwlZW2l5e7mJjAmZnFmprJm5vNnJzQnJzTnZ3VnZ3Ynp7Znp7anp7bnp7cnp7cn5/cn5/cn5/bn5/an5/ZoKDYoKDWoKDVoaHToaHQoqLTrKzZvb3fy8vn2trv6Oj18fH59/f7+/v9/f3+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7+/v7///8I/gD/CRxIsKDBgwgTKlzIsKHDhxAjSpxIsaLFixgzatxoEdarj7CycRxJMqLHWLJieZRVsqXLg69iEYQF66XNl69EDpT16qbBVaFc+ayYk6DKoQRdhfLkiZVMpA9hPf2XLSZUgq9WMV3V8+rCWK9Cgq3p1Sgrpk2nli0I9qPatQJnyJ1Lly7cuwbr6p2Lt2/cGWbRhpLrty9hg7FaqZLrKRQrVywLXz2MUC4rVZ46MQ21ilUrV10lt6R8kHLiy2g7qUbLunXrULBXdW7VyqpogqTzAk7I0xVtVsCDCwcuW7Yq2KxXN1blmazh3ZWh24TlmxVQppo9MXf1Fmnugt+hyb5qdR0t89ACZXn8aFtj+IHvy8pydV0zZ9BhZamn7hxj/H//3TUeZppk0lRoPPVn0X8B9hWLb5hppkorsPAU2UUMSnebQGEN9AorSzE1YUYZblgQZAfR54mBE14oUYkmDiQUb66cJWIr3TEEY4z/FIUQWAIlFqJjCiq0Y4ztGeRRQbIo5skqDx1pIlg6MZkkW1FqCJ6WG35UZXofucclfGOKVlVYMmXjUZEVSckjWK7gl2ObZQJYJ48kuYmnS3vttedQfer1p0YBAQA7

**Comment by elunez** [comment]
字体问题，LoginProperties 中修改字体
