### ISSUE TITLE
when create user ,error

### ISSUE THREAD

**Issue by zq1297618027** [elunez/eladmin#435]
![image](https://user-images.githubusercontent.com/16516939/87131211-ac678500-c2c6-11ea-877e-f254e5d301d1.png)
_JSON parse error: Cannot construct instance of `me.zhengjie.modules.system.domain.Role` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (1); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `me.zhengjie.modules.system.domain.Role` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (1) at [Source: (PushbackInputStream); line: 1, column: 107] (through reference chain: me.zhengjie.modules.system.domain.User["roles"]->java.util.HashSet[0])_

**Comment by elunez** [comment]
https://gitee.com/elunez/eladmin-web/commit/2d62228015d67fb0b7f5b4294b1ad580d3db6ba5
