### ISSUE TITLE
部署到linux后，部署管理执行时偶尔会卡住，卡在停止应用那一步。（如能复现最好，如无法复现，希望能给点提示我定位看看）

### ISSUE THREAD

**Issue by gcs1230** [elunez/eladmin#436]
![image](https://user-images.githubusercontent.com/50815165/87274724-00fd4100-c50f-11ea-8f87-07a438e5dd2f.png)
![image](https://user-images.githubusercontent.com/50815165/87274736-09557c00-c50f-11ea-883f-3d74c84ae3cb.png)

**Comment by spar025** [comment]
看看分配的java堆栈内存，是不是太小了
