### ISSUE TITLE
通用查询的对象 int 类型的字段为什么会自动赋值0

### ISSUE THREAD

**Issue by gee1k** [elunez/eladmin#438]
通用查询的对象 int 类型的字段为什么会自动赋值0

https://el-admin.vip/guide/hdsc.html#%E9%80%9A%E7%94%A8%E6%9F%A5%E8%AF%A2

![image](https://user-images.githubusercontent.com/12059800/87432639-dc8e8b00-c61a-11ea-94d0-f1c8a1e08813.png)

![image](https://user-images.githubusercontent.com/12059800/87432672-e617f300-c61a-11ea-96af-a09eab5e316d.png)

**Comment by elunez** [comment]
int 是非包装类 ，默认值就是 0，你把 int  改成 Integer 就好了 

建议多补补基础
