### ISSUE TITLE
提一个有关角色的建议

### ISSUE THREAD

**Issue by wj985712588** [elunez/eladmin#44]
我在创建角色时发现以下问题。
我有一个超级管理员，现在见一个普通管理员，赋予普通管理员创建用户
的权限，然后只拥有普通管理员角色的用户在创建角色时可以选择
超级管理员者这个角色。
我在想能不能给角色分配一个level属性。
![image](https://user-images.githubusercontent.com/22348075/56402101-8eab9b80-628e-11e9-9587-8d17e370743f.png)
![image](https://user-images.githubusercontent.com/22348075/56402126-af73f100-628e-11e9-8ea7-bed4972b7d86.png)

**Comment by elunez** [comment]
已完成，下个版本上
