### ISSUE TITLE
【bug】前端生成模版有问题

### ISSUE THREAD

**Issue by ICanDoBette** [elunez/eladmin#440]
版本: v2.5
环境：本地/线上
复现步骤：
前端生成模版有问题，问题文件
\eladmin\eladmin-system\src\main\resources\template\generator\front\index.ftl
问题行数：122&123
问题：在很多node版本中，这个地方只允许一行换行，这里多了一行换行，导致生成的代码无法运行
![image](https://user-images.githubusercontent.com/30899869/87623908-0352db80-c759-11ea-9274-7d35e4f8cb3a.png)
解决方案：删除一个换行

**Comment by elunez** [comment]
收到
