### ISSUE TITLE
多表关联时，查询其中一个表的数据后，查询的数据有关两个表的数据无限递归

### ISSUE THREAD

**Issue by lpl606606** [elunez/eladmin#442]
查询的数据无限递归，没有报OOM，请问作者知道什么原因吗？而且作者有没有更好的方式将这块优化下  
下边是角色和用户为多对多的关联，我查询用户的数据

![微信图片_20200722111638](https://user-images.githubusercontent.com/46151118/88130340-dbf28780-cc0c-11ea-9f68-e4e06d1d315c.png)

**Comment by Boss1ee** [comment]
删去lombok注解，重写toString方法

**Comment by lpl606606** [comment]
我看作者在BaseEntity重写了toString(),我在自己写的项目中用同样的方式会发生toString导致的OOM，但我在该项目调用正常，不知道原因是什么？

**Comment by Boss1ee** [comment]
同一对象后面的id值都是一样的，实际上没有递归吧，IDE是一直递归展示
