### ISSUE TITLE
后端的请求路径第一级能否统一

### ISSUE THREAD

**Issue by caiming100** [elunez/eladmin#452]
后端的请求路径有部分不是以api开头，比如系统授权接口为@RequestMapping("/auth")
能否统一，方便nginx部署时前后用同一个端口，根据路径来区分前后端请求

**Comment by elunez** [comment]
> 后端的请求路径有部分不是以api开头，比如系统授权接口为@RequestMapping("/auth")
> 能否统一，方便nginx部署时前后用同一个端口，根据路径来区分前后端请求

可以，后续修改
