### ISSUE TITLE
前端项目部署

### ISSUE THREAD

**Issue by ahualy** [elunez/eladmin#458]
项目打包部署在nginx上，但是有一个问题就是，在前端没法去修改后端的ip，端口，如果要修改的话只能重新打包，能不能在dist中分离初配置文件，直接进行修改呢，看看谁有好的办法，麻烦解决以下，网上查了好多没有动态修改.env文件配置的后端访问路径的方法。

**Comment by elunez** [comment]
![image](https://user-images.githubusercontent.com/42142420/90387369-9ebcd080-e0b8-11ea-888b-732564bac8ac.png)

.env.production 中地址设置为空，然后在nginx中配置代理

```
location /api {
           # 后端的API服务器
           proxy_pass https://api.auauz.net; 
    	   }

    	   location /auth {
           # 后端的API服务器
           proxy_pass https://api.auauz.net; 
    	   }
```
地址换成自己的即可
