### ISSUE TITLE
open-in-view: false设置无效

### ISSUE THREAD

**Issue by platocff** [elunez/eladmin#460]
当设置成false时session对话还是在整个会话中(当前请求整个过程开始开启了seeseion)。hibernate的lazy load仍然可用可证。因此我去验证关闭：
@Component
public class OpenEntityManagerInViewManager extends EntityManagerFactoryAccessor {
    public void cancel() {
        EntityManagerFactory emf = obtainEntityManagerFactory();
        EntityManagerHolder emHolder = (EntityManagerHolder) TransactionSynchronizationManager.unbindResourceIfPossible(emf);
        EntityManagerFactoryUtils.closeEntityManager(emHolder.getEntityManager());
    }
    public void add() {
        EntityManagerFactory emf = obtainEntityManagerFactory();
        if (!TransactionSynchronizationManager.hasResource(emf)) {
            EntityManager em = createEntityManager();
            EntityManagerHolder emHolder = new EntityManagerHolder(em);
            TransactionSynchronizationManager.bindResource(emf,emHolder);
        }
    }
}
然后我在controller里去调用cancel以后发现懒加载失败。证明了jpa在执行完一个sql会话以后就关闭了session。（many-to-mang开始懒加载时session已经关闭）关联sql再执行则失败。
由此可知open-in-view设置为false时并没有启作用

**Comment by elunez** [comment]
https://juejin.im/post/6844903818124066823
