### ISSUE TITLE
使用el-table 展开行功能时控制台报错

### ISSUE THREAD

**Issue by lazy-bum** [elunez/eladmin#461]
版本: v2.5
环境：本地
复现步骤：表格中添加
`
<el-table-column type="expand">
      <template slot-scope="props">
        {{ props.row }}
      </template>
 </el-table-column>
`
日志提供：
可选：提供gif或者视频

**Comment by lazy-bum** [comment]
版本: v2.5
环境：本地
复现步骤：表格中添加
// <el-table-column type="expand">
//      <template slot-scope="props">
//        {{ props.row }}
//      </template>
// </el-table-column>
日志提供：
可选：提供gif或者视

**Comment by elunez** [comment]
https://github.com/elunez/eladmin-web/commit/42348c150baf9a03cd8b599da9e91f59d36066ac
