### ISSUE TITLE
菜单修改权限标识的bug

### ISSUE THREAD

**Issue by spar025** [elunez/eladmin#465]
场景描述：

1. 通过管理员权限登陆，操作菜单管理，新增/修改菜单权限标识
2. 分配角色，功能正常使用
3. 假设权限标识设置错误，再次修改，则在后台重启前，用户无法使用修改后的菜单权限。

该场景在实际使用中，极有可能发生，场景描述如有不理解的地方，请回复沟通。

解决方式：
在登录时，
1、清理用户map缓存
2、清理role::auth的cache
代码：
在authenticationManagerBuilder.getObject().authenticate(authenticationToken);前
加上resetAuthencationRole(username);

private void resetAuthencationRole(String username) {
        userCacheClean.cleanUserCache(username);
        UserDto user;
        try {
            user = userService.findByName(username);
        } catch (EntityNotFoundException e) {
            throw new UsernameNotFoundException("", e);
        }
        redisUtils.del(CacheKey.ROLE_AUTH + user.getId());
    }

**Comment by elunez** [comment]
权限设置后，用户重新登录就会获取到最新的权限

**Comment by spar025** [comment]
> 权限设置后，用户重新登录就会获取到最新的权限

重新登录并不会获得最新权限 ：）
