### ISSUE TITLE
有没有朋友遇到代理失败的问题？请问如何处理

### ISSUE THREAD

**Issue by guanxb** [elunez/eladmin#466]
版本: v2.5
环境：本地
复现步骤：请求api
日志提供：
可选：
在命令行下运行npm run dev，首页请求验证码失败，提示如下：
Proxy error: Could not proxy request auth/code from localhost:8013 to http://localhost:8000/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

**Comment by coder-free** [comment]
怎么解决的呀，我也遇到了。。。

**Comment by lanbaba** [comment]
在同一个环境下试试，我在windows虚拟机上运行碰到，问题，后来前后端全部改成在windows下运行就好了。
