### ISSUE TITLE
代码生成部分的bug

### ISSUE THREAD

**Issue by zfavourite99** [elunez/eladmin#473]
生成代码的时候，如果表里面包含多个 datetime 类型的字段，并且在生成配置里面这些字段的查询类型都设置为 between，则生成的代码Dto部分没有问题，QueryCriteria部分datetime类型的字段名字全叫  createTime。
例子：
表结构：
![image](https://user-images.githubusercontent.com/2630290/91144389-87986700-e6e6-11ea-8ba0-f03b570be513.png)
生成配置：
![image](https://user-images.githubusercontent.com/2630290/91145589-4739e880-e6e8-11ea-8bce-35a2b46ceb59.png)

生成的代码：
Dto:
![image](https://user-images.githubusercontent.com/2630290/91144576-d0e8b680-e6e6-11ea-8a78-277ba02c38f9.png)
QueryCriteria:
![image](https://user-images.githubusercontent.com/2630290/91144633-e52cb380-e6e6-11ea-8b8b-5b10f80baaca.png)

**Comment by elunez** [comment]
收到
