### ISSUE TITLE
token太长的问题

### ISSUE THREAD

**Issue by Angle-bo** [elunez/eladmin#476]
版本: v2.4

实际应用过程中，菜单很多的情况，当用户是非admin的情况，根据权限列表生成的token会很长。
1、请求header过长。
2、token超过浏览器cookie最大长度。
这个后续会有相对应的优化方案吗？
谢谢

**Comment by elunez** [comment]
![image](https://user-images.githubusercontent.com/42142420/92323098-882ae900-f068-11ea-8d4c-2524ebd6f35a.png)
更换合适的算法就行

**Comment by Angle-bo** [comment]
好的，谢谢。

**Comment by Angle-bo** [comment]
更换HS256或者HS384，token长度依然会根据权限列表的长度变动，这样的话，后续如果越来越多的权限。token依然会很长。TokenProvider中解析token生成Authentication用于处理权限。这样的话，是不是就陷入死胡同了。

**Comment by Angle-bo** [comment]
临时的解决办法，去掉了token中用户权限处理，将用户权限列表放到redis中（token为key，OnlineUser中包含Collection<GrantedAuthority> authorities）。在TokenFilter中手动创建UsernamePasswordAuthenticationToken
