### ISSUE TITLE
新加的模块location.reload()后401状态码，正常为304

### ISSUE THREAD

**Issue by cy9707** [elunez/eladmin#484]
1.版本：2.4
2.环境：本地
3.新加的一级菜单中的二级菜单在location.reload()后401状态码，请求头缺失Authorization导致，从菜单点击进入状态码正常200，原有模块在location.reload()后均为304状态码。
4.浏览器控制台断点中请求头：
（1）原有菜单管理模块控制台请求头：
GET /system/menu HTTP/1.1
Host: localhost:8013
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:8013/bgbb/qjt
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cookie: rememberMe=true; password=nbcfYOhzN3+8z5vANYFC+atBXXkStoyvNgjCM/aHFXi6p77AcjZq/1eGO54KjkiCXEiI4QAdPOBnTy9F7/83Mw==; username=admin; EL-ADMIN-TOEKN=Bearer%20eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJkZXB0OmVkaXQsc3RvcmFnZTphZGQsZGVwdDphZGQsbWVudTpkZWwsc2VydmVyRGVwbG95OmVkaXQsbG9nczpleHBvcnQscWp0OmRlbCxxanQ6Ym1zcCxqb2I6ZWRpdCxkZXBsb3lIaXN0b3J5Omxpc3QsZGVwbG95OmFkZCxkaWN0OmFkZCxkZXB0Omxpc3QsYXBwOmRlbCxqb2I6bGlzdCxkYXRhYmFzZTpkZWwsZGljdDpkZWwsZGljdDpsaXN0LHNlcnZlckRlcGxveTpkZWwsZGF0YWJhc2U6bGlzdCx0aW1pbmc6bGlzdCxkZXBsb3k6bGlzdCxxanQ6YWRkLHFqdDplZGl0LGRlcGxveUhpc3Rvcnk6ZGVsLG9ubGluZTpvdXQsbWVudTplZGl0LG1lbnU6bGlzdCxzdG9yYWdlOmRlbCxzZXJ2ZXJEZXBsb3k6YWRkLHFqdDpsaXN0LGRhdGFiYXNlOmVkaXQsZGF0YWJhc2U6YWRkLGRpY3Q6ZWRpdCxkZXB0OmRlbCx1c2VyOmxpc3Qsc3RvcmFnZTplZGl0LGFwcDplZGl0LHJvbGVzOmRlbCxhZG1pbixzdG9yYWdlOmxpc3QsbG9nczpsaXN0LHVzZXI6ZGVsLHNlcnZlcjpsaXN0LGRlcGxveTplZGl0LHRpbWluZzphZGQsYXBwOmxpc3Qsam9iOmFkZCxyb2xlczphZGQsdXNlcjphZGQsYXBwOmFkZCx0aW1pbmc6ZWRpdCxvbmxpbmU6ZXhwb3J0LHJvbGVzOmxpc3QsbWVudTphZGQsam9iOmRlbCx1c2VyOmVkaXQscm9sZXM6ZWRpdCxvbmxpbmU6bGlzdCx0aW1pbmc6ZGVsLGRlcGxveTpkZWwscWp0Onpnc3Asc2VydmVyRGVwbG95Omxpc3QiLCJleHAiOjE1OTk3OTI4OTZ9.kcYEbI-cFUrB52zAn-aKFPnNbTduJg5EhZuDKp9JI7-Mne73eqcy_QA7PksuTFs250e5co8yEuRaqZNseYJprg; sidebarStatus=0
If-None-Match: W/"209-PZ8bf5JYFFeDVEw+oWMMA0FyZlE"

----------------------------·idea->tokenFilter请求头：（在刷新页面时，system/menu不向服务器发送请求，此头部为通过system/menu（get请求方式进入系统后页面中其他内容的请求头））
=== MimeHeaders ===
x-forwarded-host = localhost:8013
x-forwarded-proto = http
x-forwarded-port = 8013
x-forwarded-for = 127.0.0.1
cookie = rememberMe=true; password=nbcfYOhzN3+8z5vANYFC+atBXXkStoyvNgjCM/aHFXi6p77AcjZq/1eGO54KjkiCXEiI4QAdPOBnTy9F7/83Mw==; username=admin; sidebarStatus=1; EL-ADMIN-TOEKN=Bearer%20eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJkZXB0OmVkaXQsc3RvcmFnZTphZGQsZGVwdDphZGQsbWVudTpkZWwsc2VydmVyRGVwbG95OmVkaXQsbG9nczpleHBvcnQscWp0OmRlbCxxanQ6Ym1zcCxqb2I6ZWRpdCxkZXBsb3lIaXN0b3J5Omxpc3QsZGVwbG95OmFkZCxkaWN0OmFkZCxkZXB0Omxpc3QsYXBwOmRlbCxqb2I6bGlzdCxkYXRhYmFzZTpkZWwsZGljdDpkZWwsZGljdDpsaXN0LHNlcnZlckRlcGxveTpkZWwsZGF0YWJhc2U6bGlzdCx0aW1pbmc6bGlzdCxkZXBsb3k6bGlzdCxxanQ6YWRkLHFqdDplZGl0LGRlcGxveUhpc3Rvcnk6ZGVsLG9ubGluZTpvdXQsbWVudTplZGl0LG1lbnU6bGlzdCxzdG9yYWdlOmRlbCxzZXJ2ZXJEZXBsb3k6YWRkLHFqdDpsaXN0LGRhdGFiYXNlOmVkaXQsZGF0YWJhc2U6YWRkLGRpY3Q6ZWRpdCxkZXB0OmRlbCx1c2VyOmxpc3Qsc3RvcmFnZTplZGl0LGFwcDplZGl0LHJvbGVzOmRlbCxhZG1pbixzdG9yYWdlOmxpc3QsbG9nczpsaXN0LHVzZXI6ZGVsLHNlcnZlcjpsaXN0LGRlcGxveTplZGl0LHRpbWluZzphZGQsYXBwOmxpc3Qsam9iOmFkZCxyb2xlczphZGQsdXNlcjphZGQsYXBwOmFkZCx0aW1pbmc6ZWRpdCxvbmxpbmU6ZXhwb3J0LHJvbGVzOmxpc3QsbWVudTphZGQsam9iOmRlbCx1c2VyOmVkaXQscm9sZXM6ZWRpdCxvbmxpbmU6bGlzdCx0aW1pbmc6ZGVsLGRlcGxveTpkZWwscWp0Onpnc3Asc2VydmVyRGVwbG95Omxpc3QiLCJleHAiOjE1OTk3OTI4OTZ9.kcYEbI-cFUrB52zAn-aKFPnNbTduJg5EhZuDKp9JI7-Mne73eqcy_QA7PksuTFs250e5co8yEuRaqZNseYJprg
accept-language = zh-CN,zh;q=0.9
accept-encoding = gzip, deflate, br
referer = http://localhost:8013/system/menu
sec-fetch-dest = empty
sec-fetch-mode = cors
sec-fetch-site = same-origin
user-agent = Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
authorization = Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJkZXB0OmVkaXQsc3RvcmFnZTphZGQsZGVwdDphZGQsbWVudTpkZWwsc2VydmVyRGVwbG95OmVkaXQsbG9nczpleHBvcnQscWp0OmRlbCxxanQ6Ym1zcCxqb2I6ZWRpdCxkZXBsb3lIaXN0b3J5Omxpc3QsZGVwbG95OmFkZCxkaWN0OmFkZCxkZXB0Omxpc3QsYXBwOmRlbCxqb2I6bGlzdCxkYXRhYmFzZTpkZWwsZGljdDpkZWwsZGljdDpsaXN0LHNlcnZlckRlcGxveTpkZWwsZGF0YWJhc2U6bGlzdCx0aW1pbmc6bGlzdCxkZXBsb3k6bGlzdCxxanQ6YWRkLHFqdDplZGl0LGRlcGxveUhpc3Rvcnk6ZGVsLG9ubGluZTpvdXQsbWVudTplZGl0LG1lbnU6bGlzdCxzdG9yYWdlOmRlbCxzZXJ2ZXJEZXBsb3k6YWRkLHFqdDpsaXN0LGRhdGFiYXNlOmVkaXQsZGF0YWJhc2U6YWRkLGRpY3Q6ZWRpdCxkZXB0OmRlbCx1c2VyOmxpc3Qsc3RvcmFnZTplZGl0LGFwcDplZGl0LHJvbGVzOmRlbCxhZG1pbixzdG9yYWdlOmxpc3QsbG9nczpsaXN0LHVzZXI6ZGVsLHNlcnZlcjpsaXN0LGRlcGxveTplZGl0LHRpbWluZzphZGQsYXBwOmxpc3Qsam9iOmFkZCxyb2xlczphZGQsdXNlcjphZGQsYXBwOmFkZCx0aW1pbmc6ZWRpdCxvbmxpbmU6ZXhwb3J0LHJvbGVzOmxpc3QsbWVudTphZGQsam9iOmRlbCx1c2VyOmVkaXQscm9sZXM6ZWRpdCxvbmxpbmU6bGlzdCx0aW1pbmc6ZGVsLGRlcGxveTpkZWwscWp0Onpnc3Asc2VydmVyRGVwbG95Omxpc3QiLCJleHAiOjE1OTk3OTI4OTZ9.kcYEbI-cFUrB52zAn-aKFPnNbTduJg5EhZuDKp9JI7-Mne73eqcy_QA7PksuTFs250e5co8yEuRaqZNseYJprg
accept = application/json, text/plain, /
connection = close
host = localhost:8000

（2）新增模块浏览器控制台请求头：
GET /bgbb/qjt HTTP/1.1
Host: localhost:8013
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Referer: http://localhost:8013/bgbb/qjt
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cookie: rememberMe=true; password=nbcfYOhzN3+8z5vANYFC+atBXXkStoyvNgjCM/aHFXi6p77AcjZq/1eGO54KjkiCXEiI4QAdPOBnTy9F7/83Mw==; username=admin; EL-ADMIN-TOEKN=Bearer%20eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJkZXB0OmVkaXQsc3RvcmFnZTphZGQsZGVwdDphZGQsbWVudTpkZWwsc2VydmVyRGVwbG95OmVkaXQsbG9nczpleHBvcnQscWp0OmRlbCxxanQ6Ym1zcCxqb2I6ZWRpdCxkZXBsb3lIaXN0b3J5Omxpc3QsZGVwbG95OmFkZCxkaWN0OmFkZCxkZXB0Omxpc3QsYXBwOmRlbCxqb2I6bGlzdCxkYXRhYmFzZTpkZWwsZGljdDpkZWwsZGljdDpsaXN0LHNlcnZlckRlcGxveTpkZWwsZGF0YWJhc2U6bGlzdCx0aW1pbmc6bGlzdCxkZXBsb3k6bGlzdCxxanQ6YWRkLHFqdDplZGl0LGRlcGxveUhpc3Rvcnk6ZGVsLG9ubGluZTpvdXQsbWVudTplZGl0LG1lbnU6bGlzdCxzdG9yYWdlOmRlbCxzZXJ2ZXJEZXBsb3k6YWRkLHFqdDpsaXN0LGRhdGFiYXNlOmVkaXQsZGF0YWJhc2U6YWRkLGRpY3Q6ZWRpdCxkZXB0OmRlbCx1c2VyOmxpc3Qsc3RvcmFnZTplZGl0LGFwcDplZGl0LHJvbGVzOmRlbCxhZG1pbixzdG9yYWdlOmxpc3QsbG9nczpsaXN0LHVzZXI6ZGVsLHNlcnZlcjpsaXN0LGRlcGxveTplZGl0LHRpbWluZzphZGQsYXBwOmxpc3Qsam9iOmFkZCxyb2xlczphZGQsdXNlcjphZGQsYXBwOmFkZCx0aW1pbmc6ZWRpdCxvbmxpbmU6ZXhwb3J0LHJvbGVzOmxpc3QsbWVudTphZGQsam9iOmRlbCx1c2VyOmVkaXQscm9sZXM6ZWRpdCxvbmxpbmU6bGlzdCx0aW1pbmc6ZGVsLGRlcGxveTpkZWwscWp0Onpnc3Asc2VydmVyRGVwbG95Omxpc3QiLCJleHAiOjE1OTk3OTI4OTZ9.kcYEbI-cFUrB52zAn-aKFPnNbTduJg5EhZuDKp9JI7-Mne73eqcy_QA7PksuTFs250e5co8yEuRaqZNseYJprg; sidebarStatus=1

----------------------------·idea->tokenFilter请求头：
=== MimeHeaders ===
x-forwarded-host = localhost:8013
x-forwarded-proto = http
x-forwarded-port = 8013
x-forwarded-for = 127.0.0.1
cookie = rememberMe=true; password=nbcfYOhzN3+8z5vANYFC+atBXXkStoyvNgjCM/aHFXi6p77AcjZq/1eGO54KjkiCXEiI4QAdPOBnTy9F7/83Mw==; username=admin; sidebarStatus=1; EL-ADMIN-TOEKN=Bearer%20eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJkZXB0OmVkaXQsc3RvcmFnZTphZGQsZGVwdDphZGQsbWVudTpkZWwsc2VydmVyRGVwbG95OmVkaXQsbG9nczpleHBvcnQscWp0OmRlbCxxanQ6Ym1zcCxqb2I6ZWRpdCxkZXBsb3lIaXN0b3J5Omxpc3QsZGVwbG95OmFkZCxkaWN0OmFkZCxkZXB0Omxpc3QsYXBwOmRlbCxqb2I6bGlzdCxkYXRhYmFzZTpkZWwsZGljdDpkZWwsZGljdDpsaXN0LHNlcnZlckRlcGxveTpkZWwsZGF0YWJhc2U6bGlzdCx0aW1pbmc6bGlzdCxkZXBsb3k6bGlzdCxxanQ6YWRkLHFqdDplZGl0LGRlcGxveUhpc3Rvcnk6ZGVsLG9ubGluZTpvdXQsbWVudTplZGl0LG1lbnU6bGlzdCxzdG9yYWdlOmRlbCxzZXJ2ZXJEZXBsb3k6YWRkLHFqdDpsaXN0LGRhdGFiYXNlOmVkaXQsZGF0YWJhc2U6YWRkLGRpY3Q6ZWRpdCxkZXB0OmRlbCx1c2VyOmxpc3Qsc3RvcmFnZTplZGl0LGFwcDplZGl0LHJvbGVzOmRlbCxhZG1pbixzdG9yYWdlOmxpc3QsbG9nczpsaXN0LHVzZXI6ZGVsLHNlcnZlcjpsaXN0LGRlcGxveTplZGl0LHRpbWluZzphZGQsYXBwOmxpc3Qsam9iOmFkZCxyb2xlczphZGQsdXNlcjphZGQsYXBwOmFkZCx0aW1pbmc6ZWRpdCxvbmxpbmU6ZXhwb3J0LHJvbGVzOmxpc3QsbWVudTphZGQsam9iOmRlbCx1c2VyOmVkaXQscm9sZXM6ZWRpdCxvbmxpbmU6bGlzdCx0aW1pbmc6ZGVsLGRlcGxveTpkZWwscWp0Onpnc3Asc2VydmVyRGVwbG95Omxpc3QiLCJleHAiOjE1OTk3OTI4OTZ9.kcYEbI-cFUrB52zAn-aKFPnNbTduJg5EhZuDKp9JI7-Mne73eqcy_QA7PksuTFs250e5co8yEuRaqZNseYJprg
accept-language = zh-CN,zh;q=0.9
accept-encoding = gzip, deflate, br
referer = http://localhost:8013/bgbb/qjt
sec-fetch-dest = document
sec-fetch-user = ?1
sec-fetch-mode = navigate
sec-fetch-site = same-origin
accept = text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3;q=0.9
user-agent = Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
upgrade-insecure-requests = 1
cache-control = max-age=0
connection = close
host = localhost:8000

**Comment by elunez** [comment]
401 检查授权， 304 正常请求
