### ISSUE TITLE
参照代码生成功能，设置了菜单缓存，但是仍然不能缓存界面，这是bug吗？

### ISSUE THREAD

**Issue by spar025** [elunez/eladmin#490]
版本: v2.5
环境：本地
复现步骤：
       1、编辑菜单，设置菜单缓存为“是”
       2、退出重新登录，点开供应商档案页面，输入查询条件查询出部分记录
       3、再打开其他界面，再切换回“供应商档案”页面，结果是刷新了界面，没有缓存。
日志提供：
       
可选：提供gif或者视频

![image](https://user-images.githubusercontent.com/33474854/93845228-a9c7d980-fcd2-11ea-8423-58e1a7a42a69.png)
![image](https://user-images.githubusercontent.com/33474854/93845456-720d6180-fcd3-11ea-9a80-2d6244a52920.png)
![缓存](https://user-images.githubusercontent.com/33474854/93846587-0dec9c80-fcd7-11ea-992c-4ae93510966b.gif)

**Comment by elunez** [comment]
![image](https://user-images.githubusercontent.com/42142420/93955207-ccfd9200-fd81-11ea-8ecc-00d3deceb9a2.png)

组件名称要与 Vue 中的 name 一致
export default {
  name: '***'
}

**Comment by spar025** [comment]
> ![image](https://user-images.githubusercontent.com/42142420/93955207-ccfd9200-fd81-11ea-8ecc-00d3deceb9a2.png)
> 
> 组件名称要与 Vue 中的 name 一致
> export default {
> name: '***'
> }

是一致的，发现3级菜单不支持，只支持2级菜单，这个3级菜单怎么缓存能给指点一下吗

**Comment by elunez** [comment]
https://github.com/PanJiaChen/vue-element-admin/pull/3116

参考
