### ISSUE TITLE
问一个代码理解的问题，不是bug

### ISSUE THREAD

**Issue by EallanW** [elunez/eladmin#492]
https://github.com/elunez/eladmin/blob/53af24e1ebf9fd77671856a894e569af779824aa/eladmin-system/src/main/java/me/zhengjie/modules/system/service/impl/JobServiceImpl.java#L49

请问这个Service的实现文件里面的下面这些bean是如何被注入的？因为没有看到@Autowired或者@Resource等注解
jobRepository, JobMapper

**Comment by zc150622** [comment]
你可以直接爬了，这不是你该看的项目，去学hello world怎么写吧

**Comment by zc150622** [comment]
> https://github.com/elunez/eladmin/blob/53af24e1ebf9fd77671856a894e569af779824aa/eladmin-system/src/main/java/me/zhengjie/modules/system/service/impl/JobServiceImpl.java#L49
> 
> 请问这个Service的实现文件里面的下面这些bean是如何被注入的？因为没有看到@Autowired或者@resource等注解
> jobRepository, JobMapper

你可以直接爬了，这不是你该看的项目，去学hello world怎么写吧

**Comment by elunez** [comment]
```
用到了注解：@RequiredArgsConstructor
```
