### ISSUE TITLE
未來是否會加入多國語系支援?

### ISSUE THREAD

**Issue by zero123824** [elunez/eladmin#493]
版本: v2.6
环境：本地開發
复现步骤：
日志提供：
![image](https://user-images.githubusercontent.com/34159168/94221510-d6bbfc80-ff1d-11ea-8c9a-b60c0672ed9f.png)
![image](https://user-images.githubusercontent.com/34159168/94221536-e3405500-ff1d-11ea-8573-8178d49ff5a6.png)

你好，在VUEJS前端原模板中有看到一個i18n分支，是支援多國語系切換的選項，主要是在更改頁面模板的語言。
目前菜單的選項都是由SERVER端提供，但是否未來會加入多國語系菜單以及模板的支援呢

**Comment by elunez** [comment]
看时间吧，有时间会完善
