### ISSUE TITLE
部门管理——新增部门不显示

### ISSUE THREAD

**Issue by Funny-Panda** [elunez/eladmin#498]
系统管理下的部门管理，在新增部门时没有显示新增的部门。但是在用户管理上：修改或者新建用户时选择部门会看到新建的部门。

**Comment by Fomovet** [comment]
在角色管理栏目里面，把管理员的数据范围设置“全部”即可

**Comment by Funny-Panda** [comment]
> 在角色管理栏目里面，把管理员的数据范围设置“全部”即可

已解决，感谢！
