### ISSUE TITLE
Cannot invoke "javax.script.ScriptEngine.eval(String)" because "engine" is null

### ISSUE THREAD

**Issue by whenjs** [elunez/eladmin#502]
Cannot invoke "javax.script.ScriptEngine.eval(String)" because "engine" is null
![image](https://user-images.githubusercontent.com/36758141/95036197-bd733700-06f9-11eb-9eba-73133829dd76.png)

**Comment by reinmind** [comment]
换个1.8的jdk试试，不要问我为什么知道的，因为我用jdk15搞了一晚上

**Comment by zqk666** [comment]
> Maybe you should try jdk1.8 runtime instead.
> 不要问我为什么知道的,因为我搞了一晚上

请问要怎么操作，我也是这里出了问题
