### ISSUE TITLE
菜单新增按钮 角色分配 列表 未更新

### ISSUE THREAD

**Issue by TomYule** [elunez/eladmin#503]
版本: v2.5
环境：本地/线上
复现步骤：
日志提供：
可选：提供gif或者视频

菜单新增按钮 角色分配 列表 未更新

菜单如下权限
![image](https://user-images.githubusercontent.com/13266764/95567693-e4ad6980-0a55-11eb-8515-0e79033c49b7.png)

![image](https://user-images.githubusercontent.com/13266764/95567748-f4c54900-0a55-11eb-8461-082d1b62ce7b.png)
重启也无效

**Comment by elunez** [comment]
建议参考 2.6 修改
