### ISSUE TITLE
权限分配 树形菜单勾选根目录 不会勾选子目录

### ISSUE THREAD

**Issue by TomYule** [elunez/eladmin#505]
权限分配 树形菜单勾选根目录 不会勾选子目录
建议参考 如下 修改
https://vuejsexamples.com/a-tree-shaped-shuttle-box-assembly-based-on-vue-and-element-ui/
版本: v2.5
环境：本地/线上
复现步骤：
日志提供：
可选：提供gif或者视频

**Comment by elunez** [comment]
看最新提交的代码

https://github.com/elunez/eladmin/commit/0c6ad747ddc10fc7f2d25737c837b44cd1c67833
