### ISSUE TITLE
头像404

### ISSUE THREAD

**Issue by YuanAaron** [elunez/eladmin#507]
头像显示不出来，右键检查发现请求为 'http://localhost:8000/avatar/avatar-20200806032259161.png'，直接访问该url返回404

**Comment by elunez** [comment]
> 头像显示不出来，右键检查发现请求为 '[http://localhost:8000/avatar/avatar-20200806032259161.png'，直接访问该url返回404](http://localhost:8000/avatar/avatar-20200806032259161.png'%EF%BC%8C%E7%9B%B4%E6%8E%A5%E8%AE%BF%E9%97%AE%E8%AF%A5url%E8%BF%94%E5%9B%9E404)

重新修改头像即可，这个头像文件存在我的电脑上，在你们电脑上因此404

**Comment by YuanAaron** [comment]
好的，谢谢
