### ISSUE TITLE
TagsView打印功能报错

### ISSUE THREAD

**Issue by zhaoxxnbsp** [elunez/eladmin#509]
- 版本: v2.4

- 环境：本地

- 复现步骤：

- 日志提供：

右键选择打印：
![image](https://user-images.githubusercontent.com/40030965/96358151-8f004d80-1136-11eb-8fde-7ad48d4a05f6.png)
点击打印后，控制台报错：
![image](https://user-images.githubusercontent.com/40030965/96358180-ce2e9e80-1136-11eb-994e-681360314107.png)

**Comment by elunez** [comment]
所有版本均为提供 TagsView 的打印和导出图片功能，请自行修改
![image](https://user-images.githubusercontent.com/42142420/96426053-4f695c80-122f-11eb-84c4-c4edb9c5b731.png)
