### ISSUE TITLE
eladmin-qt 前端 公共组件TreeTable报错

### ISSUE THREAD

**Issue by Thinkson94** [elunez/eladmin#51]
eladmin作者，你好。本人在使用eladmin时发现，前端公共组件**TreeTable**报错，提示缺少row-key,如下：
![000](https://user-images.githubusercontent.com/38271738/57373907-23d5ec00-71cc-11e9-9be5-5720bf75d396.png)

在TreeTable的index.vue中的el-table加上` row-key="id"`，报错如下：
![002](https://user-images.githubusercontent.com/38271738/57373918-2c2e2700-71cc-11e9-8780-0700c0925c22.png)

综上，初步怀疑是TreeTable的eval.js处理数据不恰当，希望作者能抽空验证我的猜疑是否正确，并予以回复，感谢！

**Comment by elunez** [comment]
在package.json中将 element-ui版本改为 2.4.6试试，高版本的 element-ui 不兼容

**Comment by Thinkson94** [comment]
> 在package.json中将 element-ui版本改为 2.4.6试试，高版本的 element-ui 不兼容

换成低版本，就没提示了，谢谢！
