### ISSUE TITLE
发送邮件bug

### ISSUE THREAD

**Issue by DengSinkiang** [elunez/eladmin#52]
假如我第一次配置正确之后，发送邮件成功。然后无论怎么修改配置，依然发送成功。
假如我第一次配置不正确，发送邮件不成功。然后无论怎么修改配置，依然发送失败。

**Comment by elunez** [comment]
修改这三个的update方法
![image](https://user-images.githubusercontent.com/42142420/57496582-63085800-7306-11e9-807f-d27c4baf9835.png) 将缓存注解换成@CacheEvict(allEntries = true)
![image](https://user-images.githubusercontent.com/42142420/57496603-7a474580-7306-11e9-8524-e3150b10e51e.png)

**Comment by elunez** [comment]
发现不是缓存的问题，把缓存注解注释掉也存在问题， 现在还没定位到问题所在

**Comment by elunez** [comment]
``` java
try {
            Mail.create(account)
                    .setTos(String.valueOf(emailVo.getTos()))
                    .setTitle(emailVo.getSubject())
                    .setContent(content)
                    .setHtml(true)
                    .setUseGlobalSession(false)//关闭session
                    .send();
        }catch (Exception e){
            throw new BadRequestException(e.getMessage());
        }
```
