### ISSUE TITLE
[介绍项目的功能一个错别字]  定位排错吧

### ISSUE THREAD

**Issue by guangquan123** [elunez/eladmin#523]
![image](https://user-images.githubusercontent.com/44352044/98523124-81ab2e80-22b0-11eb-82ca-62551c30574f.png)

地址：https://el-admin.vip/guide/kslj.html#%E4%B8%BB%E8%A6%81%E5%8A%9F%E8%83%BD

**Comment by elunez** [comment]
已修改

**Comment by guangquan123** [comment]
大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "elunez/eladmin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月9日(星期一) 晚上8:10
收件人:&nbsp;"elunez/eladmin"<eladmin@noreply.github.com&gt;;
抄送:&nbsp;"缘莱瑷倪口口"<644832921@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [elunez/eladmin] [介绍项目的功能一个错别字]  定位排错吧 (#523)





 
已修改
