### ISSUE TITLE
项目部署报错Colutil.java找不到org.apache.commons.lang.exception.NestableException的类文件

### ISSUE THREAD

**Issue by 18519206524** [elunez/eladmin#528]
eladmin-gengerator模块中的ColUtil.java

\eladmin\eladmin-generator\src\main\java\me\zhengjie\utils\ColUtil.java
Error:(47, 9) java: 无法访问org.apache.commons.lang.exception.NestableException
  找不到org.apache.commons.lang.exception.NestableException的类文件

**Comment by elunez** [comment]
https://blog.csdn.net/vtopqx/article/details/50129905
