### ISSUE TITLE
sys_roles_depts  表，多了一条记录，导致 部门 **华北分部》测试部**  的删除失败

### ISSUE THREAD

**Issue by ZhangErling** [elunez/eladmin#532]
版本：2.6
![image](https://user-images.githubusercontent.com/45256786/99956142-7b44a880-2dc0-11eb-956b-920cd478a0c9.png)

在用户管理中点击**测试部门**，并不能显示该条记录
![image](https://user-images.githubusercontent.com/45256786/99956650-56046a00-2dc1-11eb-97bb-cd2e61b59322.png)

在部门管理中无法删除**测试部门**
![image](https://user-images.githubusercontent.com/45256786/99956700-6ae0fd80-2dc1-11eb-990a-a60fc1d83591.png)

![image](https://user-images.githubusercontent.com/45256786/99956954-dc20b080-2dc1-11eb-8b92-41497ee2e3f0.png)

请及时更新SQL文件

感谢分享！

**Comment by elunez** [comment]
> 版本：2.6
> ![image](https://user-images.githubusercontent.com/45256786/99956142-7b44a880-2dc0-11eb-956b-920cd478a0c9.png)
> 
> 在用户管理中点击**测试部门**，并不能显示该条记录
> ![image](https://user-images.githubusercontent.com/45256786/99956650-56046a00-2dc1-11eb-97bb-cd2e61b59322.png)
> 
> 在部门管理中无法删除**测试部门**
> ![image](https://user-images.githubusercontent.com/45256786/99956700-6ae0fd80-2dc1-11eb-990a-a60fc1d83591.png)
> 
> ![image](https://user-images.githubusercontent.com/45256786/99956954-dc20b080-2dc1-11eb-8b92-41497ee2e3f0.png)
> 
> 请及时更新SQL文件
> 
> 感谢分享！

角色 普通用户 的数据权限是自定义，并且关联的是 测试部，你需要将关联关系解除掉就行

![image](https://user-images.githubusercontent.com/42142420/100346040-2dc57700-301e-11eb-9145-dd4fdee79897.png)
