### ISSUE TITLE
swagger 404

### ISSUE THREAD

**Issue by GisDeng** [elunez/eladmin#535]
我想直接在浏览器访问swagger，需要怎么设置：http://localhost:8080/swagger-ui.html
以下配置均无效，直接访问http://localhost:8080/swagger-ui.html返回404
`@Configuration
public class WebMVCConfig extends WebMvcConfigurerAdapter {
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/swagger-ui.html")
                .addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("/webjars/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");

    }
}`

` // swagger 文档
                .antMatchers("/swagger-ui.html").permitAll()
                .antMatchers("/swagger-resources").permitAll()
                .antMatchers("/swagger-resources/**").permitAll()
                .antMatchers("/configuration/ui").permitAll()
                .antMatchers("/configuration/security").permitAll()
                .antMatchers("/webjars/**").permitAll()
                .antMatchers("/*/api-docs").permitAll()
                .antMatchers("/v2/**").permitAll()`

**Comment by elunez** [comment]
swagger 地址 ：ip/域名:端口/swagger-ui.html
