### ISSUE TITLE
Downloading dependencies takes 2 days

### ISSUE THREAD

**Issue by heliosnarcissus** [elunez/eladmin#537]
downloading Maven dependencies of this projects takes 2 days. Why is that ? My IDE freezes and hangs.

**Comment by heliosnarcissus** [comment]
my macbook freezes and force restarts, hangs. 
is there malware in this maven dependencies?

**Comment by heliosnarcissus** [comment]
when I commented this section out, my IDE started working normally again:

**Comment by 1661973574** [comment]
where are you from?Can we make friends?

**Comment by elunez** [comment]
> 下载此项目的Maven依赖项需要2天。这是为什么 ？我的IDE冻结并挂起。

The mirror warehouse in China is used by default, if you are not in China, you need to comment it out
