### ISSUE TITLE
菜单权限无效

### ISSUE THREAD

**Issue by Ahern-Lee** [elunez/eladmin#547]
1.仿照代码生成的预览跳页，新建一个菜单，设置为不可见，加上按钮权限并授权
2.在页面操作列上加一个按钮用来跳转，加上权限访问
3.该用户已有该权限但是该按钮不显示，
4.按钮权限校验去掉后显示正常

**Comment by elunez** [comment]
按钮中使用 v-permission= "['test']" 并无问题

如果有异议，可以提供下代码
