### ISSUE TITLE
登录接口中返回了password字段

### ISSUE THREAD

**Issue by aexiaosong** [elunez/eladmin#548]
版本2.6
在登录接口中返回了用户在数据库中的加密密码，这样好吗
![image](https://user-images.githubusercontent.com/46281012/102686372-4e9a7a00-4222-11eb-9382-0b4e46b3960b.png)

虽然在返回的JwtUserDto中添加了@JsonIgnore注解但是还是返回了password字段

**Comment by elunez** [comment]
是因为现在默认使用 fastjson 序列化，导致 @JsonIgnore 失效，使用 @JSONField(serialize = false) 替换即可
