### ISSUE TITLE
http://localhost:8013/login打开报错，验证码不显示问题

### ISSUE THREAD

**Issue by saminlu** [elunez/eladmin#555]
版本: v2.6
环境：本地JDK15
复现步骤：npm run dev后打开http://localhost:8013/，跳转到登录页面，
右上角出现弹层报错，验证码也不显示

日志提供：弹层显示 Cannot invoke "javax.script.ScriptEngine.eval(String)" because "engine" is null
console.log显示
xhr.js:160 GET http://localhost:8013/auth/code 400 (Bad Request)
request.js:78 400
createError.js:16 Uncaught (in promise) Error: Request failed with status code 400
    at createError (createError.js:16)
    at settle (settle.js:18)
    at XMLHttpRequest.handleLoad (xhr.js:59)
可选：
![js-error](https://user-images.githubusercontent.com/6028083/103397152-fcd2e780-4b71-11eb-9612-ea6e8a5db031.png)
![console-log](https://user-images.githubusercontent.com/6028083/103397158-00666e80-4b72-11eb-860c-204d0d7dec22.png)

**Comment by 4466** [comment]
兄弟，你得问题决解了吗？我也遇到这个问题了

**Comment by achunCoding** [comment]
请问解决了吗，是不是JDK 版本的问题，我这边JDK8时是可以正常运行的

**Comment by 4466** [comment]
> 请问解决了吗，是不是JDK 版本的问题，我这边JDK8时是可以正常运行的

我这边跟楼主一样，JDK最新的15，就是没法运行哦，有时候打开测试站el-admin.xin验证码也是没法加载，不知道怎么回事。

**Comment by qianyin11** [comment]
就是JDK版本的问题,我跑JDK15也是这个问题,我改成JDK1.8就好了

**Comment by saminlu** [comment]
> 兄弟，你得问题决解了吗？我也遇到这个问题了



> 就是JDK版本的问题,我跑JDK15也是这个问题,我改成JDK1.8就好了

那我换成1.8的试试了

**Comment by saminlu** [comment]
@achunCoding @4466 @qianyin11 
`java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)`
我的java版本已改成这个，请问还有操作哪里吗？比如有啥缓存之类的，我打开idea重新运行还是一样的错误弹出

**Comment by qianyin11** [comment]
![image](https://user-images.githubusercontent.com/22315781/104562177-fb7de080-5682-11eb-8602-20d7dcea11fa.png)
runner跑的环境是1.8么，要修改runner的环境的

**Comment by 4466** [comment]
> @achunCoding @4466 @qianyin11
> `java -version java version "1.8.0_181" Java(TM) SE Runtime Environment (build 1.8.0_181-b13) Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)`
> 我的java版本已改成这个，请问还有操作哪里吗？比如有啥缓存之类的，我打开idea重新运行还是一样的错误弹出

我把JDK15卸载了，重新安装了JDK8(1.8.0)，连接下Redis，跑起来就没有问题了，idea没有报错哈，不过JDK8的JVM可能太老了吧，虽然用Idea运行没问题，但是安装eclipse就是提示JVM不行，得下载其他JDK版本的JRE，可能是JDK8太老了，和新版的eclipse不匹配吧，不知道你是不是这个问题。

**Comment by saminlu** [comment]
@qianyin11 已配置run configurations 为1.8，问题已解决，验证码已出来，谢谢
