### ISSUE TITLE
懒加载为何无效？

### ISSUE THREAD

**Issue by EmKs** [elunez/eladmin#558]
@OneToMany 默认不是懒加载么？但是项目中使用@OneToMany注解，没有懒加载，直接全部被加载出来了，就算加上fetch=FetchType.LAZY也没有效果，而发现system模块中DictDetail使用@ManyToOne(fetch=FetchType.LAZY)却可以？是需要配置哪些地方吗？

**Comment by elunez** [comment]
懒加载并无失效，不需要修改其他地方
