### ISSUE TITLE
日期控件点击无效问题

### ISSUE THREAD

**Issue by QuanJinWuSheng** [elunez/eladmin#560]
![image](https://user-images.githubusercontent.com/17725652/103876569-c287be00-510e-11eb-9cab-d774cb2246bc.png)
在点击日期选择红框勾选的那些按钮时会有异常，导致勾选无效

**Comment by QuanJinWuSheng** [comment]
图片上传失败，也就是点击【往前一天，往后一天，往前一周，往后一周】

**Comment by qianyin11** [comment]
![image](https://user-images.githubusercontent.com/22315781/104557545-5fe97180-567c-11eb-9750-a7c7893e36f3.png)
将picker.value.length===0的判断改为picker.value===undefined
![image](https://user-images.githubusercontent.com/22315781/104557654-94f5c400-567c-11eb-887c-c3118c027db5.png)
将picker.value.length>0的判断改为是否存在
