### ISSUE TITLE
角色菜单保存的时候报错

### ISSUE THREAD

**Issue by 13196789316** [elunez/eladmin#564]
出现了一个错误：角色菜单保存的时候报错，org.hibernate.HibernateException: Found shared references to a collection: me.zhengjie.modules.system.domain.Role.depts。一开始是正常的，添加了一些菜单以后，就不能保存自己所处角色的角色菜单了，比如admin可以改别人的，改自己的就不行。切换到跟admin一样数据权限到账号，修改admin角色的菜单是可以的，改自己的也不行

**Comment by elunez** [comment]
能提供下视频吗，或者 gif 吗

**Comment by elunez** [comment]
能提供下视频吗，或者 gif 吗
