### ISSUE TITLE
请求方法凡是加有@Log("***")注解的，请求返回都比较慢（Mac本地环境）

### ISSUE THREAD

**Issue by qianyin11** [elunez/eladmin#569]
1. 版本：v2.6
2. 环境：
- 本地运行，
- macbook pro(i7+16G)
- Jdk 1.8 + Maven 3.6.3 + Mysql 8.0

3. 复现步骤：

- 登录成功后，以删除一个已创建的部门为例, 按照现有代码运行，整个请求需要5s钟左右才能返回。  
![image](https://user-images.githubusercontent.com/22315781/104556680-fd43a600-567a-11eb-8ddb-26a125b24f7a.png)

- 注释掉Deptcontroller中delete方法的注解后，再重新启动运行，整个请求只需要100ms左右就返回了
![image](https://user-images.githubusercontent.com/22315781/104556814-2d8b4480-567b-11eb-84bf-a6138b838fe6.png)
![image](https://user-images.githubusercontent.com/22315781/104556892-4dbb0380-567b-11eb-93f4-4e61e850090a.png)

4. 日志提供：只有一条insert sys_log的sql语句，已手动在mysql中执行过，很快。

**Comment by abcdelf** [comment]
这个是估计因为环切 计算耗时以及做日志保存导致的

**Comment by elunez** [comment]
日志这块可以自行修改为 elk 方式
