### ISSUE TITLE
配置属性读不正确，只能到第一层，第二层就是不生效

### ISSUE THREAD

**Issue by xzm1102207843** [elunez/eladmin#570]
![微信截图_20210115133357](https://user-images.githubusercontent.com/16155051/104685937-245fad80-5737-11eb-94d4-c6ca296332de.png)

**Comment by xzm1102207843** [comment]
版本: v2.6 最新版    
环境：本地/线上
复现步骤：在测试类读取配置
日志提供：读不到正确的属性配置

**Comment by Ryyyc** [comment]
![ok](https://user-images.githubusercontent.com/47767371/106580834-27eb9500-657d-11eb-8e1c-a6f5849d9512.png)

这边测试没问题。需要确认：
1. 配置文件被激活
2. 注入的字段不能是静态字段

看你的情况，我猜测你的 application.yml 配置  spring.profiles.active=dev, prod
然后 application-prod.yml 配置 login.login-code.heigth=36
prod 写在了后面，所以注入的 heigth 的最新值是 36，即使 dev 里面是 368

顺便疑惑一句 @elunez  ，为什么 是 heigth 不是 height ？

**Comment by xzm1102207843** [comment]
ok
