### ISSUE TITLE
侧边栏显示异常

### ISSUE THREAD

**Issue by jingshanccc** [elunez/eladmin#576]
版本: v2.6
环境：线上
复现步骤：添加一个/多个隐藏菜单（hidden为true）在一个没有子菜单的菜单下，侧边栏将显示为可展开状态但由于其子菜单皆为hidden，因此无法展开。
![1611401116296](https://user-images.githubusercontent.com/46669573/105576874-d723b180-5db0-11eb-9c5b-5dfcc0cbbe72.gif)

**Comment by elunez** [comment]
这种细节，暂不考虑修复，没太大意义
