### ISSUE TITLE
生成的id长度为17位后，查询到的id在删除和修改接口自动变化导致删除修改不成功

### ISSUE THREAD

**Issue by Pwoodong** [elunez/eladmin#578]
查询接口返回id值截图：
![image](https://user-images.githubusercontent.com/14190489/105627369-917aed80-5e71-11eb-9624-ca96c9c609bf.png)

删除接口值：
![image](https://user-images.githubusercontent.com/14190489/105627427-eae31c80-5e71-11eb-8c4d-223659ef9be1.png)

**Comment by elunez** [comment]
参数返回的时候序列化成字符串即可
