### ISSUE TITLE
vuex状态刷新重置

### ISSUE THREAD

**Issue by lrt890424** [elunez/eladmin#591]
版本: v2.6
环境：本地&线上
复现步骤：布局设置完成后f5刷新后，设置的布局消失。
FIX：本地使用了vuex-persistedstate （https://github.com/robinvdvleuten/vuex-persistedstate），来解决，并且用的是模块化配置，只持久化一部分状态。

**Comment by elunez** [comment]
这块就不改动了，可自行实现，或者实现后提个 PR， 哈哈
