### ISSUE TITLE
代码生成器 生成前端页面错误

### ISSUE THREAD

**Issue by claymorz** [elunez/eladmin#597]
当使用代码生成器生成前端代码后，index.vue中会使用checkPer 方法，但此方法不存在，导致页面加载报错
我重新试了下，如果把生成的代码放进eladmin-system等项目自带模块下面是没有问题的，但如果把生成的代码放进自己新建立的模块下就会有上述问题

**Comment by elunez** [comment]
可以全局注册该方法，或者在指定 vue 中引入

import checkPer from '@/utils/permission'
