### ISSUE TITLE
当使用数据字典后，表格显示与搜索条件不一致

### ISSUE THREAD

**Issue by claymorz** [elunez/eladmin#598]
![QQ截图20210219105554](https://user-images.githubusercontent.com/20301060/108451018-1276aa80-72a1-11eb-8643-5eac8a8ccd1f.png)
我使用了数据字典，将性别 男/ 女 映射为了数值1，2
当使用代码生成器生成相关代码后，性别搜索条件 设置为男时，不能搜索男性员工；只有将搜索条件设置为1时，方可完成搜索，不知道作者能否改进此处，多谢多谢

**Comment by elunez** [comment]
使用下拉的方式搜索就行了，查询这块需要自己修改下
