### ISSUE TITLE
是否考虑增加一些功能

### ISSUE THREAD

**Issue by tuchief** [elunez/eladmin#6]
很棒，现有功能作为管理平台的脚手架已经涵盖了基本功能

是否考虑增加下如下功能：

1、没有给任何权限的菜单是否可以隐藏掉
因为既然不给某菜单的任何权限，那么菜单树上觉得也没有必要看见菜单了；

2、消息通知
例如系统运行中发生了异常，可以发生站内通知，也可以同时发送管理员邮箱；

3、用户在线状态，可踢下线
在用户管理列表中，支持查看用户在线状态，在线的用户，管理员或者有权限的用户可以强制下线；

以上，不知是否合理？

**Comment by elunez** [comment]
控制菜单的显示与隐藏是角色决定的和权限没有关系
消息通知与站内信以后会加上
在线用户管理暂时不考虑
