### ISSUE TITLE
提个建议，关于代码生成部分ftl写死问题

### ISSUE THREAD

**Issue by newbie-tan** [elunez/eladmin#60]
代码生成部分应该允许使用者数据库主键命名不为id，可以允许使用如：orderId之类的作为主键名.
个人建议解决方法，将ftl中固定的getId()生成改成类似与get${primaryKey}之类

**Comment by newbie-tan** [comment]
from tony-tan

**Comment by newbie-tan** [comment]
还有个问题，在Repository.tfl用到了pkColumnType这个引用，但是在service及seviceImpl是将数据类型写死为Long，其实会导致如Long-Integer的强转问题

**Comment by elunez** [comment]
已修复bug
