### ISSUE TITLE
集群环境下定时任务

### ISSUE THREAD

**Issue by Lsx1131188021** [elunez/eladmin#600]
> 作者好，团队初期选型使用该项目工程作为基础。慢慢业务积累，有一些定时任务需求，试用了一下框架提供的定时任务功能，提一些功能改进的建议。现在基本部署都是集群环境，单点执行的需求目前无法满足。

> 不是伸手党，只是觉得这种要求还是有一些使用场景的，可以考虑加进去。``

**Comment by yangl1025** [comment]
quarz本身应该支持集群环境部署的啊，我试过，两台机器一个定时任务，只有一台机器执行。

**Comment by Lsx1131188021** [comment]
感谢回复~


quartz的集群支持，需要数据库创建一套quartz的表吧，目前的quartz基础2张表的情况下，我测试应该是不支持的。

你说的也对，用quartz本身的能力支撑。我们这边的领导不想拖一套表，看中就是简单方便，所以我基于目前2张表的配置，用redis分布式锁的方式，做了集群单点任务。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yangl1025"<notifications@github.com&gt;; 
发送时间: 2021年3月4日(星期四) 上午10:42
收件人: "elunez/eladmin"<eladmin@noreply.github.com&gt;; 
抄送: "﹏ゞ星,语丶"<1131188021@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [elunez/eladmin] 集群环境下定时任务 (#600)





 
quarz本身应该支持集群环境部署的啊，我试过，两台机器一个定时任务，只有一台机器执行。
