### ISSUE TITLE
关于外键功能改进的建议

### ISSUE THREAD

**Issue by coder-free** [elunez/eladmin#601]
- 版本:   v2.6

例如我现在有两个表如下：

表1:
--
| 性别ID  |  性别 |
| ----  |  ----  |
| 1 | 男 |
| 2 | 女 |

表2:
--
| 用户ID  |  姓名 | 性别ID | 
| ----  |  ----  |  ----  |
| 1 | 张三 | 1 | 
| 2 | 李四 | 2 | 

---
```diff
- 现在获取的用户列表结果和表2是一致的。但是实际使用时外键字段应该显示成外键对应的表里某个合理的字段。
```
---

期望结果:
--
| 用户ID  |  姓名 | 性别 | 
| ----  |  ----  |  ----  |
| 1 | 张三 | 男 | 
| 2 | 李四 | 女 | 

我想，要达到这个效果，所需的工作量应该不算小，但是真的有用。现在维护数据的人员在使用时需要不停的去看所需的数据对应的ID值到底是多少。

直接解决工作量太大的话，也可以有个折中的方案。就是现在系统附带的字典功能需要扩展一下，现在的字典是从后台手动填入的，可以允许维护人员在自己的数据库表里面选择一个表作为字典。需要在表里选出两个字段作为字典的ID值和描述值。可能需要不时的去数据库更新该字典的数据。

**Comment by elunez** [comment]
暂不考虑
