### ISSUE TITLE
如果设置跟B2B2C似的呢，平台开通多个商户，每个商户都是单独的系统

### ISSUE THREAD

**Issue by Hiram-Y** [elunez/eladmin#632]

**Comment by tsln1998** [comment]
自己重构权限管理那块吧，可以参考我的fork

**Comment by Hiram-Y** [comment]
哪个分支下的？

**Comment by tsln1998** [comment]
master

**Comment by huangxiaoyu** [comment]
这都1年了 你项目咋样了?弄好了么?我也在用这个做个多商户的.准备在用户中加入商户标识.业务数据都跟商户标识挂钩.我看在common包下的SecurityUtils类可以拿到当前登录用户的信息.这样就能取到商户标识读写数据了.
