### ISSUE TITLE
与企业微信加密冲突

### ISSUE THREAD

**Issue by magicLk** [elunez/eladmin#638]
用户登录密码加密是用的commons-codec1.1.3，企业微信推荐使用的是commons-codec 1.8/1.9，使用1.13会报错Last encoded character (before the paddings if any) is a valid base 64 alphabet but not a possible value，请问有什么解决方案么？

**Comment by magicLk** [comment]
我是新建的wc 模块，在新模块pom中导入的commons-codec 1.9包

**Comment by elunez** [comment]
通过 `mvn dependency:tree` 可以查看到 `commons-codec` 出现的地方。找到对应依赖排除掉
如：
```
<dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.17</version>
            <exclusions>
                <exclusion>
                    <artifactId>commons-codec</artifactId>
                    <groupId>commons-codec</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```
单独引入 commons-codec 1.8/1.9
