### ISSUE TITLE
新增加一种登录方式，自定义了一个AuthenticationProvider，结果用authenticationManagerBuilder.getObject()总是返回DaoAuthenticationProvider

### ISSUE THREAD

**Issue by chengjiansheng** [elunez/eladmin#639]
【版本】:  v2.6
【环节】：开发
【复现步骤】：
新增一种登录方式（手机号）
1、自定义一个AuthenticationProvider和AbstractAuthenticationToken；
2、在me.zhengjie.modules.security.rest.AuthorizationController中新增一个方法，用于处理手机号登录请求；
3、用postman模拟登录请求

结果每次走到authenticationManagerBuilder.getObject().authenticate()的时候，通过authenticationManagerBuilder.getObject()得到的永远是DaoAuthenticationProvider，而不是我自己定义的那个AuthenticationProvider，这样就没发正确的认证了

`@AnonymousPostMapping(value = "/smsLogin")
    public ResponseEntity<Object> smsLogin(@Validated @RequestBody AuthSmsDto authUser, HttpServletRequest request) throws Exception {
        // 查询验证码
        String code = (String) redisUtils.get(authUser.getUuid());
        // 清除验证码
        redisUtils.del(authUser.getUuid());
        if (StringUtils.isBlank(code)) {
            throw new BadRequestException("验证码不存在或已过期");
        }
        if (StringUtils.isBlank(authUser.getCode()) || !authUser.getCode().equalsIgnoreCase(code)) {
            throw new BadRequestException("验证码错误");
        }
        SmsCodeAuthenticationToken authenticationToken = new SmsCodeAuthenticationToken(authUser.getMobile());
        Authentication authentication = authenticationManagerBuilder.getObject().authenticate(authenticationToken);
        SecurityContextHolder.getContext().setAuthentication(authentication);
        String token = tokenProvider.createToken(authentication);
        final JwtUserDto jwtUserDto = (JwtUserDto) authentication.getPrincipal();
        // 保存在线信息
        onlineUserService.save(jwtUserDto, token, request);
        // 返回 token 与 用户信息
        Map<String, Object> authInfo = new HashMap<String, Object>(2) {{
            put("token", properties.getTokenStartWith() + token);
            put("user", jwtUserDto);
        }};
        if (loginProperties.isSingleLogin()) {
            //踢掉之前已经登录的token
            onlineUserService.checkLoginOnUser(jwtUserDto.getUsername(), token);
        }
        return ResponseEntity.ok(authInfo);
    }`

**Comment by miaoyinjun** [comment]
1. 在security配置中增加以下代码
` @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) {
        auth.authenticationProvider(smsCodeAuthenticationProvider());
        auth.authenticationProvider(usernamePasswordAuthenticationProvider());
    }

    /**
     * <p>
     * 短信登录
     * </p>
     *
     * @return 短信
     */
    @Bean("smsCodeAuthenticationProvider")
    SmsCodeAuthenticationProvider smsCodeAuthenticationProvider() {
        SmsCodeAuthenticationProvider smsCodeAuthenticationProvider = new SmsCodeAuthenticationProvider();
        smsCodeAuthenticationProvider.setUserDetailsService(smsUserDetailsService);
        return smsCodeAuthenticationProvider;
    }

    /**
     * <p>
     * 密码登录
     * </p>
     *
     * @return 密码
     */
    @Bean("usernamePasswordAuthenticationProvider")
    DaoAuthenticationProvider usernamePasswordAuthenticationProvider() {
        DaoAuthenticationProvider usernamePasswordAuthenticationProvider = new DaoAuthenticationProvider();
        usernamePasswordAuthenticationProvider.setUserDetailsService(userDetailsService);
        usernamePasswordAuthenticationProvider.setPasswordEncoder(passwordEncoder());
        usernamePasswordAuthenticationProvider.setHideUserNotFoundExceptions(false);
        return usernamePasswordAuthenticationProvider;
    }`

2. 由于这里提供了2个不同的UserDetailsService，   @@SecurityUtils.getCurrentUser()方法报错发现了2个UserDetailsService异常，这里做了以下优化，但这里会有另一个问题当userDetailsService的jwt的缓存失效时会出现用手机号查找username字段，或用username查找手机号字段，临时解决方案是jwt的缓存时长修改为远远大于token的缓存时长，希望作者@elunez可以提供更优方案。


`    /**
     * 获取当前登录的用户
     *
     * @return UserDetails
     */
    public static UserDetails getCurrentUser() {
        final Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication == null) {
            throw new AuthenticationBadRequestException("当前登录状态过期");
        }
        if (authentication.getPrincipal() instanceof UserDetails) {
            UserDetails userDetails = (UserDetails) authentication.getPrincipal();
            Map<String, UserDetailsService> userDetailsServiceMap = SpringUtil.getBeansOfType(UserDetailsService.class);
            String[] userDetailsServiceArray = SpringUtil.getBeanNamesForType(UserDetailsService.class);
            if (MapUtil.isNotEmpty(userDetailsServiceMap) && ArrayUtil.isNotEmpty(userDetailsServiceArray)) {
                UserDetailsService userDetailsService = userDetailsServiceMap.get(userDetailsServiceArray[0]);
                return userDetailsService.loadUserByUsername(userDetails.getUsername());
            }
        }
        throw new AuthenticationBadRequestException("找不到当前登录的信息");
    }`
