### ISSUE TITLE
代码生成器优化建议收集

### ISSUE THREAD

**Issue by elunez** [elunez/eladmin#64]
目前优化了三处
1. 主键未设置自增的情况下默认采用Snowflake生成主键ID（原版本必须在数据库中设置自增主键）
2. 主键为字符串的情况下默认采用UUID生成主键ID（原版本只能设置整形主键）
3. 完善代码生成后前后端的权限控制，权限名默认采用实体类名大小加操作类型，如Test类：'TEST_CREATE'
（原版本前后端默认只给了ADMIN权限 @PreAuthorize("hasAnyRole('ADMIN')")）

大家可以在评论说说建议

**Comment by big24** [comment]
l think you say is good




网易邮箱
在2019年05月21日 14:22，elunez 写道：

目前优化了三处

主键未设置自增的情况下默认采用Snowflake生成主键ID（原版本必须在数据库中设置自增主键）
主键为字符串的情况下默认采用UUID生成主键ID（原版本只能设置整形主键）
完善代码生成后前后端的权限控制，权限名默认采用实体类名大小加操作类型，如Test类：'TEST_CREATE'
（原版本前后端默认只给了ADMIN权限 @PreAuthorize("hasAnyRole('ADMIN')")）

大家可以在评论说说建议

**Comment by elunez** [comment]
完善前端表单验证，根据非空字段自动生成表单验证代码（原版本前端没有表单验证）

**Comment by tomray318** [comment]
建议如果表是ss_unit的话，生成的代码类名可以是unit开头的。可以加个这个功能吗？

**Comment by elunez** [comment]
> 建议如果表是ss_unit的话，生成的代码类名可以是unit开头的。可以加个这个功能吗？

可以
