### ISSUE TITLE
富文本编辑框层级高覆盖标签页栏右键菜单

### ISSUE THREAD

**Issue by FanLucifer** [elunez/eladmin#645]
1. 版本: v2.6.0
2. 环境：线上 https://el-admin.xin/components/tinymce
3. 复现步骤：

- 打开多个标签页
- 打开组件->文本标签页
- 右键点击最后一个标签页
![image](https://user-images.githubusercontent.com/49272970/121990313-24400880-cdd0-11eb-9aff-63bbddbd9e8f.png)

**Comment by elunez** [comment]
修改 z-index 即可
