### ISSUE TITLE
Tree 先勾选后取消，按钮仍可操作

### ISSUE THREAD

**Issue by hiddenlong** [elunez/eladmin#648]
版本: 未知
环境：演示地址：https://el-admin.xin/system/menu
复现步骤：
1、先点打开“系统管理”，加载出子菜单；
2、勾选父菜单“系统管理”，子菜单为全部选中状态；
3、取消父菜单选中，子菜单全部未选中状态；
4、点击删除按钮
日志提供：
如图：
![image](https://user-images.githubusercontent.com/6039515/122731386-d2a2ec80-d2ad-11eb-9ef6-96271c9a8914.png)

**Comment by elunez** [comment]
Fixed
