### ISSUE TITLE
 QueryHelp.getPredicate方法中重复添加join

### ISSUE THREAD

**Issue by ilikeclean** [elunez/eladmin#655]
1.版本: v2.6
2.环境：本地、线上
3复现步骤： @Query注解在不同字段上的joinName都是同一张表，在调用该方法后，获取到sql是每一个加注解的字段都join了一次表，这样出来的sql不是我想要的结果。请问这样是我使用注解的方式有问题吗
![image](https://user-images.githubusercontent.com/52983942/124767088-13675a80-df6a-11eb-85e8-31a2542725e2.png)
![image](https://user-images.githubusercontent.com/52983942/124767364-545f6f00-df6a-11eb-8c34-da846282fc55.png)

**Comment by shanezhiu** [comment]
你的query用的没有错，我也遇见过。
