### ISSUE TITLE
后台代码生成错误

### ISSUE THREAD

**Issue by txjhuanxian** [elunez/eladmin#67]
1:我有一张司机表，在数据库中的字段名为“driver_mobile”, model里面的属性名称为“driverMobile”
2:我选择这张表，选择“driver_mobile”的精确查询条件，执行生成代码
生成的Specification类代码如下（这在执行查询时会报错）：
@Override
        public Predicate toPredicate(Root<DriverInfo> root, CriteriaQuery<?> criteriaQuery, CriteriaBuilder cb) {

            List<Predicate> list = new ArrayList<Predicate>();

            if(!ObjectUtils.isEmpty(driverInfo.getDriverMobile())){
                /**
                * 精确
                */
                list.add(cb.equal(root.get("driver_mobile").as(String.class),driverInfo.getDriverMobile()));
            }
                Predicate[] p = new Predicate[list.size()];
                return cb.and(list.toArray(p));
        }

正确的结果应该是：
@Override
        public Predicate toPredicate(Root<DriverInfo> root, CriteriaQuery<?> criteriaQuery, CriteriaBuilder cb) {

            List<Predicate> list = new ArrayList<Predicate>();

            if(!ObjectUtils.isEmpty(driverInfo.getDriverMobile())){
                /**
                * 精确
                */
                list.add(cb.equal(root.get("driverMobile").as(String.class),driverInfo.getDriverMobile()));
            }
                Predicate[] p = new Predicate[list.size()];
                return cb.and(list.toArray(p));
        }

**Comment by elunez** [comment]
收到，这个我看看

**Comment by elunez** [comment]
修改下 QueryService.ftl
改成
```
<#if column.columnQuery = '1'>
                /**
                * 模糊
                */
                list.add(cb.like(root.get("${column.changeColumnName}").as(${column.columnType}.class),"%"+${changeClassName}.get${column.capitalColumnName}()+"%"));
            </#if>
            <#if column.columnQuery = '2'>
                /**
                * 精确
                */
                list.add(cb.equal(root.get("${column.changeColumnName}").as(${column.columnType}.class),${changeClassName}.get${column.capitalColumnName}()));
            </#if>
```
