### ISSUE TITLE
请问作者是否允许我修改eladmin源码，并作为新项目进行开源

### ISSUE THREAD

**Issue by miaoyinjun** [elunez/eladmin#677]
@elunez，将eladmin作为子模块引入，
后端修改内容大概如下：

1. 后端代码几乎所有文件全部修改，保留了原业务逻辑
2. 新的注释、代码规范
3. 引入了日志模块https://github.com/mouzt/mzt-biz-log，并做了二次优化
4. 同时支持账号密码与短信登录，可再扩展其它方式登录
5. 引入liquibase控制数据库结构变化，支持回滚
6. 行列数据级别权限控制
7. 增加注解，入参解密，出参加密，举例：返回id主键加密，保证数据安全
8. 引入SpringBootAdmin，服务端与客户端都为当前服务，非开发模式必须登录才能使用，可查看git最后一次的提交信息，用于验证项目版本是否正确
9. 引入knife4j替换原swagger，并增加了枚举支持，可在api文档界面下拉选择枚举
10. 增加账号过期、密码过期、隔多少天强制修改密码等机制
11. 支持参数验证@RequestParam、@RequestBody
12. 后续计划增加springCloud+k8s+istio

**Comment by elunez** [comment]
可以的
