### ISSUE TITLE
是否可以加入顶部导航栏

### ISSUE THREAD

**Issue by baiydavid** [elunez/eladmin#681]
版本: v2.6
环境：本地

描述： 系统越来越多， 左侧菜单 越来越多。  此时，需要加入顶部的导航栏， 对应到系统中不同的模块，  选择不同的模块，左侧展示不同的菜单 。 
示例图如下：
![image](https://user-images.githubusercontent.com/13481447/133067280-170bf31f-4570-4935-8bed-1dc41f9619ca.png)
![image](https://user-images.githubusercontent.com/13481447/133067442-0a299aff-f375-4740-ac8b-306ec40db199.png)

**Comment by elunez** [comment]
不考虑增加，不过可以参考若依Vue版本进行修改。前端大同小异
