### ISSUE TITLE
运行出现错误：Field appMapper in me.zhengjie.modules.mnt.service.impl.AppServiceImpl required a bean of type 'me.zhengjie.modules.mnt.service.mapstruct.AppMapper' that could not be found.

### ISSUE THREAD

**Issue by maosheng1991** [elunez/eladmin#683]
你好大佬：

版本: v2.6
环境：本地
复现步骤：运行出现错误：Field appMapper in me.zhengjie.modules.mnt.service.impl.AppServiceImpl required a bean of type 'me.zhengjie.modules.mnt.service.mapstruct.AppMapper' that could not be found.
日志提供：
APPLICATION FAILED TO START
***************************
Description:
Field appMapper in me.zhengjie.modules.mnt.service.impl.AppServiceImpl required a bean of type 'me.zhengjie.modules.mnt.service.mapstruct.AppMapper' that could not be found.
Action:
Consider defining a bean of type 'me.zhengjie.modules.mnt.service.mapstruct.AppMapper' in your configuration.
谢谢。

**Comment by elunez** [comment]
看文档
