### ISSUE TITLE
使用"_","%"两个特殊字符搜索时，会搜索出全部内容

### ISSUE THREAD

**Issue by zhanghui-12** [elunez/eladmin#688]
1. 版本: v2.4
2.  环境：演示环境
3. 复现步骤：使用"_","%"两个特殊字符搜索时，会搜索出全部内容
4.  日志提供：无
5. 截图如下：

![捕获1](https://user-images.githubusercontent.com/51773834/137161152-ed56618a-9cf2-464b-a64d-db8b2ca1f7c0.JPG)
![捕获](https://user-images.githubusercontent.com/51773834/137161170-c644909f-d537-481d-82e0-fa94bb422913.JPG)

**Comment by whosmyqueen** [comment]
自己加下防SQL注入就行了
