### ISSUE TITLE
Redis 缓存loadUserByUsername的时候有问题

### ISSUE THREAD

**Issue by Tech--man** [elunez/eladmin#69]
Redis 缓存loadUserByUsername的时候，存取了非常多的数据。每个key包含了所有的用户权限信息，导致第一次登陆，获取需要重新缓存的时候都非常缓慢。只要用户多加一些就非常明显了（比如有1000个）

问题出现在user::loadUserByUsername:xxxxx获取Json数据的roles这个节点下面，嵌套查询了非常多数据

**Comment by Tech--man** [comment]
每多一个user就会多执行一句
select roles0_.user_id as user_id1_20_0_, roles0_.role_id as role_id2_20_0_, role1_.id as id1_15_1_, 
role1_.create_time as create_t2_15_1_, role1_.data_scope as data_sco3_15_1_, role1_.level as 
level4_15_1_, role1_.name as name5_15_1_, role1_.remark as remark6_15_1_ from users_roles roles0_ 
inner join role role1_ on roles0_.role_id=role1_.id where roles0_.user_id

**Comment by elunez** [comment]
可使用DTO解决，优化后不会查询Role中的关联数据
![image](https://user-images.githubusercontent.com/42142420/58232460-1d1eab80-7d6c-11e9-8dd8-0361bafd820b.png)
