### ISSUE TITLE
有点不明白怎么使用多crud，给子组件加了crud-tag进行标记了，但是报错了

### ISSUE THREAD

**Issue by undefind-cre** [elunez/eladmin#694]
![image](https://user-images.githubusercontent.com/83700119/140969239-b6a38d28-36b0-4477-959c-83173d05e402.png)
有点不明白怎么使用多crud，加了crud-tag进行标记了，但是报错了，有大佬能解惑一下么
![image](https://user-images.githubusercontent.com/83700119/140969527-3016f04a-8803-4042-9c18-b7c48916266f.png)

**Comment by elunez** [comment]
加群请教管理员：Moxun
