### ISSUE TITLE
项目部署后被nginx拦截 具体配置如下

### ISSUE THREAD

**Issue by Kernel520** [elunez/eladmin#697]
![image](https://user-images.githubusercontent.com/76543258/142635038-5e5bbe6c-6933-479e-b7dc-0d4f1330a24c.png)

![image](https://user-images.githubusercontent.com/76543258/142635150-73e6baf4-64b3-4bbe-812b-752bef598482.png)
![image](https://user-images.githubusercontent.com/76543258/142635256-de1a7b0a-ef4b-4f0e-8a7d-f518e55abeda.png)

**Comment by TimberKito** [comment]
将nginx中proxy_pass反向代理配置中url后面的/ 去掉试试
>  location /jhdj {
>         proxy_pass http://jhdjapp;
>         ...
> }

**Comment by Kernel520** [comment]
已解决 是没有配置yml 文件应用context path导致的 感谢
