### ISSUE TITLE
redis配置和线程池配置启动提示未正确代理,for example: not eligible for auto-proxying

### ISSUE THREAD

**Issue by 1332987** [elunez/eladmin#700]
提交 Issues 请提供
版本: v2.6
环境：本地+线上
复现步骤：启动项目打印日志中
日志提供：
`
 o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'asyncTaskProperties' of type [me.zhengjie.config.thread.AsyncTaskProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
`

**Comment by 1332987** [comment]
修复逻辑,注入位置添加懒加载,配置文件不要实现其它类

**Comment by 1332987** [comment]
改问题只是一个提示,没有任何影响,可以不修复.
Bean '*' of type [*] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

**Comment by elunez** [comment]
我这边尝试消除这个提示，但是没有成功。
如果可以，辛苦你这边提个 PR。谢谢

**Comment by 1332987** [comment]
> Owner
我已经解决了,但是具有破坏性,得不偿失.
对与普通的依赖注入,使用懒加载注解就可以解决,
但是对与redis配置文件这种继承其它类的要重写整个redis配置文件,使用其它方式才可以解决提示,具有破坏性

**Comment by elunez** [comment]
> 

了解了
