### ISSUE TITLE
文档中写的initDict.js在源码中找不到

### ISSUE THREAD

**Issue by lisnn** [elunez/eladmin#707]
![image](https://user-images.githubusercontent.com/36067081/144997266-74891bb4-074b-48a9-810c-6bb9900c5a25.png)

**Comment by smettycat** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by CFH-Steven** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，你发的信息我已经收到，谢谢。

**Comment by elunez** [comment]
找不到应该是废弃了
