### ISSUE TITLE
2.0 版本快来了，这次更新了很多有卵用的东西，快来看看吧

### ISSUE THREAD

**Issue by elunez** [elunez/eladmin#71]
#### 前端
1.代码生成页面调整（加入了去除表前缀的配置）
2.异常日志列表调整  #59
3.优化列表显示，所属部门显示【上级部门/部门】 （避免分公司中出现相同的部门）

##### 代码生成优化 #64
1.主键未设置自增的情况下默认采用Snowflake生成主键ID（原版本必须在数据库中设置自增主键）
2.主键为字符串（varchar(32)）的情况下默认采用UUID生成主键ID（会生成长度在32位左右的字符串）（原版本只能设置整形主键）,
3.完善代码生成后前后端的权限控制，权限名默认采用实体类名大小加操作类型，如Test类：'TEST_CREATE'
（原版本前后端默认只给了ADMIN权限 @PreAuthorize("hasAnyRole('ADMIN')")）
4.完善前端表单验证，根据非空字段自动生成表单非空验证代码（原版本前端没有表单验证）
5.新增去除表前缀的功能，需在生成器配置中设置
6.优化代码生成的ftl模板中主键类型写死的问题 #60
##### 其他优化
1.优化异常日志列表，默认不返回异常详情，通过点击异常详情按钮才获取异常详情 #59
2.优化登录，用户角色数据使用RoleSmallDTO，避免加载Role中关联数据造成资源浪费 #69

##### Bug修复
1.修复了用户管理中的岗位列表数据显示问题 #66
2.修复了代码生成器中QueryService 查询的问题 #67

趁着还没更新，赶紧提一波建议~

**Comment by elunez** [comment]
> #### 前端
> 1.代码生成页面调整（加入了去除表前缀的配置）
> 2.异常日志列表调整 #59
> 3.优化列表显示，所属部门显示【上级部门/部门】 （避免分公司中出现相同的部门）
> 
> #### 后端
> ##### 代码生成优化 #64
> 1.主键未设置自增的情况下默认采用Snowflake生成主键ID（原版本必须在数据库中设置自增主键）
> 2.主键为字符串（varchar(32)）的情况下默认采用UUID生成主键ID（会生成长度在32位左右的字符串）（原版本只能设置整形主键）,
> 3.完善代码生成后前后端的权限控制，权限名默认采用实体类名大小加操作类型，如Test类：'TEST_CREATE'
> （原版本前后端默认只给了ADMIN权限 @PreAuthorize("hasAnyRole('ADMIN')")）
> 4.完善前端表单验证，根据非空字段自动生成表单非空验证代码（原版本前端没有表单验证）
> 5.新增去除表前缀的功能，需在生成器配置中设置
> 6.优化代码生成的ftl模板中主键类型写死的问题 #60
> 
> ##### 其他优化
> 1.优化异常日志列表，默认不返回异常详情，通过点击异常详情按钮才获取异常详情 #59
> 2.优化登录，用户角色数据使用RoleSmallDTO，避免加载Role中关联数据造成资源浪费 #69
> 
> ##### Bug修复
> 1.修复了用户管理中的岗位列表数据显示问题 #66
> 2.修复了代码生成器中QueryService 查询的问题 #67
> 
> 趁着还没更新，赶紧提一波建议~

已更新，发行版迟些日子更新

**Comment by hjldev** [comment]
自动代码生成最好把相应的权限sql生成
刚才更新了一下代码，之前登录的User对象缓存到redis里面了，后面User改为了UserDTO，造成从缓存中取出来的User强转UserDTO报错，RoleSmallDTO也一样

**Comment by elunez** [comment]
> 自动代码生成最好把相应的权限sql生成
> 刚才更新了一下代码，之前登录的User对象缓存到redis里面了，后面User改为了UserDTO，造成从缓存中取出来的User强转UserDTO报错，RoleSmallDTO也一样

升级了版本肯定是要清空redis的，至于权限sql生成对我不太友好，不考虑

**Comment by AndroidKid19** [comment]
是否可以集成mybatis

**Comment by elunez** [comment]
> 新版是否可以集成mybatis

计划明年1月份开始改造mybatis版本的
