### ISSUE TITLE
代码生成器如何自定义模板？

### ISSUE THREAD

**Issue by SaulJWu** [elunez/eladmin#710]
找不到模板文件啊，想自定义模板。

**Comment by miaoyinjun** [comment]
eladmin 位置：eladmin-system/resources/template/generator/*/*.ftl
这是我修改之后的效果：https://gitee.com/miaoyinjun/boot-admin

**Comment by SaulJWu** [comment]
> eladmin 位置：eladmin-system/resources/template/generator/_/_.ftl 这是我修改之后的效果：https://gitee.com/miaoyinjun/boot-admin

好的，我研究研究，最后还是决定用EasyCode，侵入性没那么强。
