### ISSUE TITLE
请教一下，我想把JPA换成了MybatisPlus怎么处理，我这边使用的时候启动异常

### ISSUE THREAD

**Issue by twlic** [elunez/eladmin#712]
1.版本: v2.6
2.环境：本地
3.复现步骤：我把jpa换成了mybatis-plus支持，在使用日志注解时，在mapper注入的时候springboot一直启动报错
4.日志提供：
```
Description:

Field logMapper in com.lh.common.service.impl.LogServiceImpl required a bean of type 'com.lh.common.mapper.LogMapper' that could not be found.


Action:

Consider defining a bean of type 'com.lh.common.mapper.LogMapper' in your configuration.

```

**Comment by twlic** [comment]
使用场景时springcloud 公用日志模块，其他配置都是做了的，但是一直报这个错，找不到相应的解决办法

**Comment by miaoyinjun** [comment]
LogMapper 没被扫描到吧，指定下路径@MapperScan("com.boot.*.*.modules.*.mapper")
可参考：https://gitee.com/miaoyinjun/boot-admin，基于eladmin替换了mybatis-plus，其它作了增强
