### ISSUE TITLE
请教一下，按照文档配置前后端，启动时，验证码不显示，登录时提示接口请求失败，请问是什么问题呢

### ISSUE THREAD

**Issue by SSSisbusy** [elunez/eladmin#713]

**Comment by tsln1998** [comment]
JDK 版本和控制台日志发一下

**Comment by SSSisbusy** [comment]
您好，因为我之间配置的一点小错误，问题目前已经解决，非常感谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "elunez/eladmin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月22日(星期三) 下午5:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [elunez/eladmin] 请教一下，按照文档配置前后端，启动时，验证码不显示，登录时提示接口请求失败，请问是什么问题呢 (Issue #713)





 
JDK 版本和控制台日志发一下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
