### ISSUE TITLE
个人中心-修改邮箱报错

### ISSUE THREAD

**Issue by heavens420** [elunez/eladmin#714]
个人中心-修改邮箱，发送邮件时存在两个问题：
1. 当一开始数据库没有配置任何邮箱的时候，系统报错提示配置，此时获取到的邮箱对象为空，而reids会直接将这个空对象存入redis，后面即使已经配置了邮箱，但也必须手动清除指定缓存 ，否则从redis获取到的邮箱对象永远为空。
2. 仅仅修改邮箱的时候，后台逻辑并没有给邮箱加密，但是却在获取邮箱账户密码的时候调用了解密方法，导致后端直接报错，这个逻辑有很大问题。

**Comment by elunez** [comment]
无法复现

2.6 版本第一点不存在问题。
更新配置后，redis 数据也会同步更新。

第二点复现不了
