### ISSUE TITLE
起不来，停不下，只看到jar的pid不断地变化

### ISSUE THREAD

**Issue by BIGMONK** [elunez/eladmin#719]
orz

**Comment by elunez** [comment]
？

**Comment by BIGMONK** [comment]
> ？

起不来是因为端口一直没有被使用，停不下来是因为执行：ps aux | grep eladmin-system-2.6.jar，看到pid在不停的变化

**Comment by BIGMONK** [comment]
![6823e97c83685fc34f9a2b0f23f5dae](https://user-images.githubusercontent.com/18308637/150294006-99f51c6a-84e9-4d81-b5fc-2d7e813182d7.png)
重启都不行，文件删除了也不行，orz，这个一直存在，pid还不断变化

**Comment by elunez** [comment]
![image](https://user-images.githubusercontent.com/42142420/150294776-0bd08fd5-9252-45d7-bd3b-c2c4273d56a7.png)
正常的情况，你这情况我没遇到过

**Comment by BIGMONK** [comment]
误会了，这个指令本身的问题：ps -ef |grep *.jar

**Comment by BIGMONK** [comment]
误会了，这个指令本身的问题：ps -ef |grep *.jar,执行这个指令会显示一条进程信息，但是不代表这个*.jar在运行
