### ISSUE TITLE
修改主键ID类型为varchar后，前端访问模块跳转404

### ISSUE THREAD

**Issue by himozhang** [elunez/eladmin#72]
我将系统所有的主键ID类型由原来的bigint修改为varchar，并将java代码中的long修改为String类型，为什么前端访问模块时，会跳转到404页面？
是否后台在进行权限处理时，有固定规则？

**Comment by elunez** [comment]
检查返回的菜单

**Comment by himozhang** [comment]
> 检查返回的菜单

感谢，已解决，buildMenus方法中的pid一级目录判断地方没有修改为字符串判断导致的。
