### ISSUE TITLE
代码生成之后相应的权限没有生成

### ISSUE THREAD

**Issue by hjldev** [elunez/eladmin#73]
生成相应的代码之后，代码里面有控制权限，但是权限管理里面直接生成相应的权限更好，或者直接生成相应的sql语句，要不然得一个个添加

**Comment by elunez** [comment]
如果直接将权限插入到数据库有点强制性，对用户不友好，如果直接生成sql语句对我不友好，因此这个功能不考虑，（如需要，可自行定制）
