### ISSUE TITLE
ManyToMany查询，同时使用join和IN进行查询，将会产生重复数据

### ISSUE THREAD

**Issue by rdyfriends** [elunez/eladmin#748]
ManyToMany查询，同时使用join和IN进行查询，将会产生重复数据

    @Query(propName = "id", joinName = "users", type = Query.Type.IN)
    private Set<Long> userIds;

    @ManyToMany(fetch = FetchType.EAGER)
    @ApiModelProperty(value = "责任人")
    @JoinTable(name = "t_gz_plan_user",
            joinColumns = {@JoinColumn(name = "plan_id", referencedColumnName = "id")},
            inverseJoinColumns = {@JoinColumn(name = "user_id", referencedColumnName = "user_id")})
    private Set<User> users;

**Comment by elunez** [comment]
描述不清楚，无日志，暂时关闭
