### ISSUE TITLE
求教国产化适配问题，java新手

### ISSUE THREAD

**Issue by bjlfp** [elunez/eladmin#758]
数据库替换为人大金仓
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.kingbase8.Driver
      url: jdbc:kingbase8://localhost:54321/test
      username: system
      password: 123456
正常运行，之后将项目打包为war，部署到tongweb(东方通)，访问api一直404，没找到问题，系统将来会考虑适配信创相关的东西吗？应该怎么正确生成war包？

**Comment by elunez** [comment]
暂无此类考虑，生成 war 包网上很多教程

**Comment by SeptC** [comment]
问题解决了吗？我也遇到同样的问题

**Comment by CFH-Steven** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，你发的信息我已经收到，谢谢。
