### ISSUE TITLE
Vue 页面错误

### ISSUE THREAD

**Issue by 3792274** [elunez/eladmin#761]
![image](https://user-images.githubusercontent.com/19231863/181185461-f4110ad8-8b38-493a-84ef-70acf533a3a7.png)

**Comment by yu-jiang-24** [comment]
大佬，请问一下，你🈶️解决嘛？这个BUG

**Comment by povs2012** [comment]
element-ui版本更新导致的，可以回退到2.15.6版本就不报错了

**Comment by yu-jiang-24** [comment]
> 

感谢感谢 ，我试试

**Comment by NapChen** [comment]
> element-ui版本更新导致的，可以回退到2.15.6版本就不报错了

我的就是2.15.6，访问user页面也同样有这个warning
