### ISSUE TITLE
安全漏洞-远程代码执行漏洞

### ISSUE THREAD

**Issue by kekexiV** [elunez/eladmin#775]
当前版本引入的
 <groupId>com.github.whvcse</groupId>
            <artifactId>easy-captcha</artifactId>
            <version>1.6.2</version>
会引入
<groupId>org.apache.commons</groupId>
                    <artifactId>commons-text</artifactId>
1.9版本，该版本存在安全漏洞

**Comment by elunez** [comment]
已更新，谢谢
