### ISSUE TITLE
knife4j-spring-boot-starte依赖与redisson不兼容 报错

### ISSUE THREAD

**Issue by kekexiV** [elunez/eladmin#776]
该依赖
<dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-spring-boot-starter</artifactId>
            <version>3.0.3</version>
        </dependency>
在引入redisson后会报错，将swagger扫描关闭后可以正常引入

**Comment by elunez** [comment]
自行检查依赖冲突
