### ISSUE TITLE
缺少部门与角色设置

### ISSUE THREAD

**Issue by wangyonghua** [elunez/eladmin#78]
目前部门和角色在ui上面没有关联，也就是dept_role表没有数据产生，qq群暂时拒绝加入，对这部分有点疑惑，不知道是什么原因缺失，盼回复，谢谢

**Comment by elunez** [comment]
当角色的数据权限为本级或者全部的时候不会关联部门，只有自定义的情况下才会管理部门，QQ群功能正常，没有拒绝加入的情况，可以用手机，或者最新版本qq试试

**Comment by wangyonghua** [comment]
谢谢，已经GET到，mac目前最新版本的qq，华为荣耀10安卓系统qq目前都不能加群，可能是qq兼容性问题，有时间换window系统再加上
