### ISSUE TITLE
最新版的eladmin登录Decryption error

### ISSUE THREAD

**Issue by hehaokunzhenshuai** [elunez/eladmin#782]
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/60168969/205477273-d9bdad57-8a72-4b66-b774-1874539f8395.png">
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/60168969/205477277-8d788614-c441-4a46-b44a-a416b0d90815.png">

**Comment by 20254393** [comment]
我也一样..

**Comment by 20254393** [comment]
具体问题我本地跑过若依-vue的项目，和这个cookie冲突了可能，我换一个浏览器就可以登录了
