### ISSUE TITLE
登录页面验证码无法生成

### ISSUE THREAD

**Issue by hehaokunzhenshuai** [elunez/eladmin#786]
<img width="1640" alt="image" src="https://user-images.githubusercontent.com/60168969/212222208-4ec7047a-9562-42b3-8a4a-22bb82df2d2e.png">
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/60168969/212222301-55958d14-948c-4ed7-8c6d-bbff922f1735.png">

**Comment by CFH-Steven** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，你发的信息我已经收到，谢谢。

**Comment by GWillS163** [comment]
同样的问题，现在还没有解决的吗

**Comment by Kingzsf** [comment]
我也收到了同样的问题  部署后没有验证码

**Comment by elunez** [comment]
无法复现

**Comment by aronchanisme** [comment]
大家是怎么解决的？
