### ISSUE TITLE
There has a directory traversal vulnerability.

### ISSUE THREAD

**Issue by qytxhjb** [elunez/eladmin#791]
https://github.com/elunez/eladmin/blob/f3cdf8ccfced849f902f58ac95c8b0bb48d68cb4/eladmin-system/src/main/java/me/zhengjie/modules/mnt/rest/DeployController.java#L108

The name of the uploaded file is not verified here. Users can construct a cross-directory file name to delete and replace other important files on the server.Do as follows:

1、Use fiddler excute a request, my upload folder is D:/data/test , create a file 123.txt in D:/ , but filename set " /../123.txt "
![a](https://user-images.githubusercontent.com/86481544/224086954-317e1add-4509-4df7-a6a8-354cc64c90a2.png)
![b](https://user-images.githubusercontent.com/86481544/224087336-893dc315-8c44-4667-9dcc-28db0ac75e1c.png)

2、we can see the file d:/123.txt has bean deleted
![c](https://user-images.githubusercontent.com/86481544/224087806-9dc3517f-7b6d-4e76-a537-362e4eb83d52.png)

**Comment by elunez** [comment]
Fixed
