### ISSUE TITLE
按钮中间 间距是用什么样式实现的，，，很好奇你是怎么实现的，没看懂。麻烦前端大佬帮忙解答一下哈。@Moxun

### ISSUE THREAD

**Issue by java668-real1** [elunez/eladmin#793]
版本: v2.4
环境：本地/线上
复现步骤：按钮中间 间距是用什么样式实现的，，，很好奇你是怎么实现的，没看懂。麻烦前端大佬帮忙解答一下哈。@Moxun
日志提供：按钮中间 间距是用什么样式实现的，，，很好奇你是怎么实现的，没看懂。麻烦前端大佬帮忙解答一下哈。@Moxun
![Screenshot of a comment on a GitHub issue showing an image, added in the Markdown, of an Octocat smiling and raising a tentacle.](https://java668.github.io/page/file/d4eb3c082243d3541ac27f8a169e40a.jpg)

**Comment by java668** [comment]
找到原因了。

**Comment by moxun1639** [comment]
两个inline-block元素间如果换行，则会产生空白间隙
```html
<div>
    <span>One</span>
    <span>Two</span>
<div>
```
<div>
    <span>One</span>
    <span>Two</span>
<div>

---

```html
<div>
    <span>One</span><span>Two</span>
<div>
```
<div>
    <span>One</span><span>Two</span>
<div>
