### ISSUE TITLE
新增模块前端访问后端接口报错404

### ISSUE THREAD

**Issue by xupt-aimulvcheng** [elunez/eladmin#796]
包名取得叫me.zhegjie，在System 模块的 pom.xml 的 dependencies 节点加入创建的子模块，最后启动还是报404

**Comment by elunez** [comment]
https://eladmin.vip/pages/020101/#%E6%96%B0%E5%BB%BA%E6%A8%A1%E5%9D%97%E5%90%8E%E8%AE%BF%E9%97%AE%E6%8E%A5%E5%8F%A3-404
