### ISSUE TITLE
用户管理/角色管理，只能操作别人，不能操作自己

### ISSUE THREAD

**Issue by zhou1002553773** [elunez/eladmin#798]
版本: v2.5 目前最新的版本
环境：本地
复现步骤：
用admin账号登录，admin有超级管理员、普通用户两个角色，操作超级管理员和普通用户角色的菜单报错  Caused by: org.hibernate.HibernateException:Found shared references to a collection: me.zhengjie.modules.system.domain.Role.depts ，操作其他角色的菜单能正常保存

用只具有普通用户角色的账号登录，操作超级管理员角色成功，操作普通用户角色失败，报错 Caused by: org.hibernate.HibernateException: Found shared references to a collection: me.zhengjie.modules.system.domain.Role.depts

操作用户信息同理，只能操作别人的，操作自己的就报错

日志提供：

[errorlog.txt](https://github.com/elunez/eladmin/files/11592863/errorlog.txt)

**Comment by elunez** [comment]
已修复
https://github.com/elunez/eladmin/issues/801
