### ISSUE TITLE
前端界面

### ISSUE THREAD

**Issue by 846027729** [elunez/eladmin#799]
![image](https://github.com/elunez/eladmin/assets/64539202/b98b75fb-a42e-4273-8197-3c92476fabca)
界面缩小时，滚动条附近样式排版有问题

**Comment by elunez** [comment]
<img width="1512" alt="image" src="https://github.com/elunez/eladmin/assets/42142420/02a5e4c3-336d-4e77-ac4a-8a81f81f3267">
谷歌浏览器，无法复现。

**Comment by 846027729** [comment]
![image](https://github.com/elunez/eladmin/assets/64539202/f9929da9-ea44-4651-8e11-9db4e316125b)
同谷歌，在线预览环境，浏览器缩小至67%时出现

**Comment by elunez** [comment]
无法复现，这种问题忍忍吧
