### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by qhl100** [elunez/eladmin#8]
Field menuMapper in me.zhengjie.system.service.impl.MenuServiceImpl required a bean of type 'me.zhengjie.system.service.mapper.MenuMapper' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'me.zhengjie.system.service.mapper.MenuMapper' in your configuration.

**Comment by jieinchina** [comment]
i'm running the same issue,how to fix it?
