### ISSUE TITLE
sql文件中code_column_config表创建语句问题

### ISSUE THREAD

**Issue by huangrw** [elunez/eladmin#806]
sql文件中创建code_column_config表的语句和是不是缺少了date_annotation字段 ? 
配置代码生成时会报错,加上改字段后正常.

**Comment by elunez** [comment]
<img width="709" alt="image" src="https://github.com/elunez/eladmin/assets/42142420/8cebd347-5c22-4278-bcb9-21d647cc30cc">
之前误删过，后面提交加上去了

**Comment by huangrw** [comment]
你好, 和代码对比发现,应该加在code_column_config表里,而不是加在code_gen_config表里

**Comment by elunez** [comment]
> 你好, 和代码对比发现,应该加在code_column_config表里,而不是加在code_gen_config表里

好的，我更新下，谢谢
