### ISSUE TITLE
JwtPermissionService的mapToGrantedAuthorities方法，role.getPermission(),有没可能返回空？

### ISSUE THREAD

**Issue by 305371179** [elunez/eladmin#81]
`
JwtPermissionService的mapToGrantedAuthorities 方法
return roles.stream().flatMap(role -> role.getPermissions().stream())
                .map(permission -> new SimpleGrantedAuthority(permission.getName()))
                .collect(Collectors.toList());
`
role.getPermissions()的结果有空的可能吧？

**Comment by elunez** [comment]
是的

**Comment by 305371179** [comment]
如果这样role.getPermissions()调用strem()方法不就报错了吗？

**Comment by elunez** [comment]
你试试就知道了
