### ISSUE TITLE
求助：验证码无法正常生成

### ISSUE THREAD

**Issue by aronchanisme** [elunez/eladmin#811]
请问下，我在服务端无法生成验证码
<img width="1913" alt="image" src="https://github.com/elunez/eladmin/assets/46433151/1b311e67-b679-4bb9-98d0-fde4df8b098b">

但在本地可以
<img width="1196" alt="image" src="https://github.com/elunez/eladmin/assets/46433151/e0487c8c-ef49-48cd-b01a-40c0f9fe0bc3">

不知道是什么原因呢？服务端的nginx配置，不知是否正确？proxy打头的那些配置，如果打开，会出现white page问题
```bash

    server
    {
        listen 80;
        server_name 139.x.x.x.  # 我的服务器外网IP
        index index.html;
        root  /data/chenhaolang/tools/app_test/eladmin/frontend/dist;  #dist上传的路径
        # 避免访问出现 404 错误
        location / {

          try_files $uri $uri/ @router;
          index  index.html;

        #proxy_pass http://127.0.0.1:8000; #这里的端口记得改成项目对应的哦
        #proxy_set_header X-Forwarded-Proto $scheme;
        #proxy_set_header X-Forwarded-Port $server_port;
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header Upgrade $http_upgrade;
        #proxy_set_header Connection "upgrade";          
  
          #try_files $uri $uri/ @router;
          #index  index.html;
        }
        location @router {
          rewrite ^.*$ /index.html last;
        }  
    } 

}
```

另外，如果我想去掉验证码直接用用户名密码登录，请问应该怎么做呢？

**Comment by aronchanisme** [comment]
补充：
1、服务端的code接口
<img width="1808" alt="image" src="https://github.com/elunez/eladmin/assets/46433151/3dd301f6-cc86-4c39-a6cd-dabc6249781f">

然后我随便填一个验证码，就会报错，无法登陆
<img width="1381" alt="image" src="https://github.com/elunez/eladmin/assets/46433151/5f4b692b-4a9d-4320-b7c9-b9554faf3194">
<img width="1912" alt="image" src="https://github.com/elunez/eladmin/assets/46433151/e0804e20-26c6-4795-8fcd-74d0c22adfce">


2、正常的本地、和demo网站的接口
<img width="1918" alt="image" src="https://github.com/elunez/eladmin/assets/46433151/66e97654-475f-4b6d-89bf-48c630de7ffd">
<img width="1914" alt="image" src="https://github.com/elunez/eladmin/assets/46433151/13d5b8eb-9da5-4d91-a62a-7edabc6cfcc8">

**Comment by wonderfulCoder1** [comment]
感谢，作者文档确实写的不清晰
