### ISSUE TITLE
踢出用户不工作

### ISSUE THREAD

**Issue by ciscolive** [elunez/eladmin#817]
![image](https://github.com/elunez/eladmin/assets/20869208/10348aae-ca1e-48ca-acbd-9d399807147f)

**Comment by l2063610646** [comment]
401，看后台报错信息，光截个接口请求失败，这能看出什么

**Comment by ciscolive** [comment]
项目是拉取最新的代码，运行期间后端接口没有报错信息，前端一直logout死循环。
