### ISSUE TITLE
几十人同时打开登录页，验证码接口会报错

### ISSUE THREAD

**Issue by shouhe11** [elunez/eladmin#819]
几十人同时打开登陆页面时，验证码加载失败，接口报错信息：
“Caused by: java.lang.Error: Probable fatal error:No fonts found.”
“java.io.IOException: 打开的文件过多”

我尝试重启java服务后恢复正常，具体报错信息详细如下：
![image](https://github.com/elunez/eladmin/assets/49010729/c58c3cbe-c778-4038-bf19-3401367735b6)
[log.txt](https://github.com/elunez/eladmin/files/12736850/3.txt)

**Comment by CFH-Steven** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，你发的信息我已经收到，谢谢。

**Comment by elunez** [comment]
什么版本

**Comment by shouhe11** [comment]
> 什么版本

很早之前的版本的，大概2年前。因为变动了很多所以没办法更新成最新版本。

**Comment by elunez** [comment]
<dependency>
            <groupId>com.github.whvcse</groupId>
            <artifactId>easy-captcha</artifactId>
            <version>1.6.2</version>
        </dependency>
        
        图形验证码现在用的这个。
        
        
        <dependency>
            <groupId>net.dreamlu</groupId>
            <artifactId>mica-ip2region</artifactId>
            <version>2.7.12</version>
        </dependency>

以前是获取ip信息容易出现这个问题，现在用了mica-ip2region，你对比修改下
