### ISSUE TITLE
搞了个分布式的框架

### ISSUE THREAD

**Issue by Lyn4ever29** [elunez/eladmin#823]
您好，您的项目很是优秀，我们一直在使用。本人不才，搞了个分布式的版本，用的是SpringCloud。
我遵循您项目的开源协议，对项目进行了部分重构，前端基本上没有改什么，后端改动较多。
项目地址：[https://github.com/Lyn4ever29/fish-cloud](https://github.com/Lyn4ever29/fish-cloud)

**Comment by CFH-Steven** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，你发的信息我已经收到，谢谢。
