### ISSUE TITLE
nodejs 版本过高，推荐使用 nodejs 12 - 16 版本

### ISSUE THREAD

**Issue by wangpeng1** [elunez/eladmin#826]
我在看常见问题的时候 发现 推荐使用 nodejs 12 - 16 版本，请问为啥不能将项支持高版本的nodejs呢？ 是鉴于什么考虑吗？

**Comment by elunez** [comment]
> 我在看常见问题的时候 发现 推荐使用 nodejs 12 - 16 版本，请问为啥不能将项支持高版本的nodejs呢？ 是鉴于什么考虑吗？

版本太高，有些人 install 的时候部分依赖有时会出现问题，所有推荐新手使用 nodejs 12 - 16 版本，便于一次就能启动成功。也没有限制说必须要用nodejs 12 - 16 版本
