### ISSUE TITLE
密码忘记了无法恢复

### ISSUE THREAD

**Issue by websecer** [elunez/eladmin#831]
后台密码忘记了，把sql里面的密文替换到了数据库里面，登录还是提示密码错误，请问密码效验是不是有其他东西参与了，替换了密文依然提示密码错误。

**Comment by elunez** [comment]
> 后台密码忘记了，把sql里面的密文替换到了数据库里面，登录还是提示密码错误，请问密码效验是不是有其他东西参与了，替换了密文依然提示密码错误。

redis 缓存清理下就行了
