### ISSUE TITLE
使用yarn会报gyp错误

### ISSUE THREAD

**Issue by wj17870569856** [elunez/eladmin#859]
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.2.0
gyp info using node@16.20.0 | darwin | arm64
gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v16.20.0/node-v16.20.0-headers.tar.gz

gyp http fetch GET https://nodejs.org/download/release/v16.20.0/node-v16.20.0-headers.tar.gz attempt 1 failed with ETIMEDOUT
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v16.20.0/node-v16.20.0-headers.tar.gz failed, reason: connect ETIMEDOUT 104.20.22.46:443
gyp ERR! stack at ClientRequest.<anonymous> (/Users/vincin/.config/yarn/global/node_modules/minipass-fetch/lib/index.js:130:14)
gyp ERR! stack at ClientRequest.emit (node:events:513:28)
gyp ERR! stack at _destroy (node:_http_client:874:13)
gyp ERR! stack at onSocketNT (node:_http_client:891:5)
gyp ERR! stack at processTicksAndRejections (node:internal/process/task_queues:84:21)
gyp ERR! System Darwin 23.5.0
gyp ERR! command 

即使我降低node版本，也还是会报这个gyp错误， v12~v16都试过了，请问还有其他方案吗

**Comment by elunez** [comment]
这个错误信息表明在使用 `node-gyp` 编译 Node.js 原生模块时，下载 Node.js 头文件失败了，原因是连接超时 (`ETIMEDOUT`)。这通常是网络连接问题或防火墙设置导致的。可以尝试以下解决方案：

1. **检查网络连接**：确保你的网络连接正常，可以访问外部网站。

2. **更换网络**：尝试使用不同的网络环境，比如手机热点。

3. **代理设置**：如果你在公司网络，可能需要配置网络代理。可以在终端中设置 `HTTP_PROXY` 和 `HTTPS_PROXY` 环境变量。

4. **重试**：有时候网络问题是暂时的，再试一次可能就成功了。

5. **手动下载**：如果自动下载一直失败，可以手动下载 `node-v16.20.0-headers.tar.gz` 文件，然后放到合适的目录中。

6. **防火墙设置**：检查防火墙设置，确保没有阻止相关的网络请求。

如果这些方法都不奏效，可能需要进一步检查网络配置或联系网络管理员。

chatgpt 的回答
