### ISSUE TITLE
分页查询可以封装一下

### ISSUE THREAD

**Issue by d15801543974** [elunez/eladmin#87]
可以自定义注解，提取为公共的分页方法，减少代码量 更优雅的实现分页查询
 
我已经在你的项目中实现了demo  作者可以查看一下吗？

**Comment by d15801543974** [comment]
[工具类.zip](https://github.com/elunez/eladmin/files/3245728/default.zip)

1. 将工具类放入项目
2. 
![7U9B%}3BF_SOAKQB_30PL%V](https://user-images.githubusercontent.com/23231997/58774270-32f56180-85f3-11e9-8944-7a8ae50af5dc.png)
3.
![OH@K ~H3~5FZ1NW}NK{4$G](https://user-images.githubusercontent.com/23231997/58774315-659f5a00-85f3-11e9-8292-664090d66cca.png)

望采纳！

**Comment by elunez** [comment]
good！
