### ISSUE TITLE
给作者的5个建议。项目很棒！！

### ISSUE THREAD

**Issue by Zetting** [elunez/eladmin#9]
给作者几个建议：
1.权限管理和菜单管理不建议分开，因为这样会到时权限和菜单不统一的问题，而且分开配置略多一步；
2.持久层建议用mybatis plus
3.swagger文档建议换成其他版本的，该版本用起来好变扭
4.所有接口的响应，建议采用如下格式:
  4.1 非分页响应固定字段，code，message，data
  4.2 分页响应固定字段，code，message，data，totalSize
5.登录页面比较普通，有一点low，建议优化，其他页面超级漂亮

总体来说，eladmin，界面超级漂亮，代码逻辑比较优化，给作者100个赞！！继续加油

**Comment by elunez** [comment]
菜单是和角色绑定的，角色才是和权限绑定的，mybatis plus版本已经在改了，swagger可以自己修改，接口请求返回的字段可以根据自己需求修改，登录页面已经改好了，下个版本更新
![QQ截图20190114111052.png](https://i.loli.net/2019/01/14/5c3bfea41cd3a.png)
