### ISSUE TITLE
who is  jie 

### ISSUE THREAD

**Issue by dawangdedawang5** [elunez/eladmin#91]
so good.study many。

**Comment by dawangdedawang5** [comment]
![image](https://user-images.githubusercontent.com/30396074/58943848-35061e80-87b3-11e9-994c-2ab26ceaf303.png)

**Comment by dawangdedawang5** [comment]
这里不应该是查询的不是is_pause为0的定时任务吗，也就是启用的任务。

**Comment by elunez** [comment]
isPause = false 也就是启用的任务

**Comment by dawangdedawang5** [comment]
对啊。可是注释上写的是  查询不是启用的任务。

**Comment by dawangdedawang5** [comment]
还有，请问下jie 是哪一位啊。

**Comment by elunez** [comment]
> 对啊。可是注释上写的是 查询不是启用的任务。

注解没改过来，jie 是我，我姓郑

**Comment by dawangdedawang5** [comment]
很棒棒哦~

**Comment by dawangdedawang5** [comment]
zheng jie。还以为是个软妹子。
